### ISSUE TITLE
그리드 옵션 keyColumnName 값을 부여했을때 문제

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#10]
그리드 로우를 더블클릭하면 빈줄이 하나씩 늘어남.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
`keyColumnName` 값을 지정하는 것만으로는 해당 상황이 재현이 되지 않는데, 
혹시 그리드 생성시에 어떤 옵션을 사용했는지 좀더 자세하게 알 수 있을까요?

**Comment by globeer** [comment]
안녕하세요. 

좋은 그리드 만들어 주셔서 감사합니다.

제가 만든 그리드 생성 옵션 입니다. 
아래와 같이 생성하였는데 keyColumnName 을 지정하면 질의했던 현상이 나타납니다.
추가로 bootstrap theme gentelella 적용해서 개발중입니다.

	    var gridDblogsOption = {
	   	    el: $('#gridDblogs'),
	   	    selectType: 'checkbox',
	   	    autoNumbering: false,
	   	    headerHeight: 30,
	   	    bodyHeight: 381,
//	   	    keyColumnName: "user_id",  지정하면 버그발생함
	   	    minimumColumnWidth: 20,
	   	    singleClickEdit: false,
	   	    isFixedHeight: true,
		    pagination: true,
	   	    columnModelList : columnModelList
	    };	

	gridDblogs = new tui.Grid(gridDblogsOption);

**Comment by dongwoo-kim** [comment]
@globeer 
생성 옵션 만으로 확실하게 파악은 어렵지만..
`keyColumnName`을 지정하는 경우 해당 `columnName` 의 값이 `rowKey` 가 되며, 이 값은 null 이 되거나 중복이 되면 안됩니다. (위의 경우 Row 데이터 내부에 `user_id` 라는 값이 반드시 유니크하게 지정되어야 합니다.)
그리드 내부에서 `rowKey`에 해당하는 데이터가 `null` 인 경우에는 Dummy Row (빈 영역에 격자 무늬만 보여주기 위한 가짜 Row)로 판단해서 더블클릭 시 행을 추가 하도록 되어 있습니다. 

`user_id` 를 key 데이터로 사용하실 의도라면 실제 데이터가 잘 지정되어 있는지 한번 확인해 보시면 좋을 것 같습니다.
