### ISSUE TITLE
컬럼값 정렬 예제 및 컬럼고정 예제 부탁드립니다.^^;

### ISSUE THREAD

**Issue by chamgosu** [nhnent/tui.grid#102]
정말 유용한 APT를 만들어주셔서 진심으로 감사드립니다.^^

다만 많은 기능의 있다는 것을 알면서도 지식이 짧은지라 명령어 별로 사용예제가 많았으면 하는 바램입니다.^^;;

특히 컬럼값 정렬 기능과 컬럼고정 기능을 꼭 적용해 보고 싶은데 간단한 예제가 절실합니다.ㅜㅜ;

간곡히 부탁드립니다.^^ㅋ

**Comment by seonim-ryu** [comment]
@chamgosu 
안녕하세요. 그리드를 사용해주셔서 감사합니다. :)

먼저 **컬럼값 정렬** 기능의 경우, 다음 2가지 경우로 사용을 구분할 수 있습니다.

1. 옵션 설정
- `columns`(각 컬럼을 설정하는 옵션)의 하위 옵션 사용
- `sortable: true`로 설한 컬럼의 헤더에 정렬 버튼 생성
- 정렬 버튼을 통해 오름차순/내림차순으로 행 데이터 상태를 변경할 수 있음

```js
{
  columns: [
    {
        sortable: true,
        title: '정렬 테스트',
        name: 'c1'
    },
    // ...
  ]
}
```
![2018-04-06 2 41 17](https://user-images.githubusercontent.com/18183560/38404987-9888fd06-39a8-11e8-967b-27fa6ae4009a.png)

2. API 호출
- 헤더 내 정렬 버튼을 사용하지 않고 직접 정렬 기능을 구현하는 경우 사용
- 정렬 기능 관련 메서드 : `sort()`, `unSort()`, `getSortState()`
```js
grid.sort('c1'); // ascending
grid.sort('c1', false); // descending
```

**고정 컬럼** 기능도 생성 옵션 사용과 API 호출의 경우로 각각 사용할 수 있습니다.

1. 옵션 설정
- `columnOptions`(전체 컬럼에 대한 설정 옵션)의 하위 옵션 사용
- `frozenCount`에 설정한 값만큼 고정 컬럼 영역(고정 컬럼 보더 기준으로 왼쪽 영역에 해당)이 생성됨
- `frozenBorderWidth`에 설정한 값만큼 고정 컬럼 보더 두께가 지정됨
```js
{
  columnOptions: {
    frozenCount: 2,
    frozenBorderWidth: 2
  }
}
```

2. API 호출
- 파라미터 값만큼 고정 컬럼 영역이 생성됨

```js
grid.setFrozenColumnCount(3);
```

추후 개선 사항으로 지금보다 더 많은 예제들을 제공할 예정이며 의견주셔서 감사합니다.
그리고 이후 이슈 등록 시에는 꼭 [이슈 템플릿](https://github.com/nhnent/tui.tree/blob/master/ISSUE_TEMPLATE.md)에 맞추어 작성 부탁드리겠습니다. :)
