### ISSUE TITLE
그리드에서 데이터 표시할때 한개 데이터를 여러줄로 표시 가능할까요?

### ISSUE THREAD

**Issue by akqjqthr** [nhnent/tui.grid#105]
아래와 같은 형태로 헤더와 데이터값 출력이 가능할까요?
가능하면 혹시 샘플코드를 알려주실 수 있나요?
![test](https://user-images.githubusercontent.com/2058873/38488302-05637e16-3c1e-11e8-839e-2f9cfc5d71db.png)

그리고 셀 선택되는걸 비활성화 할 수 없을까요. 
스마트폰에서 키보드가 올라와서요.
이 부분만 해결되면 스마트폰에서도 사용가능할꺼 같은데요.

**Comment by seonim-ryu** [comment]
@akqjqthr 
첫 번째 문의주신 형태의 그리드의 경우,
**이름**, **연락처**에 해당하는 헤더 영역은 [`header.complexColumns` 옵션](https://nhnent.github.io/tui.grid/latest/tutorial-example03-complex-columns.html)을 사용해 처리할 수 있으며
**번호**의 경우 [행 머지(`_extraData.rowSpan`) 기능](https://nhnent.github.io/tui.grid/latest/tutorial-example06-using-extradata.html)을 활용해 원하는 형태로 표현은 가능합니다.

```js
// 그리드 생성 옵션
var options = {
    header: {
        complexColumns: [
            {
                title: 'c1',
                name: 'mergeColumn1',
                childNames: ['name']
            },
            {
                title: 'c2',
                name: 'mergeColumn2',
                childNames: ['artist']
            }
        ]
    }
    // ..
};
```
```js
// 그리드 데이터
var data = [
    {
        name: 'Beautiful Lies',
        artist: 'Birdy',
        _extraData: {
            rowSpan: {
                _number: 2 // rowHeaders 영역에서 행 번호 컬럼에 해당
            }
        }
    },
    {
        name: 'X',
        artist: 'Ed Sheeran'
    },
    {
        name: 'Moves Like Jagger',
        artist: 'Maroon5',
        _extraData: {
            rowSpan: {
                _number: 2
            }
        }
    },
    {
        name: 'A Head Full Of Dreams',
        artist: 'Coldplay'
    },
    // ...
];
```
다만 이 경우 행 번호(`rowNum`)가 병합된 순서대로 오름차순 되지 않기 때문에
오토 넘버링을 하기 위해서는 `rowHeaders.template`을 사용해 행 번호를 가공해줘야 합니다.

```js
// 그리드 생성 옵션
var options = {
    rowHeaders: [
      {
          type: 'rowNum',
          title: 'No.',

          /**
           * Customizing when row header type is 'rowNum'
           * @param {object} props
           *     @param {string} props.content - Original data
           */
          template: function(props) {
              tmpl = '<span>' + Math.ceil(props.content / 2) + '</span>';
              return _.template(tmpl)(props); // underscore template function
          }
      }
    ]
    // ...
};
```

추가로 현재 셀 선택(포커스 및 셀렉션)에 대한 스타일 제어는 가능하나 액션 자체를 비활성화하는 기능은 제공하고 있지 않습니다.
모바일 디바이스에서 소프트 키보드 비활성화는 기능 개선 이슈에 등록되어 처리될 예정입니다.

위 내용들 참고해주시고 추후 등록되는 이슈들은 [이슈 템플릿](https://github.com/nhnent/tui.grid/blob/master/docs/ISSUE_TEMPLATE.md)에 작성 부탁드리겠습니다. :)

**Comment by akqjqthr** [comment]
rowSpan으로 2개의 데이터를 하나의 셀로 합치는건 가능한데
1개의 그리드 데이터값으로 여러줄 표현하는건 안될까요?

**Comment by seonim-ryu** [comment]
@akqjqthr
그리드는 모든 행이 동일한 데이터 값을 가지고 있더라도 행마다 1개씩 데이터를 가지고 있어야 합니다.
이슈 클로즈합니다.
