### ISSUE TITLE
컬럼 크기를 줄이면 이상해지는 문제

### ISSUE THREAD

**Issue by wordcop** [nhnent/tui.grid#106]
## Version

v2.10.0
## Development Environment

Chrome / [win10]
![bug](https://user-images.githubusercontent.com/8130963/38531861-1452a192-3cad-11e8-9ac1-ad11cc2ae3da.jpg)
컬럼 크기를 줄이고 선택을 하면 선택이 저런 식으로 이상하게 됩니다..

## Current Behavior

```js
// Write example code
```

**Comment by seonim-ryu** [comment]
@wordcop 
현재 재현이 안되고 있어 생성 옵션 또는 API 정보를 전달해주시면 감사하겠습니다. :)
