### ISSUE TITLE
그리드 사이즈 동적 조정 문의

### ISSUE THREAD

**Issue by rapune** [nhnent/tui.grid#107]
## Version
2.9.1

## Development Environment
Chrome, win7

## Current Behavior
그리드 사이즈를 동적으로 제어하는 방법이 있는지요?
화면중에 접고 펴는 화면이 있는데, 화면을 접었을시에 rside-area 최초 렌더링된 사이즈로 고정되어 화면이 당겨지나, 여백이 남는현상이발생하여 그리드가 틀어집니다.

제공 메소드인 refreshLayout을 사용해보았으나 화면이 제어되지는 않았습니다. 혹 이런 케이스에 그리드 사이즈를 동적으로 제어하는 방법이 있는지요?

확인 부탁드립니다.

감사합니다.

-- 현상 캡처
(before)
![before](https://user-images.githubusercontent.com/14829791/38719200-96613222-3f2b-11e8-8996-222d1428f3a8.PNG)

(after)
![after](https://user-images.githubusercontent.com/14829791/38719189-8ce57032-3f2b-11e8-846b-616f182843a9.PNG)

**Comment by seonim-ryu** [comment]
@rapune 
현재 UI만으로는 현상 확인은 어려우나, 좌측의 히든 메뉴와 우측 그리드를 감싸는 엘리먼트의 `position` 상태에 따른 이슈로 보입니다.

아래 예제 코드에서는 `refreshLayout()` API가 정상 호출되며 참고바랍니다.

또한 동적으로 그리드 너비를 조정하는 API로는 [`setWidth()`](https://nhnent.github.io/tui.grid/latest/Grid.html#setWidth)가 있습니다.

```html
<!-- left-side menu -->
<div id="menu" style="float:left;width:200px;height:800px;">
  <button id="btn-close">close</button>
</div>

<!-- right-side area -->
<div id="grid-wrapper" style="float:left;width:800px;">
  <div id="grid"></div>
</div>
```
```js
var grid = new tui.Grid({
    el: $('#grid'),
    data: [ ... ],
    columns: [
        {
            title: 'Name',
            name: 'name',
            width: 100
        },
        {
            title: 'Artist',
            name: 'artist',
            width: 100
        },
        {
            title: 'Type',
            name: 'type',
            width: 100
        },
        {
            title: 'Release',
            name: 'release',
            width: 100
        },
        {
            title: 'Genre',
            name: 'genre',
            width: 100
        }
    ]
});

$('#btn-close').on('click', function() {
  $('#menu').width(10 + 'px');
  $('#grid-wrapper').width(990 + 'px');

  grid.refreshLayout();
});
```
