### ISSUE TITLE
Pagination 질문

### ISSUE THREAD

**Issue by JiHong88** [nhnent/tui.grid#110]
## Development Environment

개발환경은
spring boot, freemarker, mybatis 입니다.

## Current Behavior

```js
instance.use('Net', {
perPage: 5,
readDataMethod: 'GET',
api: {
readData: newData
}
});
```
위 처럼 쓰지 않고

instance.setData(newData) 로 데이터를 채운후에

페이징을 하고싶은데 어떻게 하나요

**Comment by JiHong88** [comment]
instance.use('Net', {
        perPage: 5,
        readDataMethod: 'GET',
        api: {
            readData: newData
        }
    });

위 처럼 쓰지 않고

instance.setData(newData) 로 데이터 채운후에

페이징을 하고싶은데 어떻게 하나요

**Comment by seonim-ryu** [comment]
@JiHong88 
먼저 그리드를 사용해주셔서 감사합니다 :)

직접 서버 통신 및 페이지네이션을 구현하시기 위해서는
그리드에서 사용하고 있는 [페이지네이션 컴포넌트](https://github.com/nhnent/tui.pagination)를 사용하시면 처리 가능합니다.

`getPagination` API를 사용해 그리드 내부에 생성된 페이지네이션 컴포넌트에 대한 인스턴스를 가져올 수 있으며,
페이징 버튼 클릭 시에 발생하는 커스텀 이벤트(`beforeMove`, `afterMove`)를 통해 서버 통신 및 데이터 세팅을 구현할 수 있습니다.

```js
var pagination = grid.getPagination();

pagination.on('beforeMove', function(ev) {
  var page = ev.page;

  search(page); // implements server request and data setting
});
```
