### ISSUE TITLE
summary 출력 시 다른 컬럼 참조 방법 문의

### ISSUE THREAD

**Issue by dhyu** [nhnent/tui.grid#111]
## Version
version: 2.10.0

## Development Environment

개발 환경은 .net에서 진행중입니다.

## Current Behavior

summary 기능을 이용하고 하는데요.
summary 영역에서 같은 row의 다른 컬럼값을 참조한 평균을 구하고자 합니다.
가능한 방법에 대해 문의드립니다.
```js
// Write example code
```

**Comment by seonim-ryu** [comment]
@dhyu 
먼저 그리드를 사용해주셔서 감사합니다. :)
아쉽게도 다른 컬럼의 서머리 값을 가져오는 기능은 제공하고 있지 않습니다.
