### ISSUE TITLE
열 이동 기능문의

### ISSUE THREAD

**Issue by rapune** [nhnent/tui.grid#112]
## Version
2.9.1

## Development Environment
Chrome, windows7

## Current Behavior
혹시 toast grid드에서 열 이동 기능을 지원하는지 문의드립니다.
api 문서상으로는 보이지 않네요..;

**Comment by seonim-ryu** [comment]
@rapune 
UI로는 제공되고 있지 않으나 API를 사용하면 처리가 가능합니다.
그리드 생성 시 `columns`에 세팅한 값의 순서를 변경하여 `setColumns()`를 호출하면 열 순서를 변경할 수 있습니다.
* https://nhnent.github.io/tui.grid/latest/Grid.html#setColumns
