### ISSUE TITLE
Implement the filter option to show specific rows

### ISSUE THREAD

**Issue by seonim-ryu** [nhnent/tui.grid#113]
## 이슈의 개요

MS 액셀, 구글 스프레드시트와 같은 애플리케이션에서는 각 컬럼(column, 열)별로 조건에 따라 해당하는 값에 대한 로우(row, 행)를 보여주는 '필터(filter)' 기능을 제공한다.
데이터가 많은 경우 조건에 따른 행만 보고 싶은 니즈가 있으며, 그리드 내부 UI를 통해 필터 기능을 편리하고 사용할 수 있도록 하는 것이 목적이다.

### UML

![grid-uml](https://user-images.githubusercontent.com/18183560/39742089-2912303a-52d7-11e8-9eba-2b6a00257293.png)

* UML은 [`src/js`](https://github.com/nhnent/tui.grid/tree/master/src/js) 경로의 이하 파일들에 대한 구조이다.
    * 클래스를 묶은 패키지는 폴더에 해당된다. (예: Model.Data -> `model/data` 폴더)
    * 클래스명은 각 모듈 파일의 실제 모듈명에 해당된다. (예: Grid -> `grid.js` 파일의 모듈명)
* 사전 과제를 수행하기 위해 필수로 이해해야 하는 최소 모델만을 명시하였다.

### 기본 구조

* 그리드는 [Backbone.js](http://backbonejs.org/)에 대한 디펜던시가 있다.
* MV 패턴을 따르며 기본적인 뷰, 모델은 백본에서 상속받아 생성한다. 그 외 모듈은 [tui-code-snippet](https://github.com/nhnent/tui.code-snippet)의 `defineClass`를 사용해 생성한다.
* 그리드의 코어 클래스이자 퍼블릭 API가 노출되어 있는 모듈은 `Grid`에 해당된다.

#### 모델

* 그리드 인스턴스 생성 시 옵션을 넘겨 그리드 내부에서 사용하는 모델의 기본 값을 세팅한다.
```js
var options = {
    element: target,
    scrollX: true,
    ...
};

var instance = new tui.Grid(options);
```
* 그리드 데이터는 `setData` 메서드 또는 `data` 생성 옵션을 통해 세팅할 수 있으며, 데이터를 관장하는 모델은 `Model.Data.RowList`에 해당된다. 입력된 데이터 배열의 각 요소 값은 `Model.Data.RowList`의 모델 즉, `Model.Data.Row`에 매핑된다. 그리드 내부에서는 `dataModel`로 사용하고 있다.
```js
var data = [
  {
    c1: 'foo',
    c2: 'bar',
    c3: 'baz'
  },
  {
    c1: 'foo2',
    c2: 'bar2',
    c3: 'baz3'
  },
  ...
];

instance.setData(data);
```

#### 뷰

* 그리드는 총 4개 테이블 영역으로 구성된다. `lside`는 `LsideFrame`, `rside`는 `RsideFrame` 클래스에 해당된다.
    - 헤더 (lside + rside)
    - 바디 (lside + rside)

| lside header | rside header |
| --- | --- |
| lside body | rside body |

* 디폴트 옵션만으로 생성될 때는 다음과 lside 영역 너비가 0으로 생성되며, 메타 컬럼 옵션(`rowHeaders`) 또는 고정 컬럼 옵션을 사용하면 `lside` 영역이 늘어나게 된다.

| | rside header |
| --- | --- |
| | rside body |

* 각 `lside`, `rside` 프레임에서는 `View.RowList` 클래스를 통해 그리드 행 리스트를 렌더링하며, 이 때 사용되는 뷰 모델은 `Model.RowList`에 해당된다.
* 행 단위까지의 렌더링은 `View` 레이어에서 관장하며, 셀(cell) 단위의 렌더링은 `Painter` 레이어에서 처리한다.
* 기본 셀은 데이터만 표시되며 [`editOptions` 옵션](https://nhnent.github.io/tui.grid/api/tutorial-example04-input-types.html)에 따라 여러 종류의 input을 셀에 렌더링하고 사용할 수 있다.

#### 이벤트

* 그래드 내부의 이벤트는 옵저버 패턴을 따르며, 모델의 속성 값이 변경되면 뷰가 업데이트되는 방식으로 동작한다.
* 그리드의 [퍼블릭 이벤트](https://github.com/nhnent/tui.grid/blob/production/docs/custom-event.md)는 `GridEvent`, `PublicEventEmitter` 모듈을 사용해 등록할 수 있다.

### 사전 기능 설명

* UI를 통해 특정 컬럼에서 조건에 해당하는 데이터가 포함된 행들을 찾아 그리드 영역에 그려준다.
* 필터 방식은 '동등(equal) 비교'에 해당된다. 즉, 필터링 하는 값이 해당 컬럼의 데이터와 일치해야 한다.

![grid-filter](https://user-images.githubusercontent.com/18183560/39742070-1ec0f828-52d7-11e8-9537-d3c36828e0c5.png)

### 기능 명세

* [ ] 특정 컬럼에 필터 기능을 사용할 수 있는 그리드 생성 옵션을 추가한다.
``` js
var options = {
    columns: [
        ...
        {
            name: 'type',
            title: 'Type',
            // add the option for this feature
        },
        ...
    ],
    ...
};

new tui.Grid(options);
```
* [ ] 필터링 옵션을 설정하면 컬럼 헤더에 필터 아이콘이 추가된다.
* [ ] 필터 아이콘을 클릭하면 필터 조건을 컨트롤 할 수 있는 팝업 레이어가 생성된다.
* [ ] 필터 관련 디자인 요소(아이콘, 팝업 레이어)에 대한 스타일은 자유롭게 구성한다.
* [ ] 다음 2가지 방식으로 필터링을 할 수 있으며 input 엘리먼트를 사용해 구현한다.
    * [ ] 특정 1개 값 필터링 : `input[type='text']`로 필터 값 검색
    * [ ] 다수 값 필터링 : `input[type='checkbox']`로 필터 값 선택
* [ ] 필터 팝업 레이어가 열려있는 상태에서 그리드 영역을 클릭하면 레이어가 사라진다.
* [ ] 필터 기능에 대한 모델-뷰(MV)가 반드시 생성되어 있어야 한다.

## 선택 요구 사항

* [ ] 위에 명시된 필터 기능이 여러 개 컬럼에 적용되어 있는 경우를 구현해본다.
* [ ] 필터 값이 숫자인 경우, 동등 비교 외에 다른 필터링 조건(예: `>=`, `<=`, `!==`)을 줄 수 있다. 이 경우를 고려해 생성 옵션을 확장하고 다른 UI의 레이어 팝업을 구성해본다.
* [ ] 필수 요구 사항에 대한 테스트 케이스(TC)를 작성한다.

## 커밋 메세지 가이드

개발 전 리포지터리의 `docs` 폴더 하위 문서들을 숙지하고 다음 양식에 맞게 커밋 메세지를 작성한다.

* [Commit Message Convention](https://github.com/nhnent/tui.grid/blob/master/docs/COMMIT_MESSAGE_CONVENTION.md)

## 개발 환경

* 프로젝트 내의 ESLint 준수
* TC 작성 및 통과
```sh
npm run test
```
* 기능 구현 시 데모용 페이지는 examples 폴더 하위에 생성
* 크로스브라우징 (IE8 이상부터 지원)

**Comment by chamgosu** [comment]
필터옵션을 구현한 예제파일(example14-filter.html)에 있는 "useViewMode: true" 명령줄이 필터옵션 명령문인게 맞나요??

위 예제파일과 함께 아래 아이콘 파일을 다운로드하고  
images/filter-off.png
images/filter-on.png

아래 소스파일들을 수정했지만 구동이 안됩니다.^^;;
src/css/index.styl, src/css/layer.styl, src/js/common/classNameConst.js, src/js/model/condition.js, src/js/model/data/row.js, src/js/model/data/rowList.js, src/js/model/filter.js, src/js/model/filterList.js, src/js/model/manager.js, src/js/model/numberConditon.js, src/js/model/row.js, src/js/model/textCondition.js, src/js/painter/row.js, src/js/view/container.js, src/js/view/factory.js, src/js/view/filterLayer.js, src/js/view/layout/header.js

예제파일(example14-filter.html)에 위 수정파일을 호출하지 못해서 그런것 같은데 grid.js 하나만 호출하면 되나요??

초보라 많이 부족합니다. 도움 부탁드립니다.^^ㅋ

**Comment by sohee6030** [comment]
`filterOptions: {
   type: 'text'
 }`
이것이 필터옵션을 주는 것입니다.
type을 number로 설정시에는 숫자범위로 필터를 설정할 수 있습니다.

**Comment by chamgosu** [comment]
filterOptions: { type: 'text' }
알려주신데로 적용해 보았으나 결과하면에는 예시화면과 같은 필터 아이콘 이미지도 나타나지 않으며 필터도 작동되지 않습니다.
src/js/grid.js를 불러와야 하나요??
grid.js만 호출하면 필터가 이상없이 작동될까요??

**Comment by shiren** [comment]
@chamgosu 님 본 이슈는 사내에서 공개 채용을 위해 생성된 이슈입니다. 
해당 피처는 아직 릴리즈 계획이 없습니다.
다른 문의 사항은 새로 이슈를 생성해주세요
