### ISSUE TITLE
checkBox 설정관련 문의

### ISSUE THREAD

**Issue by WooDolpa** [nhnent/tui.grid#115]
안녕하세요.  웹그리드 오늘 처음 입문한 초보 개발자입니다. 
rowHeader : {
     type : 'checkbox'
}

로 checkbox 나타내는것 까지 성공했습니다. 

var grid = new tui.Grid({
    el: $('#grid'),
    data: gridData, ... }); 

checkbox 안에 value 값으로 gridData 안의 값으로 설정을 하고싶은데....  헤매고 있습니다..
api 문서에 제가 못 찾는건지 checkbox 값에 대한 설정은 안보이네요

해당 문제를 어떻게 해결할수있나요? 부탁드립니다

**Comment by seonim-ryu** [comment]
@WooDolpa 
먼저 그리드를 사용해주셔서 감사합니다. :)
해당 기능은 `_extraData` 값을 사용하면 처리 가능합니다.
아래와 같이 `rowState` 값에 초기 상태 값을 지정하면 됩니다.
* https://nhnent.github.io/tui.grid/latest/tutorial-example06-using-extradata.html

```js
var gridData = [
  {
    name: 'c1',
    _extraData: {
      rowState: 'CHECKED'
    }
  }
];
```
