### ISSUE TITLE
grid pagination 에서 처음, 이전, 다음, 마지막 표시 되지 않는 문제 

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#12]
그리드 생성시 코드입니다.

var gridDblogsOption = {
    el: $('#gridDblogs'),
    selectType: 'checkbox',
    autoNumbering: false,
    headerHeight: 30,
    bodyHeight: 381,  // 10 row 바디 기본 높이는 27 지정하면 그리드 스크롤이 안생김.
    minimumColumnWidth: 20,
    singleClickEdit: false,
    isFixedHeight: true,
    pagination: true,
    columnModelList : columnModelList
};  
gridDblogs = new tui.Grid(gridDblogsOption);

select 결과후 데이터 총 레코드 수가 변경되므로 이때 pagination 생성 및 이벤트 부여 코드

gridDblogs.setRowList(obj.data);

var pageOption = {
    itemCount: 500
  , itemPerPage: t_param.itemPerPage
  , pagePerPageList: 10
  , page: req_page
};
var pagination = new tui.component.Pagination(pageOption, $('.tui-grid-pagination'));
ㅊ.on('beforeMove', function(eventData) {
    req_page = eventData.page;
    doSearchFunc(getSelectListReq);
});
                        
이렇게 pagination 하면 처음, 이전, 다음, 마지막 페이지 이동할 수 있는 아이콘이 표시되지 않습니다.

**Comment by dongwoo-kim** [comment]
안녕하세요, @globeer 
위의 코드만으로는 정확한 상황을 알긴 어렵지만.. 
그리드에 `patination: true` 옵션을 줘서 페이지네이션 기능을 사용하는 경우, 
그리드 내부에서 `tui.component.Pagination` 인스턴스가 생성이 되기 때문에 외부에서 또다시 인스턴스를 생성하실 필요가 없습니다.
```javascript
var pagination = gridDblogs.getPagination();
```
와 같은 형태로 인스턴스를 받아와서 사용하면 문제가 해결될 수 있을 것 같습니다.
