### ISSUE TITLE
thead 방향 문의

### ISSUE THREAD

**Issue by jiwonlee22** [nhnent/tui.grid#120]
안녕하세요 toast grid사용중에 문의사항이 있어서 글 남깁니다.
현재 table head방향이 가로모드가 디폴트로 되어있는데
table head를 세로로 두고 사용할 수 있는 방법이 있는지 궁금합니다.
아니면 thead를 숨기는 기능이 있나요?
css로 숨겨서 사용해보니 cell focus 위치가 한단계 뒤로 밀리는 현상이 있어서
기능이 따로 제공이 되는지 궁금합니다.

**Comment by seonim-ryu** [comment]
@jiwonlee22
해당 기능은 현재 지원되고 있지 않습니다.
그리드는 기본적으로 헤더를 포함하는 구조이며 CSS로 제어할 경우 정상 동작하지 않으므로 해당 방식은 권장하지 않습니다.
