### ISSUE TITLE
혹시 tree-grid 형태 구현할 수 있을까요?

### ISSUE THREAD

**Issue by akqjqthr** [nhnent/tui.grid#13]
안녕하세요.
샘플을 찾아봐도 안보여서요.
treegrid 형태로 구현하는 옵션은 없을까요?

**Comment by dongwoo-kim** [comment]
안녕하세요.
아쉽게도.. 현재까지는 그리드 내부에서 Tree를 지원하지 않습니다. 
아직은 Row를 숨김/보임 처리를 하는 기능도 없어서, 직접 확장해서 구현하기도 쉽지 않을 것 같습니다.

상반기 내에 관련된 기능을 추가할 계획을 하고 있습니다만.. 정확히 원하시는 스펙이 구현될지는 모르겠네요.
필요한 스펙을 좀더 상세하게 적어주시면 구현시에 참고하도록 하겠습니다 :)
