### ISSUE TITLE
column title별로 색상을 달리하고자 하는데 도움이 필요합니다.

### ISSUE THREAD

**Issue by chamgosu** [nhnent/tui.grid#137]
## Current Behavior

column title별로 색상을 달리하고자 하는데 도움이 필요합니다.
데이터 컬럼별 색상은 바꿀수 있겠는데 컬럼 타이블 별로 색상을 바꾸는 방법을 알고 싶습니다.^^ㅋ

```js
// Write example code
```

**Comment by seonim-ryu** [comment]
@chamgosu 
현재는 각 컬럼의 헤더 영역을 컨트롤 할 수 있는 방법이 제공되고 있지 않습니다.
대신 서비스단에서 셀렉터 값으로 `th.tui-grid-cell-head`을 사용해 엘리먼트를 가져와 조건에 맞게 처리하시면 될 것 같습니다.
