### ISSUE TITLE
relationList 에서 상품분류에 따른 가격을 변경하고 싶은데 어떻게 해야 할까요?

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#14]
안녕하세요.

relationList 에서 "optionListChange" 는 'select', 'radio', 'checkbox' type만 지원하는 것으로 나와 있는데요.

상품분류에 따라 최종 상품을 선택한 경우 상품가격을 변경해 주고 싶은데, 어떻게 해야 할까요?

최종 상품 선택시에 
changeBeforeCallback 함수에서 자료를 읽어와서 어떻게 해당 칼럼 정보를 변경해야 할지 찾지 못해서요.

**Comment by dongwoo-kim** [comment]
안녕하세요.
값 자체를 직접 변경하고 싶은 경우에는 굳이 `relationList` 를 사용하지 않아도 
`changeBeforeCallback` 함수만으로 구현 가능합니다.
다음과 같이 핸들러 내부에서 `setValue()` 함수를 호출해 주시면 됩니다.

```javascript
changeBeforeCalback: function(ev) {
  var targetValue = ev.value * 100;
  grid.setValue(ev.rowKey, 'targetColumnName', targetValue);
}
```

**Comment by globeer** [comment]
감사합니다. 알려주신대로 적용하니 해결되었습니다.
