### ISSUE TITLE
grid option 에 selectType: 'checkbox' 와 columnFixCount 속성 부여시 체크박스 너비 줄어드는 현상.

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#16]
안녕하세요.

제목처럼 그리드 옵션에 체크박스와 칼럼 고정 속성을 정의할때, 체크박스 너비가 줄어드는 현상이 발생합니다.

크게 문제 될 사안은 아니지만, 가운데 정렬이 안되는 것처럼 보이는 군요.

확인 부탁드립니다.

감사합니다.

**Comment by dongwoo-kim** [comment]
안녕하세요.

`selectType: 'chekbox'` 와 `columnFixCount` 속성만 가지고는 재현이 잘 안되네요.
아마도, 다른 컬럼의 넓이 값이나 속성에 영향을 받는 것 같은데.. 
관련된 다른 옵션값들과 브라우저 환경도 같이 알려주시면 다시 확인해 보겠습니다

감사합니다.

**Comment by globeer** [comment]
그리드 옵션 중 minimumColumnWidth: 20 으로 되어 있어서 문제가 되었네요.
너비를 34 정도주니 정상으로 보입니다.
감사합니다.
