### ISSUE TITLE
페이징 관련 질문 사항입니다.

### ISSUE THREAD

**Issue by jooyh** [nhnent/tui.grid#169]
## Version
version: 2.10.1

## Development Environment
window7 / chrome / eclipse / spring 

우선 너무 감사히 툴을 잘 사용하고 있습니다.

페이징 관련 질문 사항이 있어 이렇게 연락드립니다.

페이징 시  첫 열에 no 부분에 자동 채번 되어 나오는 부분이 현재 매 패이지마다 갱신되어 1부터 시작하게 됩니다.
해당 예제가 없어 개발중에 많은 어려움을 겪고 있습니다.

현재 데이터를  프론트 단에서 

```
grid.use('Net', {
    readDataMethod: 'GET',
    api: {
        readData: '/test/testData'
    }
});
```

이러한 식으로 호출하고 컨트롤러 단에서 
```
	`@RequestMapping("/testData")
	@ResponseBody
	public Object testData(@RequestParam HashMap <String,Object> param) throws Exception{
		
		return resultData(testService.getList(param), param);
	}

	public Object resultData(List<HashMap <String,Object>> list, HashMap <String,Object> param) throws JsonProcessingException, SQLException{
		HashMap <String,Object> res = new HashMap <String,Object>();
		HashMap <String,Object> data = new HashMap <String,Object>();
		HashMap <String,Object> pagination = new HashMap <String,Object>();
		
//		List<HashMap <String,Object>> list = testService.getList(param);
		pagination.put("page", param.get("page"));
		pagination.put("totalCount", testService.getDwCnt());
		data.put("contents", list);
		data.put("pagination", pagination);
				
		res.put("result",true);
		res.put("data",data);
		
		if(list.size()>0) {
			ObjectMapper jackson = new ObjectMapper();
			String jsonString = jackson.writeValueAsString(res);
			return jsonString;
		}
		return null;
		
	}
```

이렇게  받아 전달합니다.

현재 쿼리는 페이징을 포함하여 페이지 단위로 데이터를 끊어서 가져오고 있습니다.

이러한 방식의 페이징은 컬럼 소팅시 다음페이지부터는 적용이 안되는 이유도 있고 앞서말한 채번에 대한 문제도 생기게 되어 혹시 더 나은 방법 혹은 예제가 필요하여 이렇게 연락 드렸습니다.

더불어 혹시 퍼포먼스상의 무리 없이 데이터를 모두 들고와서 페이징을 할수 있는 방안이 있다면 조언 부탁드리겠습니다.

감사합니다.

**Comment by seonim-ryu** [comment]
@jooyh 
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다 :)
외부에서 별도 처리 없이 자동으로 행 번호가 업데이트 되는 것이 정상 동작이 맞습니다.
해당 이슈는 v2.10.1 버전에서 발생한 버그로 확인되어 다음 버전 배포 시 버그 픽스될 예정입니다.
