### ISSUE TITLE
제 윈도우환경PC에서 Tui.Grid 테스트하고 싶은데....

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#17]
제 윈도우환경PC에서 Tui.Grid 테스트하고 싶은데.... 잘안되네요...
다운로드 받은파일실행해봐도 잘안되고...도와주세욘~
완전초짜라....어렵네요~

**Comment by dongwoo-kim** [comment]
안녕하세요. 
TUI 그리드는 윈도우 환경에서도 문제 없이 돌아가도록 테스트되고 있습니다.
어떤 부분이 잘 안되는지 좀더 자세하게 알려주시면 도움을 드릴 수 있을 것 같네요.

**Comment by Kanu-h** [comment]
안녕하세요. 
컬럼 소팅되는 링크나 예제는 없나요?

**Comment by dongwoo-kim** [comment]
@Kanu-h 안녕하세요.
현재는 컬럼 정렬 관련 예제가 제공되지 않고 있습니다. 
방법이 간단해서 잠깐 간략하게 설명 드리면..
```javascript
var grid = new tui.Grid({
    el: $('#grid'),
    columnModelList: [
        {
            title: 'c1',
            columnName: 'c1',
            isSortable: true
        },
        {
            ....
        }
    ]
})
```
위와 같이 `isSortable: true` 옵션을 추가해 주시면 사용 가능합니다.

**Comment by kjd95110** [comment]
답변주셔서 감사합니다. 예전 k-팝스타 시즌4에 나오신분 맞죠? ^^
노래도 잘하시고 프로그래밍도 대단하신분같아서 부럽습니다.
제가...안된다는게말이죠 다운로드받은  Tui.grid-master 폴더안에 examples 폴더내에 있는 파일들(example1,example2,example3,example4,example5,example6) 각각 더블클릭해서 실행하면  대부분
화면이 하얗게.... 아무런 결과가 안나와서요...
참고로 tui.grid-master 내에 dist 폴더,images폴더,src폴더,performance폴더,test폴더
와 js파일 모두 존재하고 있는상태이고요 인터넷 연결되어있구요..
제가 뭔가 잘못 사용한게있을가요?ㅡ.ㅡ;

**Comment by dongwoo-kim** [comment]
아;; 넵. 노래도 프로그래밍도 잘 못합니다만.. 암튼 감사합니다 ㅎ

확인해 보니깐 examples 폴더 내에 외부 자바스크립트를 불러오는 부분에서 프로토콜(https)이 생략되어 있어서 발생하는 문제인 것 같습니다. 로컬에서 직접 실행하는 상황이 고려가 안되어 있었네요. 
```html
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.js"></script>
```
와 같은 코드를
```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.js"></script>
```
같은 형태로 변경해 주시면 정상 작동할 것 같습니다.
현재 리포지토리에도 적용되어 있으니, examples 파일들만 개별로 다시 다운로드 받으셔도 됩니다.

**Comment by kjd95110** [comment]
답변너무나 감사합니다.다시해볼께요^^

**Comment by kjd95110** [comment]
네~잘 작동합니다. 감사하네요...
이 좋은 그리드가 무료라니 너무좋은데요...
혹시 메뉴얼이 있나요? 제가 GIT에 도움에 되야 하는데 염치없이 이용만해서 쫌 그렇기 합니다만^^;;;
이Tui.Grid를  저희회사에 적용할수 있다면 더없이 좋을거같습니다. 중소기업이라 Grid구매비용이 만만치
않아서...제가 회사에 도움이 되보고자...^^;;
저희회사는 닷넷 베이스 환경이구요
혹시 개발메뉴얼있으면 부탁드립니다~~

**Comment by kjd95110** [comment]
네~잘 작동합니다. 감사하네요...
이 좋은 그리드가 무료라니 너무좋은데요...
혹시 메뉴얼이 있나요? 제가 GIT에 도움에 되야 하는데 염치없이 이용만해서 쫌 그렇기 합니다만^^;;;
이Tui.Grid를  저희회사에 적용할수 있다면 더없이 좋을거같습니다. 중소기업이라 Grid구매비용이 만만치
않아서...제가 회사에 도움이 되보고자...^^;;
저희회사는 닷넷 베이스 환경이구요
혹시 개발메뉴얼있으면 부탁드립니다~~

**Comment by dongwoo-kim** [comment]
@kjd95110 
TUI Grid 는 개발 메뉴얼이 상세하게 제공되지는 않고 있습니다. 
최대한 자세하게 가이드를 하려고 노력하고 있지만, 아무래도 상용 제품이 아닌 오픈소스이다 보니 기능개발에 좀더 우선순위를 두고 작업할 수밖에 없는 점 양해해 주시기 바랍니다. 부족한 점에 대해서는 적극적으로 피드백을 주시면 보완해 나갈 수 있도록 하겠습니다.

**Comment by kjd95110** [comment]
개발메뉴얼이 없군요..ㅠㅠ 
궁금한게...grid.setRowList(dummyRowList);로 데이터를 제공받아서 TuiGrid에 뿌려주는데.....
궁금한건 변경된내용을 저장하거나 새로 데이터를 입력했을때 인서트작업을 하기위해 Grid내용을
읽어야 하는데...이건 어떻게...하나요? ^^;;;
무슨말이냐하면...저희회사에서는 현재 그리드(액티브X기반)의 내용을 읽어 히든콘트롤에 저장하여 
저장된 히든 콘트롤을 다른페이지에 넘겨서 DB작업을 처리합니다.
Tui Grid에서 변경된 내용이나 새로운 입력내용을 히든에 담든 아니면 다른변수에 담든 담아서 
DB작업을 하기위해서 어떻게 해야하는지 
다시말해  Tui.Grid의 변경된내용이나 입력된내용을 어떻게 읽어서 변수에 넣는지가 궁금합니다.
 터무니없는질문같지만 저에게 몹시 중요한 일이오니 가볍게 넘기지마시고 답변해주세용.
자바스크립트공부 다시시작하라는 말만 하지말아주세요....다시할꺼니깐요^^;;

**Comment by dongwoo-kim** [comment]
음.. 어떤걸 말씀하시는지 모르겠는데, 
현재 값을 가져오는 메소드는 `getRowList`, `getRow`, `getRowAt`, `getValue`, `getColumnValues` 등이 있구요,
처음 값에서 변경된 내용만 가져오고 싶다면 `getModifiedRowList`를 사용하실 수 있습니다.

메소드별 설명은 [API 페이지](http://nhnent.github.io/tui.grid/api/tui.Grid.html) 를 참고하시면 될 것 같습니다.

**Comment by kjd95110** [comment]
API이게 매뉴얼아잉교...^^
고맙습니다~~~~~~~~~
기회가된다면 식사대접해드리고 싶어요^^

**Comment by kjd95110** [comment]
동우님입장에서는 제가 한심할수도 있을거 같군요...ㅡ.ㅡ;;
API페이지를 보고도 이용하지못한다면... 문제가...참 심각한거지요? ㅎㅎ ㅠㅠ
제가 그렇네요...다때려치우고 농촌에가서 소나길러야 하나요?나이만 많아가꼬..ㅠㅠ아공...
제가 참 한심합니다만...다..감내하고여쭤봅니다.
getModifiedRowList 메소드 이용해서 어떻게 자바스크립 변수또는 배열로 넣는지 
메소드에서 리턴되는 Object를 어떻게 받아서 변수 또는 배열로 넣어야 될지 모르겠습니다.
바보같은질문이지만 이런종의 인간들도있구나 하고 넓은마음으로 한번만 답변달아주세요~~
기회된다면 보은하고 싶고 밥이라도 사드리겠습니다.^^

**Comment by kjd95110** [comment]
TUI Grid 소개란에 보니까 서버에 데이터저장하는 방법이 간단한게 되어있는거 같아요
Saving Changed Data
If you want to save changed data to the remote server, you can use the following APIs:
• createData : To send newly added data only
• updateData : To send updated data only
• deleteData : To send deleted data only
• modifyData : To send all added/updated/deleted data
To use these APIs, you have to register the URL of each request in advance.
grid.use('Net', {
    perPage: 100,
    api: {
        readData: '/api/readData',
        createData: '/api/createData',
        updateData: '/api/updateData',
        modifyData: '/api/modifyData',
        deleteData: '/api/deleteData'
    }
});

혹시 상단의 저장  API 에 관해 간단한예제없을까요?
내용들이 저에게 좀...뜬구름같은 내용들이라 이해하기 힘드네요...
돈이라도 달라고 하면 드릴수 있을정도로 절박합니다.
옛날 .NET베이스  ASP.NET 환경에서 유지보수만 하다보니 이상한 사람이 되어버렸네요 ㅠㅠ
이런환경을 이해할수 있는 추천책도 부탁드립니다. 억울해서라도 공부해야겠어요..

**Comment by shiren** [comment]
@kjd95110 여기서 이러시면 안됩니다..

**Comment by kjd95110** [comment]
죄송합니다..
삭제할께요

**Comment by shiren** [comment]
@kjd95110 일단 이렇게는 여기서 하면안됩니다.

**Comment by shiren** [comment]
이슈 클로즈해주시구요.

**Comment by kjd95110** [comment]
이슈클로즈는 뭐예요?

**Comment by kjd95110** [comment]
나...왜 아는게 없냐...ㅠㅠ
