### ISSUE TITLE
toast gird 2.10.0 버전을 사용중입니다

### ISSUE THREAD

**Issue by okmy03** [nhnent/tui.grid#174]
input 값을 넘길때 name 값을 맞추는 법을 모르겠어서 데이터를 넣을 때 바로 input 타입으로 넣었는데 text값이 드래그도 안돼고 전체 선택 함수를 입력해도 동작하지 않습니다. 

editOptions: {
                type: 'text',
                maxLength: 10,
                useViewMode: false
            }
을 사용하여 name 값을 지정해 주는 방식이나,

그리드 내에서 텍스트 값을 드래그 하려면 어떻게 해야하나요

**Comment by seonim-ryu** [comment]
@okmy03 
`editOptions`을 사용하여 input 요소를 생성할 경우, 다음 2가지 타입으로 셀에서 input을 보여줄 수 있습니다. ([ref.](https://nhnent.github.io/tui.grid/latest/tutorial-example04-input-types.html))

1. 디폴트
- 셀에 input 요소가 바로 보여지며, 셀이 선택되면 편집 모드로 변경됨
```js
editOptions: {
  // ...
  useViewMode: false
}
```

2. 뷰 모드
- 셀을 더블 클릭했을 때 input 요소가 보여지고 편집 모드로 변경됨
```js
editOptions: {
  // ...
  useViewMode: true
}
```

현재 1번 디폴트 모드로 설정된 상태이며, 이 경우에 현재 말씀하신 text 값 드래그는 셀이 편집 모드로 변경된 상태에서 사용할 수 있습니다.
그리고 현재 그리드에서 input 요소의 `name` 프로퍼티 값은 그리드 내부에서 설정된 값으로 세팅되기 때문에 외부에서 설정이 불가합니다.
