### ISSUE TITLE
그리드 컬럼 넓이 이슈사항 

### ISSUE THREAD

**Issue by jooyh** [nhnent/tui.grid#176]
## Version
 2.10.1

## Development Environment
window / eclipse / tomcat / chorme

안녕하세요

그리드 툴 감사히 잘 사용하고 있습니다.

다름이아니라 버그사항을 발견하여 이렇게 이슈제기를 하게 되었습니다.

현재 인덱스 포함 16개의 컬럼을 사용중입니다.

처음에는 정상적으로 잘 구동이 되나 컬럼 헤더부분의 넓이를 조정하고 나면 컬럼헤더 이하 데이터 의 열이 정확히 맞지 않게되는 이슈사항이 있습니다.

검토해주셔서 다음번 패치에 반영되었으면 좋겠습니다.

더 좋은 툴 제작에 도움이 되었으면 좋겠습니다. 감사합니다.

**Comment by seonim-ryu** [comment]
@jooyh 
현재 이슈 내용만으로는 현상 파악이 어렵습니다.
스크린샷이나 현재 설정하신 옵션 제공해주시면 감사하겠습니다.
