### ISSUE TITLE
selectbox 함수호출

### ISSUE THREAD

**Issue by ghost** [nhnent/tui.grid#18]
안녕하세요 :)

"changeBeforeCallback" : function (changeEvent){                	   
       // console.log("셀렉트박스2 값 변경 이벤트 : ", changeEvent);
      return   EventTest();                
}
그리드에서 셀렉트박스를 선택하고 다른 곳에 포커스를 클릭해야 함수를
호출이 되는것 같은데 바로 호출해 올수 없나요?

http://nhnent.github.io/tui.grid/api/tutorial-example2.html 예제와 같이
대분류에서 '선택하세요'를 선택하고 다른 곳에 클릭했을때만 중분류 컬럼의 셀렉트박스가
disabled 처리되는데 대분류에서 바로 선택했을때 처리는 안되나요?

**Comment by dongwoo-kim** [comment]
안녕하세요~

방법을 찾아봤는데.. 
내부적으로 `setValue` 를 호출하는 시점 자체가 "blur가 발생할 때"로 정해져 있어서,
현재로서는 셀렉트박스의 값이 변하는 타이밍에 함수를 호출할 수 있는 방법이 없는 것 같습니다.

viewMode 를 사용할 때와 UX를 맞추려고 의도한 건데.. 불편함 점이 있는 것 같네요.
이 부분은 내부 검토후에 개선할 수 있도록 하겠습니다.

**Comment by dongwoo-kim** [comment]
@ghost 
[1.8.0](https://github.com/nhnent/tui.grid/releases/tag/1.8.0) 에 반영되었습니다.
