### ISSUE TITLE
Binding to remote data 설명이 너무 부실합니다.

### ISSUE THREAD

**Issue by no1steel** [nhnent/tui.grid#188]
step by step 으로 좀 자세히 설명 해 주실 수 없을까요?

**Comment by seonim-ryu** [comment]
@no1steel 
[튜토리얼](https://github.com/nhnent/tui.grid/blob/production/docs/binding-to-remote-data.md)에 Net 사용과 관련해 모든 내용들을 설명하고 있습니다만,
혹시 어떤 부분이 부실한지 또는 보강해야 될 부분에 대해서 자세하게 설명해주시면 감사하겠습니다.

**Comment by no1steel** [comment]
아래의 소스로 현재 readData는 정상적으로 데이터를 들고 오고 있습니다.

튜트리얼 부분에 Net 설명을 가지고 아래의  createData를 사용해 봤는데 No data to create 가 뜹니다.

이런 질문이 이슈 close 된 부분에 두개나 더 있더군요.

오픈 소스 이긴 하나 이슈가 되는 부분은 처리 방식에 어떤 부분을 유념하라 라는 코멘트도 있었으면 좋겠습니다.

그리고 왜 createData를 No data to create 가 뜰까요 ㅠㅠ?

var grid, net;

$(document).ready(function(){

        grid = new tui.Grid({
            el: $('#grid'),
            bodyHeight: $(".sidebar-offcanvas").height(),
            minBodyHeight: 30,
            rowHeaders: ['rowNum'],
            pagination: false,
            columns: []
        });
                
        grid.use('Net', {
            el: $('#frmSw'),
            initialRequest: false,
            readDataMethod: 'POST',
            enableAjaxHistory: false,
            api: {
            	readData: '/api/readData',
                createData: '/api/createData',
                updateData: '/api/updateData',
                modifyData: '/api/modifyData',
                deleteData: '/api/deleteData'
            }
        });

        grid.on('beforeRequest', function(data) {
            // before sending a request
            //alert("beforeRequest " + data);
        }).on('response', function(data) {
            // when receiving response regardless of success/fail
            //console.log("data " + data.responseData.list)
            grid.setData(data.responseData.list);
        }).on('successResponse', function(data) {
            // when the result is true
            alert("successResponse " + data);
        }).on('errorResponse', function(data) {
            // when an error occurred
            alert("errorResponse " + data);
        });
        
});

    function doSearch(){
      var net = grid.getAddOn('Net');
      net.request('readData');
    }

    function doSave(){
        net = grid.getAddOn('Net');
        net.request('createData');
        grid.on('response', function(data) {
            console.log("data");
        });
    }

**Comment by no1steel** [comment]
2.0 버전의 튜트리얼에서 checkedOnly 옵션이 있는 걸 확인 했습니다.

    	var options = {
  		    checkedOnly: false
  		};
    
        net = grid.getAddOn('Net');
        net.request('createData', options);

를 하니 Are you sure you want to create 1 data? 가 나옵니다. 

감사합니다.

**Comment by seonim-ryu** [comment]
@no1steel 
`checkedOnly: true` 값이 디폴트로 설정되어 있어 사용 시 이슈가 있었던 것 같습니다.
말씀해주신 내용은 튜토리얼에 추가하도록 하겠습니다. 감사합니다. :)
