### ISSUE TITLE
키 입력 이벤트 사용

### ISSUE THREAD

**Issue by tackiyo** [nhnent/tui.grid#19]
안녕하세요.

셀입력시 숫자만 입력 받고 싶은데

그리드 셀에서 키입력 관련 이벤트를 사용할 수 있나요?

**Comment by dongwoo-kim** [comment]
안녕하세요.

컬럼 모델의 `editOption` 내부에서 `inputEvents` 옵션을 사용하실 수 있습니다.
예를 들어 `c1` 컬럼의 셀에서 `keydown` 이벤트를 사용하고 싶으면 다음과 같이 

```javascript
var grid = new tui.Grid({
  el: $('#grid'),
  columnModelList: [
    {
      columnName: 'c1',
      editOption: {
        inputEvents: {
          keydown: function(ev) {
          // ev 는 DOM Event 객체
          }
        }
      } 
    }
  ]
});
```
와 같이 사용하실 수 있습니다. 
`inputEvents` 에서 사용 가능한 이벤트는 `keydown`, `focus`, `blur` 세가지입니다.
