### ISSUE TITLE
virtualScrolling option 에 대해 가이드 수정이 필요합니다.

### ISSUE THREAD

**Issue by kywwoo** [nhnent/tui.grid#190]
가이드 문서 내에는 default 값이 true 로 되어 있는데요.
참조한 가이드 문서: http://nhnent.github.io/tui.grid/api/Grid.html

실제 소스 내에서는 default 값이 false 입니다.
사용 버전: 3.0.0

가이드 문서 수정이 필요해보입니다. 확인해주세용

**Comment by seonim-ryu** [comment]
@kywwoo 
제보 감사합니다. 다음 배포 시 수정하도록 하겠습니다.

**Comment by seonim-ryu** [comment]
@kywwoo 
문의주셨던 API 문서를 확인해보니 v2.9.1에 해당하는 문서이며 위 URL은 더 이상 제공하고 있지 않습니다 ^^;
정식 URL은 http://nhnent.github.io/tui.grid/latest/ 이며, 3.0.0 버전에는 해당 옵션이 수정되어 있어 이슈 클로징합니다.
