### ISSUE TITLE
rowHeaders 이용시 removeRow에 문의 드립니다.

### ISSUE THREAD

**Issue by kdp514** [nhnent/tui.grid#192]
grid옵션에 rowHeaders를 ['checkbox','rowNum']지정해주고
applyTheme를 이용하여 evenRow에 배경색을 넣은다음
removeRow하게 되면
css가 깨져서 나오게 됩니다.
강제로 class명을 변경하여 사용하고 있는데
혹시 다른방법이 있는지 확인 부탁드립니다.
![test](https://user-images.githubusercontent.com/30856253/44014959-7f76bb7a-9f09-11e8-875d-32f42367b2e4.png)

**Comment by seonim-ryu** [comment]
@kdp514 
버그로 확인되었으며 내부에서 클래스 값을 변경해야 되는 이슈가 있어 외부 css로는 처리가 불가해보입니다.
이슈 제보 감사합니다.
