### ISSUE TITLE
토스트그리드 net 를 이용한 그리드 데이터 출력

### ISSUE THREAD

**Issue by shknight76** [nhnent/tui.grid#193]
안녕하십니까?

토스트 그리드를 이용해서 내부의 데이터를 보여주는 웹을 만들고 싶습니다.

그런데 예제를 봐도 실력이 없어서 이해되지 않아 요청드립니다. Jsp mvc 로 json 리턴 받아 그리드에 뿌려주는 예제 하나만 부탁드립니다.

**Comment by seonim-ryu** [comment]
@shknight76 
TOAST UI 제품들은 프론트엔드 컴포넌트로, 서버 사이드 언어까지 대응하여 가이드 드리기 어려운 점 양해 부탁드리겠습니다.
[예제](http://nhnent.github.io/tui.grid/latest/tutorial-example01-basic)와 [튜토리얼](https://github.com/nhnent/tui.grid/tree/master/docs)을 제공하고 있으며, 해당 문서 참조하여 개발 중 궁금한 점 있으실 경우 다시 이슈 등록 부탁드리겠습니다.

**Comment by MaxmumDragon** [comment]
@seonim-ryu 
ResponseBody 어노테이션을 사용하여 List로 JSON 까지 데이터를 전송하여 .net를 통해서 그리드에 뿌려주려고 합니다. 헌데 로딩화면만 나오고 데이터가 확인 되지 않습니다...
애드온 net 사용시 페이징을 해주던데요.. 혹시 페이징이  필수적으로 들어가야하는 것인지요??
Controller  list 부분입니다.
@RequestMapping("listJ.do")
		@ResponseBody
		public List<BoardVO> listJ() throws Exception{
			List<BoardVO> listJ = service.listAll();
			//System.out.println(listJson);
			return listJ;
		}
스크립트 부분
$(document).ready(function(){
     var grid = new tui.Grid({
el :$("#grid"),
			scrollX : false,			
			scrollY : false,
			columns : 		 
			[{
				title : '번호',
				name : "bno"
			}, {
				title : '제목',
				name : 'title'
			}, {
				title : '내용',
				name : 'content'
			}, {
				title : '날짜',
				name : 'regdate'
			}, {
				title : '작성자',
				name : 'writer'
			}]
		});
		grid.use('Net',{
			api : {
				'readData' : '/listJ.do'
			}
		});
	});
