### ISSUE TITLE
webjars 메이븐 의존성 설정 시 오류

### ISSUE THREAD

**Issue by GroovySunday** [nhnent/tui.grid#194]
안녕하세요, 현재 스프링부트 프로젝트 프론트에 토스트 그리드를 사용하려 합니다.

Webjars를 통해 메이븐에 의존성을 설정하려고 하는데요.
https://www.webjars.org 에서 제공하는 토스트 그리드 2.3.0 의 설정을 

```
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>github-com-nhnent-tui-grid</artifactId>
    <version>2.3.0</version>
</dependency>
```

pom.xml 을 통해 추가했을 경우, 라이브러리가 추가되지 않습니다. 
현재는 우선 STS 를 통해서 메이븐 프로젝트 업데이트 기능을 사용중인데요.
혹시 이 부분과 관련되어 해결할 수 있는 방법이나, 관련 사항의 확인이 가능하신지 문의드리고자 합니다.

감사합니다.

크게 도움이 될 사항인지는 잘 모르겠지만,
현재 JDK 8 그리고 STS는 3.9.5, Spring Boot 2.0.4 버전을 사용하고 있습니다.

webjars를 통해서는
jquery 3.3.1, undersorejs 1.8.3, backbonejs 1.3.3, tui-code-snippet 1.4.0 
이 메이븐으로 추가되어 있습니다.

**Comment by seonim-ryu** [comment]
@GroovySunday 
안녕하세요. 답변이 많이 늦어졌습니다 ^^;
https://www.webjars.org에 등록된 내용은 저희쪽에서 등록한 것이 아니라 답변을 드리기 어렵습니다.
그리고 현재 v3.0 이후 버전까지 배포가 된 상황이라 호환성 유지를 위해서라도 최신 버전을 사용하시기를 권장합니다.
[node](https://nodejs.org/ko/)를 사용해 프론트엔드 개발이 가능할지 검토해보시는 것도 좋을 것 같습니다.
감사합니다 :)
