### ISSUE TITLE
컬럼 동적 생성 방법 문의드립니다.

### ISSUE THREAD

**Issue by JungMin89** [nhnent/tui.grid#197]
컬럼을 동적으로 생성 하고 싶습니다.
예를 들면 각 월별로 일 수가 다르니 월이 바뀔때마다 30, 31일 계속 바뀌게 컬럼을 생성 시키고 싶은데 컬럼을 동적으로 생성하는게 가능한가요?

**Comment by seonim-ryu** [comment]
@JungMin89 
[`setColumns`](http://nhnent.github.io/tui.grid/latest/Grid#setColumns) 메서드를 사용하면 동적으로 컬럼을 변경할 수 있습니다.
그리고 이후 이슈 등록 시에는 꼭 이슈 템플릿 양식에 맞추어 작성 부탁드립니다.
감사합니다.
