### ISSUE TITLE
auto numbering을 출력하는 열이 전체 행의 높이에 맞춰서 조정되지 않음

### ISSUE THREAD

**Issue by mamings** [nhnent/tui.grid#2]
autoNumbering: true고 아래와 같은 컬럼의 출력정보 때문에 행의 높이가 길어지는 경우,
auto numbering을 출력하는 열이 전체 행의 높이에 맞춰서 조정되지 않습니다.

그리드 버전 : 1.1.0

					{
						columnName : 'repImgUrl',
						title : '샘플',
						width : 60,
						align : 'center',
						formatter : function(value, rowData) {
							return "<img src='" + value + "?100x100' />";
						}
					},
![gridtest](https://cloud.githubusercontent.com/assets/10988007/11946855/6ce18108-a8a2-11e5-9713-d662fa687531.png)

**Comment by dongwoo-kim** [comment]
안녕하세요. 
그리드에서 행의 높이는 `rowHeight` 값으로 관리가 되는데, 현재 `rowHeight` 값이 셀의 내용에 따라 자동으로 변경되는 기능은 성능상의 이슈로 인해 지원하지 않고 있습니다. 번거롭겠지만, 그리드 생성 시에 옵션으로 `rowHeight` 값을 원하시는 행 높이 만큼 지정을 해 주시면 문제가 해결 될 것 같습니다.

감사합니다 :)
