### ISSUE TITLE
그리드에 데이터 입력시 엔터키치고 다음행으로 내려가서 

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#20]
한칼럼만 계속 입력하려고 할때말이죠...
Grid에 데이터 입력시 엔터키치고 다음행으로 내려가서 바로 입력가능하게 가능할까요?
제가 사용해보니 Grid에서 엔터키를 쳐야 입력이 가능하더라구요...한두개 입력시에는 문제가
없겠지만 데이터를 많이 입력할때는 불편할거 같습니다.

**Comment by kjd95110** [comment]
행추가 할때는  appendRow를  사용하나요? 아니면 addRowClassName 사용하나요?
사용예제 간단히 부탁드려도 되나요?

**Comment by dongwoo-kim** [comment]
@kjd95110 
현재 입력이 끝난 이후 포커스를 제어할 수 있는 API는 제공되지 않고 있습니다.

그리고 이슈 페이지는 다른 개발자들도 보는 페이지이기 때문에
추후에 검색이 용이하도록 제목을 잘 정리해서 올려주시고, 
기존 이슈와 관계없는 내용인 경우 댓글이 아니라 새로운 이슈로 등록해 주시기 바랍니다.

**Comment by kjd95110** [comment]
답변감사합니다.

**Comment by kjd95110** [comment]
위에 질문한내용은 엑셀처럼 빨리 입력하고자할때 Grid에서 제공하는가하는 문제인데
제공하지 않아서 아쉽습니다.
참고해주시고 반영되면 좋을거같습니다.
