### ISSUE TITLE
getRow나 특정 함수를 통해 행의 상태를 알수있는 방법이 없나요?

### ISSUE THREAD

**Issue by kkhkykkk** [nhnent/tui.grid#201]
getModifiedRows()를 사용하면 insert, delete, update 별로 행을 나누던데요.

특정 행의 상태를 알수 있는 방법은 없을까요?
왠지 있을거 같은데 제가 잘 못 찾는건지 싶어서요.

insert된 행일경우 키값은 수정 가능
기존 행의 경우 키값은 수정 불가

위 처럼 구현하려 합니다.

**Comment by seonim-ryu** [comment]
@kkhkykkk 
행 데이터 자체에 추가, 삭제, 수정된 행에 대한 상태를 기록하고 있지는 않습니다.
말씀하신 기능의 경우, `getModifiedRows`에서 반환한 값 중 `createdRows` 키 값의 행 데이터에서 `rowKey` 값을 가져와 사용하면 될 것 같습니다.
```js
{
    createdRows: [ ... ] // 행 데이터
}
```
그리고 번거로우시겠지만 추후 이슈 등록 시 꼭 이슈 템플릿에 맞추어 작성 부탁드립니다. :)

**Comment by kkhkykkk** [comment]
답변 감사합니다.


2018년 10월 5일 (금) 오전 10:30, 류선임 <notifications@github.com>님이 작성:
