### ISSUE TITLE
validation 옵션을 주고, editOptions 옵션을 주었을 때..

### ISSUE THREAD

**Issue by kungfumong** [nhnent/tui.grid#203]
```js
columns: [
  {
    validation: {
      dataType: 'number',
      required: true
    },
    align: 'center',
    title: '가격',
    name: 'price',
    editOptions: {
      type: 'text',
      useViewMode: true
    }
  }
]
```

위와 같이
validation 옵션을 number로 주고
editOptions을 text로 주었을 때,
수정 값을 숫자로 입력하면 ex) 3500
validation에서 String으로 인식하네요

editOptions의 type은  'text', 'password', 'select', 'radio', 'checkbox' 밖에 없고..
어떻게 해결할 수 있나요?

**Comment by dongwoo-kim** [comment]
controller 로직 내부의 버그인 것 같습니다. 다음 버전 (3.5.0) 에 패치가 포함될 예정입니다.
