### ISSUE TITLE
download excelAll 사용이 잘 되지 않습니다.

### ISSUE THREAD

**Issue by ppoyang** [nhnent/tui.grid#204]
안녕하세요.
tui grid 사용 중 넘겨진 데이터를 엑셀로 저장하는 기능을 사용하고 싶은데 잘 되지 않아 글을 남깁니다.
버전은 tui.grid-3.1.0 다운로드 받아 사용했습니다.
examples에서 example11-customizing-rowheaders.html 파일을 그대로 사용했고,
data는 basic-dummy를 그대로 사용했습니다.
script에 

 $(function(){
    $('.bb').on('click',function(){  ///버튼 클릭시
      grid.use('Net', {
          api: {
               readData: '/api/readData',
               downloadExcel: '/api/download/excel',
               downloadExcelAll: '/api/download/excelAll'
          }
       });
      var net = grid.getAddOn('Net');
       net.download('excelAll');
    })
 })

이부분만 추가했는데요.
버튼을 클릭하면

An erroer occurred while requesting data.
Please try again.

이라는 알림창이 뜨면서 
url이 file:///파일위치경로/tui.grid-3.1.0/examples/api/download/excelAll? 이렇게 바뀝니다.

어떤 것을 수정해야하는지 도움 부탁드립니다.

**Comment by dongwoo-kim** [comment]
죄송합니다. 문의 대응이 너무 늦었네요. 너무 오래된 이슈라서 일단 Close 합니다.
아직 대응이 필요한 문제라면 ReOpen 하신 다음 댓글 부탁드릴게요.
