### ISSUE TITLE
binding-to-remote-data.md 관련 문의드립니다. 

### ISSUE THREAD

**Issue by onlyroad** [nhnent/tui.grid#205]
## Version

지금현재 버전
## Development Environment

스프링/톰캣 
## Current Behavior

1. readData 시 MULTIPART FILE  을 업로드 해야하는데  해당내용에 대한 설명이 없습니다. 
2. 위 사유로 readData사용없이 따로 서블릿 호출하여 setData()를 사용하는데 ..
    수정을 위해 net을 설정할경우 readData Process가 실행되어 화면에 loading ... 메시지가 나타 납니다.
    << readData >> 자동실행안되게끔 하는 환경 
3. modifyData  실행시 grid에 있는 전체데이터를 서버로 보내고 싶은데 ...  setData()로 세팅된 데이터중 
   변경된 건들만 보내집니다. 전체를 보내고 싶은데 방법이 없는지요
4. 소스는 아래건 참조했습니다. 
```js
// Write example code
```

## Expected Behavior

var grid, net;

$(document).ready(function(){

    grid = new tui.Grid({
        el: $('#grid'),
        bodyHeight: $(".sidebar-offcanvas").height(),
        minBodyHeight: 30,
        rowHeaders: ['rowNum'],
        pagination: false,
        columns: []
    });
            
    grid.use('Net', {
        el: $('#frmSw'),
        initialRequest: false,
        readDataMethod: 'POST',
        enableAjaxHistory: false,
        api: {
        	readData: '/api/readData',
            createData: '/api/createData',
            updateData: '/api/updateData',
            modifyData: '/api/modifyData',
            deleteData: '/api/deleteData'
        }
    });

    grid.on('beforeRequest', function(data) {
        // before sending a request
        //alert("beforeRequest " + data);
    }).on('response', function(data) {
        // when receiving response regardless of success/fail
        //console.log("data " + data.responseData.list)
        grid.setData(data.responseData.list);
    }).on('successResponse', function(data) {
        // when the result is true
        alert("successResponse " + data);
    }).on('errorResponse', function(data) {
        // when an error occurred
        alert("errorResponse " + data);
    });

});

function doSearch(){
  var net = grid.getAddOn('Net');
  net.request('readData');
}

function doSave(){
    net = grid.getAddOn('Net');
    net.request('createData');
    grid.on('response', function(data) {
        console.log("data");
    });
}

**Comment by dongwoo-kim** [comment]
죄송합니다. 문의 대응이 너무 늦었네요. 너무 오래된 이슈라서 일단 Close 합니다. 
아직 대응이 필요한 문제라면 다시 ReOpen 하신 다음에 댓글 부탁드릴게요.
