### ISSUE TITLE
Grid 행추가를 테스트해보려하는데 

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#21]
행추가 메소드 2개가 눈에 보이네요...
1. grid.prependRow(row, focus);
row에 어떤값을 줘야할지...0 을주고 실행해보면 
맨위에 잠깐 행추가됐다가 사라집니다.ㅠㅠ
2.grid.appendRow(row,optionsopt);  
row에 어떤값을 줘야할지...설명에는 The data for the new row (새행의 자료)라 되있고,
optionsopt에는 focus를 주면 되는것인지..맨밑에 행추가되는거 같긴한데 사용법이 어렵네요
 설명부탁드려요^^

**Comment by dongwoo-kim** [comment]
빈 행을 추가하려고 할 때에는 `prependRow`, `appendRow` 모두 인자 없이 호출 가능합니다.
```javascript
grid.prependRow();
grid.appendRow();
```
잠깐 추가되었다가 사라지는 현상은 다른 원인이 있는 것 같은데.. 현재 상황만으로는 파악이 어렵네요. 
`row` 에는 원하는 데이터를 일반객체 형태로 넘기면 됩니다. 

```javascript
grid.appendRow({
  name: 'Kim',
  age: 30
};
```

`options` 에는 특정 인덱스에 추가하고 싶으면 `at`, 추가된 행에 포커스를 주고싶은 경우 `focus` 를 사용하시면 됩니다.
```javascript
grid.appendRow({}, {
  at: 2,
  focus: true
});
```

**Comment by kjd95110** [comment]
답변감사합니다. 빨리실력키워 같이 버전업하길 기대해봅니다^^
