### ISSUE TITLE
net readData 통신 오류 문의

### ISSUE THREAD

**Issue by leedongok** [nhnent/tui.grid#217]
Version
version: 3.0
Development Environment
window7 / chrome / eclipse/spring
jquery 3.2.1
tomcat 7

Current Behavior

`var net; 
    var energyGrid = new tui.Grid({
	    el: $('#energyGrid'), 
	    bodyHeight: 550,
	    bodyHeight: $(".sidebar-offcanvas").height(),
	    rowHeaders: ['rowNum'],
	    columnOptions: {
	        width: 100
	    },
	    columns: [
	        {
	            title: '층별명',
	            name: 'floor'
	        },
	        {
	            title: '냉난방/비냉난방',
	            name: 'machine'
	        },
	        {
	            title: '장비명',
	            name: 'equip_nm'
	       }
	    ]
	});

    energyGrid.use('Net', {
    	el: $('#data_form'),
        initialRequest: true, //초기화 후 readData요청여부
        readDataMethod: 'GET', 
        perPage: 500,
        enableAjaxHistory: false,
        api: {
            'readData': '/selectInfo'
        }
     });
    
    // Bind event handlers
    energyGrid.on('beforeRequest', function(data) {
        // For all requests
    }).on('response', function(data) {
        // For all response (regardless of success or failure)
    }).on('successResponse', function(data) {
        // Only if response.result is true
    }).on('failResponse', function(data) {
        // Only if response.result is false
    }).on('errorResponse', function(data) {
        // For error response
    });
   
	 net = energyGrid.getAddOn('Net');
});`

안녕하세요. net으로 통신하여 목록을 가져오려하는데.

잘안되서 문의드려요 

`@RequestMapping(value = "/selectInfo", method = RequestMethod.GET)
	public String selectInfo(@RequestParam Map<String, String> paramMap, ModelMap model) throws Exception {
		model.addAttribute("readData", dashBoardService.selectEnergyInfo(paramMap));
	
				return VIEW_PATH + "dashboard2";
	}`

**Comment by dongwoo-kim** [comment]
죄송합니다. 문의 대응이 너무 늦었네요. 너무 오래된 이슈라서 일단 Close 합니다.
아직 대응이 필요한 문제라면 다시 ReOpen 하신 다음에 댓글 부탁드릴게요.
