### ISSUE TITLE
columnFixIndex - 컬럼고정

### ISSUE THREAD

**Issue by streetlab-michael** [nhnent/tui.grid#22]
columnFixIndex로 고정할 인덱스를 지정하면
가로스크롤 시 스크롤이 안되는 것 아닌가요?
별도 frozen 기능의 함수가 있나요?
setColumnFixCount로 지정해도 동일하게 모두 스크롤되는 것 같습니다. 

추가로 멀티 컬럼 고정이나 좌,우 컬럼 고정이 가능할 수는 없나요?

**Comment by dongwoo-kim** [comment]
안녕하세요.
현재 컬럼 고정 기능은 좌측으로만 가능합니다.
`columnFixIndex` 는 현재 deprecated 되었고, 대신 `columnFixCount` 옵션을 사용하시면 됩니다.
`setColumnFixCount()` 를 사용하시면 지정한 숫자의 컬럼만큼 좌측으로 고정되게 됩니다. 
(현재 1.8.0 기준으로 테스트해본 결과 잘 동작하는데.. 안되는 원인을 모르겠네요.)
