### ISSUE TITLE
헤더 사이즈 조절 시 여백 문의

### ISSUE THREAD

**Issue by PlantGrace** [nhnent/tui.grid#224]
아래 그림과 같이 여백이 남는데요

테이블 영역이 같이 줄어드는 반응형 테이블은 제공되지 않나요?

![default](https://user-images.githubusercontent.com/42427717/48814401-ed232b00-ed7d-11e8-92b9-4a769a29506e.PNG)

**Comment by dongwoo-kim** [comment]
현재 전체 테이블의 넓이는 고정값이거나 부모 엘리먼트의 넓이를 따르도록 되어 있습니다.
전체 테이블의 넓이를 가변으로 설정할 수 있는 옵션을 주는 것도 좋을 것 같네요.

다음 버전에 추가될 수 있도록 고려해 보겠습니다. 의견 감사합니다 :)
