### ISSUE TITLE
tui grid에서 한번에 표현할수 있는 Row수는 몇개인가요?

### ISSUE THREAD

**Issue by jeunhaksun** [nhnent/tui.grid#228]
tui grid를 사용할려고 하는데 
appendRow를 이용해서 row를 추가해보니
일정갯수가 넘어가면 추가되지 않고 스크립트 대기가 뜨는데
그리드에서 표현되어지는 row수는 어떻게 되나요
아님 다음 문제를 해결 방법은 무엇인가요

아래와 같이 그리드에 appendRow 실행시 에러
for(var iLoop = 0; iLoop < 500; iLoop++) {
		grid.appendRow({
			unitCode: '',
			delGubun: '',
        });
}

**Comment by dongwoo-kim** [comment]
그리드에서 표현할 수 있는 Row 수에 제한은 없습니다. 하지만 `appendRow` 는 호출할 때마다 렌더링이 발생하기 때문에 한 프레임에서 수백번 호출하면 사실상 처리가 불가능합니다.  대신 다음과 같이 `appendRow()` 호출 시에 배열을 넘길 수 있습니다.
```js
var newRows = [];
for (var iLoop = 0; iLoop < 500; iLoop++) {
  newRows.push({
    unitCode: '',
    delGubun: '',
  });
}
grid.appendRow(newRows);
```
