### ISSUE TITLE
cell 선택 시 파란 색 박스 범위 변경 방법 및 colSpan 기능 문의

### ISSUE THREAD

**Issue by cjy6179** [nhnent/tui.grid#229]
## Version

tui.grid-3.3.0

## Development Environment

browser : chrome, internet Explorer

## Current Behavior

1. cell 선택시 파란색 박스 관련 문의
![image](https://user-images.githubusercontent.com/45343886/48989805-3a810d00-f16f-11e8-8c5b-f75fa2b75772.png)

cell 클릭 시 선택한 cell에 파란색 박스가 상단이미지처럼 표시가 되는데

cell 클릭 시 선택시 아래 처럼도 가능한 한가요?

![image](https://user-images.githubusercontent.com/45343886/48989812-42d94800-f16f-11e8-9ac4-1a3071f08dcb.png)

불가능하다면 표시 되지않게 가능한가요??

2. colspan 기능 구현 방법 문의
colspan 기능 구현 방안 문의 드립니다.
```js
// Write example code
```

**Comment by seonim-ryu** [comment]
@cjy6179 
1. 파란색 박스는 셀 단위의 '포커스' 상태를 나타내는 것으로, 해당 이미지처럼 포커스는 불가합니다.
포커스 보더 색상 변경은 다음과 같이 테마 API를 사용하여 처리할 수 있습니다.
```js
const extOptions = {
  cell: {
    focused: {
      border: 'red'
    }
  }
};

Grid.applyTheme('newTheme', extOptions)
```
2. 현재 그리드에서는 컬럼 병합(`colspan`) 기능은 제공하고 있지 않습니다.
