### ISSUE TITLE
TOAST UI GRID를  조금 사용해보니 

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#23]
TOAST UI GRID를  사용해보니 좋은점이 많이 보입니다^^
감사드리구요...
한가지 요청드려봅니다.
엑셀에서 입력해보시면 입력후 엔터키치면 다음칸(밑)으로 자동으로 내려가서
바로입력이가능한데 이기능이 매우 편리하더라구요..
혹시 TOAST UI GRID에서  구현가능할까해서 이슈남겨봅니다.
건강하세요~~

**Comment by seonim-ryu** [comment]
문의하신 기능은 검토 후 적용 가능할 경우 다시 코멘트 드리겠습니다 :)
