### ISSUE TITLE
grid addon request create/update/modify 데이터 없음으로 나오는 현상.

### ISSUE THREAD

**Issue by jinho1410** [nhnent/tui.grid#231]
## Version
3.3

## Development Environment
윈도우10 크롬 최신버전

## Current Behavior
행추가와 행수정에 대해서 modifyData는 수정된 결과가 없다고 나옴.
허나 grid.getModifiedRows() 결과를 출력해조면 createdRows와 updatedRows가 1건씩 있음.
```js
        		var net = grid.getAddOn('Net');
        		net.request('modifyData');
```

![image](https://user-images.githubusercontent.com/26426936/49479509-9e3dc100-f866-11e8-8cfc-e20a3762a750.png)

## Expected Behavior
 혹여  validation 검사로 인해서 net.request에서는 빠졌을 가능성 있으나.
validaton 검사 실행방법을 어떻게 하는지 몰라서 확인해보지 못함.
해당 오류 발견 및 수정 되길 바라며
추가로 사용자가 별도로 validaton 검사를 실행해서 경고 alert 가이드 띄울 수 있는 방법 가이드 부탁드립니다.

굿럭

**Comment by seonim-ryu** [comment]
@jinho1410 
`checkedOnly: true` 옵션이 기본 값으로 설정되어 있어서 해당 이슈가 발생한 것으로 보입니다.
아래와 같이 설정해주시면 정상동작합니다.
해당 내용은 버그건으로 처리할 예정입니다. 감사합니다.

```js
function syncServer() {
  const net = grid.getAddOn('Net');

  net.request('updateData', {
    checkedOnly: false
  });
}
```

**Comment by jinho1410** [comment]
감사합니다.
혹시 validation 체크로직 실행방법은 문의글 같아서 오류 등록겸 적었는데..
없는건가요?.. 따로 이슈로 등록하도록 하겠습니다.
