### ISSUE TITLE
그리드 validation 체크 실행 방법.

### ISSUE THREAD

**Issue by jinho1410** [nhnent/tui.grid#233]
## Version
3.3

## Development Environment
윈도우10 크롬 최신버전

## Current Behavior
아래와 같이 validation을 설정하였습니다. 
새행을 추가하고 값을 비우고 netAddOn request로 저장시 아무런 경고가 뜨지 않습니다.

```js
var columns = [{
  title : 'ORDER',
  name : 'APPROVAL_ORDER',
  width: 40,
  editOptions: {
    type: 'text',
    useViewMode: true
  },
  validation: {
    dataType: 'number',
    required: true
  }
}]
```

## Expected Behavior
따로 사용자가 validation 체크해서 경고를 띄울수있는 가이드가 API에는 없습니다.
확인 부탁드립니다.

**Comment by dongwoo-kim** [comment]
[validate](http://nhnent.github.io/tui.grid/latest/Grid#validate) 메소드를 사용하면 원하는 시점에 validation 체크를 실행할 수 있고, 결과값에서 에러가 난 항목을 모두 확인할 수 있습니다. 다만 현재 validation 결과가 화면에 바로 반영되지 않는 문제(#255)가 있는데, 이 문제는 3.5.0 에서 수정되어 배포될 예정입니다.
