### ISSUE TITLE
net readData 검색중 조회 데이터는 10건인데 1개의 로우만 화면에 표시되는 현상

### ISSUE THREAD

**Issue by jinho1410** [nhnent/tui.grid#235]
## Version
3.3

## Development Environment
윈도우10 크롬 최신버전

## Current Behavior
net.readData 를 이용하여 그리드 데이터 조회시
조회 조건을 변경하여 데이터 없음이 그리드에 표시된 후에
다시 10건이 있는 데이터 조회시 화면에 1행만 데이터가 표시되는 문제가 있습니다.

아래는 검색 로직 일부입니다.
```js
function search(){
	        var formData = net._getFormData(); //form
	        formData.page = 1;
	        formData.perPage = net.perPage;    //페이지당 항목 수
	        net.readData(1, formData, true);	
}
```

![image](https://user-images.githubusercontent.com/26426936/49842851-7ae3ba80-fe00-11e8-9829-c72ca741b0bb.png)
그림 1 처음 조회 화면.. (화면 표시내용은 삭제함)
그림 2 데이터가 존재하지 않습니다 조회 화면
그림 3 처음 조회 화면 재조회 (1행만 표시됨)

## Expected Behavior
10개의 데이터가 그리드에 전부 표시되어야 합니다.

**Comment by dongwoo-kim** [comment]
답변이 늦어 죄송합니다. #269 와 같은 이슈인 것 같습니다. 현재 수정중이며, 완료되면 댓글로 알려드리도록 하겠습니다.
