### ISSUE TITLE
그리드2개를 나란히 (왼쪽그리드1개  오른쪽그리드1개)배치하려하는데...

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#24]
요즘 뜸하시네요...바쁜신거같네요...ㅎ
시간되시면 답변좀 부탁드립니다.
그리드2개를 나란히 (왼쪽그리드1개  오른쪽그리드1개) 놓을려고 하는데,  프로그램구성상 필요해서요
2번째 그리드(오른쪽그리드가)
자꾸 내려와서 화면구성에 애를 먹고 있습니다.
방법이 있을까요??

**Comment by seonim-ryu** [comment]
안녕하세요.
현재 문의주신 내용은 그리드를 사용하고 있는 서비스 페이지의 레이아웃 구성에 대한 이슈로 보입니다.
그리드에서 제공하는 기능과는 무관해 보이며 서비스 페이지 마크업을 수정하셔야 될 것 같습니다.
확인 부탁드립니다.
