### ISSUE TITLE
summary 관련 질문 있습니다.

### ISSUE THREAD

**Issue by kkhkykkk** [nhnent/tui.grid#240]
excel 출력 기능을 만들었는데요,
summary bar 는 어떻게 데이터를 가져갈(얻어낼) 방법이 없을까요?

어떤 컬럼에서 어떤 값을 갖고 있다 는 정보 정도만 있으면 좋을거 같아요.

**Comment by dongwoo-kim** [comment]
3.5.0 버전에 추가될 예정인 `getSummaryValues` 메소드를 사용하면 될 것 같습니다. (b9de2a75)
