### ISSUE TITLE
mousedown 이벤트 유지 현상

### ISSUE THREAD

**Issue by baeklae** [nhnent/tui.grid#253]
## Version
version: 3.1.0

## Development Environment

Crome, Win10

## Current Behavior
editingEvent: 'click', 사용중

```js
title : '중간고사',
name : 'midtermScore',
align : "right",
editOptions : {
    type: 'text',
    maxLength: 3,
    useViewMode: true    	
}
, formatter: function(value) {
    return value == '' ? value.toString() : value.toString() + '점';
}     
, onAfterChange: function(ev){
    if(Number(ev.value)){
        ev.value = Number(ev.value);
        return ev;
    } else {
        alert("숫자만 가능합니다.");
        ev.stop();
        grid.focusIn(ev.rowKey, ev.columnName, true);		            		
    }	            	
}  
```

## Expected Behavior
최초 value 변경시 정상적으로 체크 후 포커스를 강제로 가져오는데는 성공하였으나,
onAfterChange 되면서 함께 발생하는 mousedown 이벤트 때문에 포커스 이동 후 마우스가 눌린 상태가 유지됩니다.

강제로 발생하는 mousedown 이벤트 전부를 stop 시키는 방안을 사용해 보았으나 다른 문제가 발생할 수 있어 해당 방안은 사용하지 않기로 결정했습니다.

함께 발생하는 mousedown 처리할 수 있는 방안이 있는지 확인 부탁드립니다.

![tui_mousedown](https://user-images.githubusercontent.com/42962165/51647827-a3470300-1fc1-11e9-8fcf-7494523c9626.png)

마우스 눌린상태의 이미지 첨부합니다.

**Comment by dongwoo-kim** [comment]
아마도 편집 모드를 종료하기 위해 다른 셀을 클릭했을 때 발생하는 것 같습니다. 이 경우 `mousedown` -> `blur` -> `change` 순서로 이벤트가 발생하는데, 마우스를 떼기 전에 `alert` 창이 뜨게 되면 `mouseup` 을 이벤트를 잡을 수가 없어 드래그 상태가 유지되게 됩니다. 

외부에서 막을 수 있는 방법은 없을 것 같고, 그리드 내부에서 `dragmove` 이벤트를 발생시킬 때 마우스 버튼이 눌렸는지를 체크해서 드래그를 방지하는 식으로 처리할 수 있을 것 같습니다.
