### ISSUE TITLE
특정 Row의 특정 column 배경색만 변경이 가능한가여?

### ISSUE THREAD

**Issue by hiphopddori** [nhnent/tui.grid#259]
예를들어 3번쨰 Row 2번째 컬럼만 배경색을 red로 변겨하고싶은데
formatter로만은 애매한부분이 있드라구욤

예제중에서 수정하여 아래처럼 formatter로는 컬럼 즉 td전체 배경이 제어가 안되고 해당 텍스트 부분만 제어가 되드라구욤 요소를 혹인해보니 formatter 상위 태그의 tui-grid-cell-content 클래스에서 padding처리가 되있어서 그렇드라구요
혹시 다른방법으로 특정 행 컬럼의 배경색이 td 전체 적용되게 제어가 가능한가여?

```js
columns: [
  {
    sortable: true,
    title: 'Name',
    name: 'name'
  },
  {
    title: 'Artist',
    name: 'artist',
    formatter: function(value, rowData) {
      let backgroudColor = "";

      if (rowData.score == "5"){
        backgroudColor = "red";
      } else {
        backgroudColor = "green";
      }
      return '<div style="width:100%;height:100%;background-color:'+backgroudColor+'">'+rowData.artist+'</div>';
    }
  }
]
```

**Comment by dongwoo-kim** [comment]
직접 스타일을 변경할 수 있는 방법은 없습니다만, 클래스명을 지정할 수는 있습니다. 아래의 두 메소드를 사용하면 동적으로 특정 셀의 클래스명을 추가/제거할 수 있습니다.

- http://nhnent.github.io/tui.grid/latest/Grid#addCellClassName
- http://nhnent.github.io/tui.grid/latest/Grid#removeCellClassName

다만, CSS 우선순위를 높이기 위해 다음과 같이 `.tui-grid-cell` 을 CSS 선택자에 포함시켜서 사용해야 적용됩니다. 

```css
.tui-grid-cell.cell-red {background-color: red}
.tui-grid-cell.cell-green {background-color: green}
```

**Comment by hiphopddori** [comment]
아 답변 감사합니다.
적용해보겟습니다

**Comment by hiphopddori** [comment]
vue.js에서 사용중인데 
https://github.com/nhnent/toast-ui.vue-grid 대로 하고있는데 아래처럼 테스트 코드를 만들어해보고있는데
<v-btn color="info"  v-on:click="setCellColorChange">cell color change</v-btn>
<grid ref="tuiGrid" :rowData="data" :columnData="columns" />

setCellColorChange(){
            //this.$refs.tuiGrid.getRootElement();
            //const info = this.$refs.tuiGrid.invoke('getFocusedCell');
            this.$refs.tuiGrid.invoke('addCellClassName', 1,'artist','.tui-grid-cell.cell-red');
            
            //this.$refs.tuiGrid.addCellClassName(1,'artist','.tui-grid-cell.cell-red');
        }
<style>
    .tui-grid-cell.cell-red {background-color: red}
</style>


vue에서는 invoke를 통해서 제어가 되게 되있드라구요 저렇게 해도 셀 배경색이 변경이 안되는데
vue.js에서는 어떤식으로 addCellCalssName을 호출할수 있는건가여?

**Comment by hiphopddori** [comment]
vue.js 를 통해서 제어하고있는데욤
https://github.com/nhnent/toast-ui.vue-grid 를 참조해서 처리하고있고욤

아래처림 테스트 코드를 작성하고

<v-card>
            <v-btn color="info"  @click='gridControl("cell_color_change")'>cell color change</v-btn>
            <v-btn color="info"  @click='gridControl("get_value")'>Get Value</v-btn>
        </v-card>
        <v-card>
            <grid ref="tuiGrid" :rowData="data" :columnData="columns" />
        </v-card>

methods:{
        gridControl(flag){
            //this.$refs.tuiGrid.getRootElement();
            //const info = this.$refs.tuiGrid.invoke('getFocusedCell');
            
            if (flag == "get_value" ){
                let row = this.$refs.tuiGrid.invoke('getValue','1','artist',true);
                alert(row);
            }else if (flag == "cell_color_change"){
                this.$refs.tuiGrid.invoke('addCellClassName', '1','artist','cell-red');
            }
        }
    }

<style>
    .tui-grid-cell.cell-red {background-color: red}
</style>

하면 vue는 invoke를통해서 메소드를 제어하는데욤
다른부분은 잘되드라구여 getValue , getRows등 다 잘되는데 원래 제가 하려는
 배경색 벼경을 하려고 알려주신대로 addCellClassName 을 invoke를 통해 호출하면 적용이 안되드라구요
수동으로 크롬 요소검사에서 cell-red를 추가해주면 잘반영이 되구요
혹시 다르게 더 처리해야할게 있는건가여?

**Comment by dongwoo-kim** [comment]
#262 에서 해결된 이슈로 클로즈합니다.
