### ISSUE TITLE
궁금합니다.

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#26]
1.궁금 
Grid의 cell 클릭했을때 cellclick 이벤트나 click이벤트를 어떻게 사용하는지 모르겠어요
api보니 잘이해가 안되서 여쭤봅니다.
Occurs when a mouse button is clicked on the Grid.
The properties of the event object is the same as the native MouseEvent
이렇게만 되있어서요...

onclick{
//click했을때 코드
}
oncellclick{
//cellclick
}
간단한 예제부탁드려봅니다.

2.궁금
  No(순서) 칼럼의  특정 행 클릭했을때  행의 전부가 선택되는데 
다른 Cell을 선택했을때도  행의 전부가 선택되게 하려면 어떻게 하면될까요?

**Comment by seonim-ryu** [comment]
안녕하세요.

첫 번째 문의 사항은 커스텀 이벤트 사용법을 문의하신 것 같습니다.
그리드 커스텀 이벤트 사용법은 [튜토리얼](https://github.com/nhnent/tui.grid/wiki/Custom-Event)로 제공되며 해당 문서 확인 부탁드립니다.

두 번째 문의 사항의 경우, 그리드에서 스펙 상 로우 헤더 영역을 클릭했을 때만 전체 행 선택이 가능하며 추가로 제공되는 API는 없습니다.

**Comment by kjd95110** [comment]
답변감사드립니다^^

**Comment by rarelhw** [comment]
그리드에서 로우 헤더를 클릭했을 때 클릭된 행 선택을 사용하고 싶지 않을 때는 어떻게 하면 되나요?
로우헤더 클릭 시 행 선택을 disable하는 옵션이 있을까요?

**Comment by seonim-ryu** [comment]
@rarelhw 
그리드 이벤트를 사용하면 처리가 가능합니다.
그리드 영역을 클릭했을 때 마우스 이벤트(`mousedown`)가 발생하며, 이 때 인자값으로 넘어온 객체의 `target`을 판별해 이벤트를 중단 여부를 결정할 있습니다.
아래 내용 확인 부탁드립니다.

```js
// fired mouse event
grid.on('mousedown', function(ev) {
  var target = ev.nativeEvent.target;

  if (/* determine condition of target element */) {
      return ev.stop();
  }
});
```

**Comment by rarelhw** [comment]
오오오오오오옷!!!!! 완전 따봉입니다! 감사합니다! (b^ㅅ^)b 더블따봉 드립니다!
