### ISSUE TITLE
vue version tui grid 사용중인데  addClassName이 적용이 안되고 있습니다.

### ISSUE THREAD

**Issue by hiphopddori** [nhnent/tui.grid#262]
아래 질문을 올렸었는데 배경색 변경을 하려하는데 말씀해주신 addClassName로 변경하려는데 적용되지 않습니다.
읽어보니 이전에 해당 버그가있어 수정된거 같은데욤
저는 근데 지금 올려주신 Vue.js 버전을 사용하여 테스트 진행하고 있습니다.
아래에서 해당 그리드를 다운받아서 사용중입니다.
https://github.com/nhnent/toast-ui.vue-grid

## Version
1.0.3
## Test Environment
크롬 , 맥 모하비

## Current Behavior

```html
<div>
  <v-btn color="info"  @click='gridControl("cell_color_change")'>cell color change</v-btn>
  <v-btn color="info"  @click='gridControl("get_value")'>Get Value</v-btn>
  <div>
    <grid ref="tuiGrid" :rowData="data" :columnData="columns" />
  </div>
</div> 
```

```js
gridControl(flag) {
  if (flag == "get_value" ) {
    let row = this.$refs.tuiGrid.invoke('getValue','1','artist',true);
    alert(row);
  } else if (flag == "cell_color_change") {
    this.$refs.tuiGrid.invoke('addCellClassName', '1', 'artist', 'cell-red');
  }   
}
```

```css
<style>
.tui-grid-cell.cell-red {background-color: red}
</style>
```
위 테스트 코드로 테스트하고있는데 실제 다른 메소드들은 잘 작동하는데 에를들어
getValue나 getRows등 원하는값들이 잘 출력되는데
배경색을 바꾸기 위해 addClassName을 호출하였을경우 반영이 안되고있습니다.
크롬 요소검사에서 수동으로 cell-red를 추가하였을시 배경색이 잘 변경되는것을 확인하였습니다.
해당 메소드가 정상 작동 하지 않는거 같습니다.

## Expected Behavior
addClassName호출시 바로 원하는 클래스가 해당 셀에 추가되었으면 합니다.

**Comment by dongwoo-kim** [comment]
제가 이슈 링크를 달아놓는 걸 깜빡한 것 같네요. 해당 이슈는 #255 로 따로 등록했고, [3.5.0](https://github.com/nhnent/tui.grid/releases/tag/v3.5.0) 버전에 반영되었습니다. 

현재 vue-wrapper 에는 반영이 안된 것 같은데.. 차주 중에 vue-wrapper도 업데이트할 예정입니다.

**Comment by hiphopddori** [comment]
아옙 감사합니다,

**Comment by dongwoo-kim** [comment]
[vue-wrapper 1.0.4](https://github.com/nhnent/toast-ui.vue-grid/releases/tag/v1.0.4)에 반영되었습니다.
