### ISSUE TITLE
virtualScrolling 의 단점이 뭔지 알고 싶습니다.

### ISSUE THREAD

**Issue by kkhkykkk** [nhnent/tui.grid#265]
많은 양의 데이터를 로드 하다보니,
페이지 버벅임과 데이터 최초로딩시 상당한 시간을 잡아먹게 됩니다.
그래서 virtualScrolling 를 사용해보니, 위의 두 부분은 엄청나게 개선 되었습니다.

하지만 그에 따른 단점이 있지 않을까 싶어서 질문 남겨 봅니다.

**Comment by dongwoo-kim** [comment]
아주 가끔 컬럼이 아주 많으면서 로우는 그리 많지 않은 경우에는, 스크롤 버벅임이 더 발생하기도 합니다. (가상 스크롤이 로우 단위로만 동작하기 때문입니다). 하지만 대부분의 경우에는 가상 스크롤링이 훨씬 좋은 성능을 보여줍니다.
다만, 가상 스킄롤은 각 행의 높이를 미리 알고 있어야만 사용할 수 있는 기능입니다. 즉, 행의 높이를 `auto`로 해 놓은 경우에는 컨텐츠의 길이에 맞게 행의 높이가 변경되어야 하기 때문에 가상 스크롤을 사용하실 수 없습니다.
