### ISSUE TITLE
editOptions의 listitems 프로퍼티 값에대해 질문 사항있습니다.

### ISSUE THREAD

**Issue by spectre3130** [nhnent/tui.grid#267]
db에서 값을 불러와서 셀렉트박스를 사용하고 싶은데 테이블이 만들어지기전까지 지연시켜 값을 넣을수 있는지 궁금합니다.

**Comment by dongwoo-kim** [comment]
질문 내용만으로는 정확한 의도를 파악하기가 어렵네요. 좀 더 자세히 설명해주실 수 있을까요?

**Comment by spectre3130** [comment]
필터에 따라 디비에서 값을 호출하여 셀렉트 박스를 만들고 있습니다. 테이블이 만들어지기 전에 값이 들어가야 제대로 생성되는 거 같아 에이잭스 호출을 블록킹 처리한 후 다수의 컬럼에다 셀렉트 박스들을 설정해주고 있습니다. 이 부분을 비동기적으로 받아와서 처리하고 싶습니다. 

> db에서 값을 불러와서 셀렉트박스를 사용하고 싶은데 테이블이 만들어지기전까지 지연시켜 값을 넣을수 있는지 궁금합니다.

**Comment by spectre3130** [comment]
필터에 따라 디비에서 값을 호출하여 셀렉트 박스를 만들고 있습니다. 테이블이 만들어지기 전에 값이 들어가야 제대로 생성되는 거 같아 에이잭스 호출을 블록킹 처리한 후 다수의 컬럼에다 셀렉트 박스들을 설정해주고 있습니다. 이 부분을 비동기적으로 받아와서 처리하고 싶습니다.

**Comment by dongwoo-kim** [comment]
참고할 만한 코드가 없어서 의도를 정확히는 알기 어렵지만.. 제 생각에 `columns` 옵션의 `editOptions.listItems` 값을 동적으로 변경하려고 하는 것 같습니다. 현재 개별 컬럼의 `editOptions`을 변경하는 API는 없지만, [setColumns](http://nhnent.github.io/tui.grid/latest/Grid#setColumns) 메소드를 사용해서 전체 `columns` 옵션 값을 갱신하는 방식으로 구현할 수 있습니다.
