### ISSUE TITLE
readData 검색후 화면에 데이터를 다 그리지 못합니다.

### ISSUE THREAD

**Issue by gurgus0189** [nhnent/tui.grid#269]
readData를 통해 데이터를 정상적으로 뿌려 줬습니다.

그러다가 데이터가 없는 경우를 검색하고 데이터가 있는 경우를 검색하면 화면에 보이지 않습니다.

원인을 찾아보니

<div class="ui-grid-body-area" style="height: "> 에 height가 행(데이터행)의 갯수만큼 높이가 늘어나야 되는데 크기가 안되다보니 데이터가 화면에 표시되지 않습니다.(데이터는 정상적으로 가져오나 안보입니다)

임시적으로 height값을 고정으로 해놓았지만 좋은 방법은 아닌것 같습니다.

해결방법이 있을까요 ?

**Comment by dongwoo-kim** [comment]
확인해 보니 내부에서 자동으로 `fixedWidth` 값을 설정할 때 버그가 있는 것 같습니다. 현재 수정 중이구요, 며칠 내로 패치 버전이 배포될 예정입니다. 제보 감사합니다 :)
