### ISSUE TITLE
support react&typescript

### ISSUE THREAD

**Issue by minsu0806** [nhnent/tui.grid#273]
안녕하세요.

nhnent의 github의 모든 프로젝트에 관심이 많은 개발자 입니다.

issues를 검색해보니 조만간 React Wrapper도 공식적으로 공개될거라는 글을 보았는데요.

typescript도 공식 지원할 예정인지요.

또 언급이 가능하시다면 언제쯤 릴리즈 되는지도 궁금합니다.

감사합니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. nhnent의 모든 공개 프로젝트에 관심이 많다니.. 
감사합니다. 열심히 해야겠네요 :)

리액트 랩퍼는 TOAST UI 전체 리액트 랩퍼들과 함께 다음 주 중에 공개될 예정입니다. 조금만 기다려주세요 ㅎ

그리고 현재 [index.d.ts](https://github.com/nhnent/tui.grid/blob/master/index.d.ts) 파일에 타입이 명시되어 있어, 타입스크립트를 사용하는 프로젝트에서는 npm 설치만 하면 바로 사용할 수 있습니다. 관련 내용은 README에 추가할 예정입니다.

**Comment by dongwoo-kim** [comment]
공식 발표가 계속 늦어져서 공유드리는 걸 잊고 있었네요; 
리액트 랩퍼는 아래 주소에 공개되어 있습니다. 
https://github.com/nhnent/toast-ui.react-grid

**Comment by minsu0806** [comment]
잊지 않고 챙겨주셔서 감사합니다 ㅎ 바로 써보겠습니다.

감사합니다~
