### ISSUE TITLE
버튼이 잘못 눌려 클로즈 되었네요 ㅠㅠ 질문 다시 올립니다.

### ISSUE THREAD

**Issue by spectre3130** [nhnent/tui.grid#276]
필터에 따라 디비에서 값을 호출하여 셀의 에디트 부분에 셀렉트 박스를 만들고 있습니다. 테이블이 만들어지기 전에 값이 들어가야 생성되는 거 같아 에이잭스 호출을 동기로 블록킹 처리한 후 데이터를 받아와 다수의 컬럼에다 셀렉트 박스들을 설정해주고 있습니다. 이 부분을 비동기적으로 받아와서 처리하고 싶습니다.

**Comment by dongwoo-kim** [comment]
기존 이슈를 다시 오픈하시면 됩니다 :) 
이슈 관리 정책상 이 이슈는 닫고, 기존 이슈에서 답변드리겠습니다.
#267
