### ISSUE TITLE
Grid내용을 출력하려고 할때

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#28]
Grid내용을 출력하려고 할때 그리드내용전체를 어떻게 받는지 궁금합니다.

**Comment by seonim-ryu** [comment]
@kjd95110 
**그리드 내용 전체**가 데이터를 말씀하시는건지요?
초기 데이터를 세팅하는 경우라면 `setRowList` API를 사용하시면 됩니다.
데이터 포멧은 튜토리얼로 제공되고 있으며 아래 링크 참조부탁드립니다.

* [https://github.com/nhnent/tui.grid/wiki/Getting-Started](https://github.com/nhnent/tui.grid/wiki/Getting-Started)
