### ISSUE TITLE
grid appendRow 후 추가 Row  속성이 disabled 모드(useViewMode:true  일때)

### ISSUE THREAD

**Issue by keyjong** [nhnent/tui.grid#287]
안녕하세요.

이번에  tui-grid 새롭게 적용하고 있는데,
그리드 로우 추가시 disabled 모드 형태가 되어 편집 불가능한 현상이 발생하였습니다.
 editOptions   useViewMode  true 을 사용한 상태입니다.

![image](https://user-images.githubusercontent.com/13306187/54670787-c9a79b80-4b37-11e9-860d-9b66e22c8d64.png)

## Version
최신 버젼임
https://uicdn.toast.com/tui-grid/latest/tui-grid.js

## Development Environment
Windows 10
Chrome이 최신 버전입니다.
버전 73.0.3683.75(공식 빌드) (64비트)

## Current Behavior
grid appendRow  Row  추가  후 Edit 모드가 아님
기존 columnData 속성은 editOptions  useViewMode  true 을 사용한 상태.
useViewMode false 일때는 정상적임.

```js
editOptions: {
  type: 'text',
  maxLength: 50,
  useViewMode: true
}

var rowData = [{cntCd: "", cntNm: "", cntKorNm: "",  cntetKorNm: "", useYn : "" , dispSeq: ""}]

grid.appendRow(rowData, {
  at: 1,
  extendPrevRowSpan: true,
  focus: true
});
```

## Expected Behavior
추가된 rows도 기존에 정의된 속성을 상속 받아서(편집가능) 추가 되어야 함.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
`useViewMode` 사용 여부와 관계 없이 새로 추가된 행도 편집이 가능해야 합니다만... 
알려주신 정보만으로는 재현이 안되네요. 스크린샷을 봐도 정확히 어떤 상황인지 알기가 어렵습니다. 
그리도 `extendPrevRowSpan` 옵션을 사용한 이유도 명확하지 않습니다.  재현 상황을 좀 더 자세히 알려주실 수 있을까요?

**Comment by keyjong** [comment]
안녕하세요. 확인해주셔서 감사합니다.
다시 확인해 보니 현상이 해결되어 있어서 종료하겠습니다.

감사합니다.

**Comment by dayemond11** [comment]
어떻게 해결하셨나요?

**Comment by D0ctrine** [comment]
제 경우에는 appendRow 하고 다음에 enable사용하니 됬습니다.
