### ISSUE TITLE
그리드의 내용을 excel export 받고 싶습니다.

### ISSUE THREAD

**Issue by mozirangi-lee** [nhnent/tui.grid#29]
그리드의 내용을 excel export 받고 싶습니다.
Net애드온 기능을 사용하지 않고 페이징을 해서 grid를 그리고 있는데,
options 값으로 toolbar: true만 해서는 excel export 기능을 사용할수 없는건가요?
샘플코드나 가이드 페이지에서는 해당 내용에 대한 부분이 없어서 문의 드립니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
현재 클라이언트 상에서는 엑셀 다운로드 기능을 제공하지 않고 있습니다. 
Net 애드온 기능과 연계된 기능도 툴바 영역에 버튼만 그려줄 뿐, 실제 기능은 서버에서 구현해서 URL을 등록해 줘야 동작합니다. (그래서 툴바의 의미가 없다고 판단되어 다음 버전에서 제거될 예정입니다.)

번거롭겠지만, 엑셀 다운로드 기능은 별도로 구현해서 사용하셔야 할 것 같습니다.
