### ISSUE TITLE
showColumn 변경시 index 초기화 현상

### ISSUE THREAD

**Issue by EventHot** [nhnent/tui.grid#290]
안녕하세요. 좋은 컴포넌트 만들어 주셔서 감사합니다. 
우선 제가 지금 설정한 설정 값이구요.

```js
grid = new tui.Grid({
    el: project.Grid(),
    scrollX: true,
    scrollY: true,
    rowHeight: 10,
    keyColumnName: 'KEY_ID',
    virtualScrolling: true,
    bodyHeight: height,
    rowHeaders: ['rowNum'],
    pagination: false,
    columns: company_colModel
});
```

위와 같이 virtualScrolling 을 사용 하고 있습니다. 

아래로 스크롤링 한후에 showColumn 이벤트로 컬럼의 보임 설정을 하는데. 
스크롤이 top : 0 으로 이동 하는 현상이 있어서 문의 드립니다. 

소스를 확인해 보니.. 
2307 라인 setHidden 에서 columnModelChange 트리거후에 refresh 이벤트에서..
초기화가 되는거 같은데요..

제가 개발 하고 있는 사이트의 컬럼이 약 50개 정도 이며. 이중에 특정 컬럼 영역들을 그룹화 하여 
보임 안보임 처리를 해야하거든요..

그래서 불필요한 데이터는 숨김 처리 한 후 스크롤링 하다가 특정 로우에서 정보를 확인 할때 위의 기능을 사용 하여야 해서요^^;

해결 방법이 잇을까요..
아니면..현재위치를 기억하고 
showColumn , hideColumn 후에 이벤트 전 위치로 이동 할수 있는 방법이 있을가요.

**Comment by dongwoo-kim** [comment]
안녕하세요. 해당 이슈는 컬럼 상태가 변경될 때 렌더링이 다시 이뤄지는 과정에서 발생하는 것 같습니다. 현재 해결 중에 있고 며칠 내로 수정해서 배포할 예정입니다.

**Comment by EventHot** [comment]
빠른 대응 감사합니다^^
늘 감사한 마음으로 이용하도록 하겠습니다.



2019년 4월 4일 (목) 오후 10:19, 김동우 <notifications@github.com>님이 작성:

**Comment by jung-han** [comment]
@EventHot v3.7.0에서 수정되었습니다.
