### ISSUE TITLE
그리드 속도 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by rhrh82** [nhnent/tui.grid#293]
## Version
3.6.0

## Development Environment
Chrome, Windows10

## Current Behavior
안녕하세요. 유용한 프로그램 잘 사용하고 있습니다. 감사드립니다.
그리드 속도 및 몇가지 문의가 있습니다.

1. 속도문제
현재 필드 수가 약 55개 정도 표시하고 있습니다.
이를 net을 통해 서버에서 가져와 출력하는 형태로 사용중인데, 가져온 후 그리드를 그리는 과정에서 대기 시간이 너무 깁니다.
크롬 개발자도구를 통해 본 결과 TTFB가 약 8초정도 입니다.
데이터를 반환하는 Ajax 페이지에서 결과를 반환해주는데 걸리는 시간은 약 1초정도 (데이터 약 9천건 중 500건) 입니다.

![20190404_112515](https://user-images.githubusercontent.com/25657721/55525750-4193cb00-56cd-11e9-995a-d147c7269fc2.png)

이 속도를 줄이려면 어떻게 해야하는것인지요.
필드가 많은것이 문제인것인지, 아니면 어떤것이 원인이 될수 있는지 알려주시면 감사하겠습니다.

2. 그리드 높이 조절
그리드의 Body 높이를 조절하면 서버에서 데이터를 새로 가져옵니다.
현재 속도 문제가 있어, 높이 조절시 데이터를 갱신하지 않도록 하고 싶습니다.

3. 페이지매김 처리 방식
현재는 서버에서 페이징처리하여 총 10000건 중 500건만 조회하여 반환해주도록 하였습니다.
전체 데이터를 가지고 그리드 자체에서 페이지매김처리되는 방법은 없는것인지요.
즉, 10000개의 데이터를 한번에 가져오고, 이를 페이징 처리하는것은그리드 자체에서 처리하고, 정렬시에도 서버와 통신하지 않고 전체 10000개의 데이터를 가지고 정렬이 수행되는 방법을 알고 싶습니다.

두서 없는 질문글인줄 잘 압니다. 이해가 어려우실수 있으나 답변은 꼭 부탁드립니다.
감사합니다 (__)

```js
// Write example code
```

**Comment by dongwoo-kim** [comment]
안녕하세요. 알려주신 정보만으로는 정확한 답변을 드리기 어렵습니다만.. 
일단 제가 이해한 내용으로 최대한 설명드리겠습니다.

### 1. 속도 문제
그리드는 대용량 데이터 사용 시 속도를 개선하기 위해 "페이징"과 "가상 스크롤링" 두 가지의 방식을 사용합니다. 현재 페이징 방식을 사용하고 있는 것 같은데, 500개씩 끊어서 보여주더라도 필드가 55개나 되면 데이터가 꽤 많아서 렌더링 속도에 영향을 줄 수 있습니다. 만약 가상 스크롤링을 사용하지 않고 있다면, `virtualScrolling: true` 옵션을 사용해서 성능을 개선할 수 있을 것 같습니다.

개발자 도구의 TTFB는 서버의 응답 속도를 나타내기 때문에 그리드의 렌더링 속도와는 크게 관계가 없는 것 같습니다. (그래프에도 표시되어 있듯이, 서버에 요청을 보낸 시간부터 실제 데이터를 다운로드 시작하기 전까지의 시간을 나타냅니다). 

### 2. 그리드 높이 조절
이 부분은 확인이 좀 어렵네요. 그리드 높이 조절과 서버 요청은 크게 관계가 없습니다만.. 혹시 어떤 방식으로 그리드의 높이를 변경하고 있는지 알려주실 수 있을까요.

### 3. 페이지매김 처리 방식
현재 페이지네이션은 Net과 연동하는 경우에만 작동하도록 구현되어 있습니다. 클라이언트에서 페이징을 처리하려면 해당 로직(페이징 처리, 정렬 처리 등)을 클라이언트에서 직접 구현하셔서 그리드의 데이터를 매번 변경해 주셔야만 합니다. 이 부분은 개선 예정입니다만, 현재 계획으로는 4.0 이후에나 구현이 가능할 것 같습니다.

**Comment by rhrh82** [comment]
친절하고 상세한 답변에 매우 감사드립니다.
질문을 좀더 보강하자면..

1. 속도문제
- 현재 가상스크롤과 페이징 기능을 사용중입니다.
- TTFB가 8초가량 나오는것이 실제 서버상의 문제라면.. 어떻게 체크해봐야 할런지요.
-- 그리드를 제외하고 실제 서버에서 Ajax를 통해 값이 넘어오는 시간 : 1초 남짓
-- 그리드를 포함하고 실제 서버에서 Ajax를 통해 값이 넘어오는 시간 : 8초 남짓
`$.ajax({
    type:"POST",
    dataType:"JSON",
    url:"grid.php",
    success:function(data){
        console.log(data);
    }
})
//--- 이렇게만 했을때 약 1초 남짓

grid.use('Net',{
    el:$('#form'),
    perPage:500,
    initialRequest:true,
    readDataMethod:'POST',
    enableAjaxHistory:false,
    api:{
        readData:'grid.php',
    }
});
//--net을 사용하여 그리드를 적용했을때 약 8초 남짓
`
말씀하신데로 필드 수와 한번에 가져오는 데이터의 양에 따라 속도에 변화가 있었습니다.
음 프로그램 특성상 필드수를 줄일수가 없는데 큰일이네요. 답변해주신 내용 토대로 방법을 찾아 보겠습니다. 

2. 그리드 높이 조절
- 그리드 영역(body)의 높이를 조절하는 (heightResizable:true) bar를 드래그 하여 높이를 조절하면
서버에서 다시 데이터를 가져옵니다.(즉, 로딩바가 나타나고 그리드가 새로 그려집니다. net.reloadData() 를 사용한것과 같은 현상) 현재 TTFB 측정 시간이 약 8초남짓이라 가로 스크롤을 움직이려다 실수로 높이 조절 bar를 건드리면 8초를 또 기다려야 하는 상황입니다.. 높이 조절 기능은 필요한데, 높이만 조절되는 방법은 없을련지요.

3. 페이지매김
- 추후 업데이트 버전을 기다리겠습니다.

답변 주신 내용으로 로컬에서 페이지매김처리 및 그리드 높이 조절시 문제 모두 해결이 가능할것 같습니다.

매우 감사드립니다.

**Comment by dongwoo-kim** [comment]
답변 감사합니다. 도움 드린 건 별로 없는데.. 그래도 문제 해결이 가능할 것 같다고 하시니 다행이네요. 몇가지 답변 추가로 드립니다.

### 1. 속도 문제

이미 가상 스크롤과 페이징을 동시에 사용중이라고 하시니, 렌더링 관련 성능은 그 이상 개선하기 힘들 것 같네요. 4.0에서는 필드가 많을 때 성능이 느린 문제를 해결하기 위해 컬럼 단위의 가상 스크롤도 지원할 예정입니다. (하지만 대규모 업데이트라 시간이 좀 걸려서.. 릴리스 시기를 최소 5월말 이후로 예상하고 있습니다)

TTFB가 8초 가량 나오는 문제는 사실 파악이 어렵네요. 현재 의심가는 부분은 "Ajax 요청 파라미터나 헤더 정보가 달라서 서버가 다르게 반응할 수도 있다" 정도입니다만.. 요청 헤더가 다른 점은 Content-Type이 'application/x-www-form-urlencoded; charset=UTF-8' 로 지정된다는 것 밖에 없는 것 같습니다. 혹시 이 차이로 인해 서버가 다르게 반응할 수도 있는지 아니면, 페이지 관련 파라미터 값이 제대로 해석되고 있는지(POST 메소드 사용시 form 데이터로 전송됨)는 확인해 보면 좋을 것 같습니다.

### 2. 그리드 높이 조절
소스를 찾아봤는데, 높이 조절과 서버 요청이 연동되는 부분을 찾기가 어렵네요. 가능하시다면 XHR 요청을 보내는 시점의 함수 호출 스택 정보를 알려주시면 확인에 도움이 될 것 같습니다.

**Comment by rhrh82** [comment]
qwrqwrqwrqrqwrqwrqwrqr
qwrqwrqwrqr
qwrqwrqwrqr
qwrqwrqwrqr

**Comment by rhrh82** [comment]
상세한 답변 매우 감사드립니다.

답변주신 내용을 토대로 소스를 수정해보겠습니다.

아무래도 그리드 자체 문제가 아닌것 같다는 결론이 나왔습니다.

혼란을드려 대단히 죄송합니다만 답변을 보고나니 결론이 나오네요.

노고에 감사드립니다. (__)
