### ISSUE TITLE
컬럼 클릭 시, 클릭했다는 UI 피드백이 없어 어색합니다.

### ISSUE THREAD

**Issue by cybaek** [nhnent/tui.grid#3]
* 버전: 1.1.1

로(row)를 클릭하면 반전이 생기는데,
컬럼을 클릭하면 헤딩(heading) 영역에 아무런 UI피드백이 없습니다.

클릭 시, 눌림이든 반전이든 뭔가 피드백이 있으면 보다 자연스러울 것 같습니다.

**Comment by dongwoo-kim** [comment]
의견 감사합니다. 
클릭 뿐만 아니라 현재 로우헤더의 기능처럼 '셀렉션', '포커스' 관련해서 UI피드백이 추가되어야 할 것 같습니다.
정리해서 다음 버전에 반영될 수 있도록 하겠습니다.

**Comment by dongwoo-kim** [comment]
1.1.3 버전에 반영되었습니다.
