### ISSUE TITLE
그리드에서 datetimepicker tui component를 적용하는 방법이 궁금합니다..

### ISSUE THREAD

**Issue by javakiller** [nhnent/tui.grid#30]
안녕하세요~
게임포털개발팀 이효민 입니다.

grid 에서 datetimepicker tui component 를 적용하는 방법이 궁금합니다. 
아래 예제 페이지에서 년/월/일 까지는 적용하는 방법을 확인했습니다.
https://nhnent.github.io/tui.grid/api/tutorials/example5.html

아래 예제에 있는 것과 같이 년/월/일 시:분:초 형식을 grid cell에 적용하려고 하는데, grid에 columnModelList 쪽 component 옵션에 어떻게 넣어야할지 잘 모르겠습니다.
https://nhnent.github.io/tui.component.date-picker/latest/tutorials/datetimepicker.html

적용이 가능할지와. 가능하다면 가이드좀 부탁드리겠습니다.

참고로 작업중인 페이지에서 import하고 있는 js,css 들은 아래와 같습니다..
------------------------------------------------------------------------------------------------------------------
<link rel="stylesheet" type="text/css" href="/share/tui.grid/grid.min.css" />
<script type="text/javascript" src="/share/tui.grid/underscore-1.8.3.js"></script>
<script type="text/javascript" src="/share/tui.grid/backbone-1.1.2.js"></script>
<script type="text/javascript" src="/share/tui.grid/code-snippet-1.2.0.js"></script>
<script type="text/javascript" src="/share/tui.grid/pagination-1.0.3.js"></script>
<script type="text/javascript" src="/share/tui.grid/calendar-1.1.2.js"></script>
<script type="text/javascript" src="/share/tui.grid/date-picker-1.3.1.js"></script>
<script type="text/javascript" src="/share/tui.grid/grid.min.js"></script>
------------------------------------------------------------------------------------------------------------------

그리고 아래는 grid 쪽에 기존에 설정되어 있는 component 옵션 입니다.
------------------------------------------------------------------------------------------------------------------
        {
            "title" : "<b>판매시작<br>start_date</b>",
            "columnName" : "startDate",
            "width" : 100,
            "align" : "right",
            "editOption" : {
                type: 'text'
            },
            component: {
                name: 'datePicker',
                option: {
                    dateForm: 'yyyy/mm/dd',
                    date: {year: 1970, month: 1, date: 1}
                }
            }
        },
------------------------------------------------------------------------------------------------------------------

그럼, 확인 부탁드리겠습니다~^^
감사합니다

**Comment by seonim-ryu** [comment]
안녕하세요 :) 문의주신 내용은 확인하였습니다.

데이트피커에서 시간을 표시하기 위해서는 타임피커 옵션을 넘겨주어야 하는데요.
그리드에서는 내부적으로 데이트피커 객체를 생성하는데 이 때 타임피커 옵션은 처리하고 있지 않아
해당 기능을 사용하기 위해서는 추가 개발이 필요합니다.

다만 현재 그리드 2.0 배포를 앞두고 있어서 추가 개발을 하게 될 경우 2.0 배포 이후에 적용이 가능하며,
사용하고 계신 그리드 및 컴포넌트 버전 업데이트로 마이그레이션 작업이 필요할 것으로 보입니다.

해당 내용 검토해보신 후 개발 일정과 필요하신 기능과 관련하여
FE개발랩 DL로 요청주시면 감사하겠습니다. :)

**Comment by javakiller** [comment]
넵~ 빠른 확인 감사드립니다. 추가 내용은 메일로 전달드리겠습니다^^
