### ISSUE TITLE
스크롤바 제거방법 및, editOption 을 통한 이벤트 체크 문의드립니다.

### ISSUE THREAD

**Issue by junyoungJeong** [nhnent/tui.grid#31]
1. 스크롤바 제거방법
스크롤바가 필요없는 경우에도, 우측과 하단에 스크롤바 영역이 존재하는데, 없애는 설정값이 있는지 궁금합니다.

2. editOption으로 text값 및, selectbox , checkbox, radio..등 변경하는 가이드가있는데요.
http://nhnent.github.io/tui.grid/api/tutorial-example04.html
이 기능을 통해 값이 변경될때, 어떤 이벤트로 잡아야하나요? 변경시, 바로 서버랑 통신해서 값을 바꾸고 싶습니다.  가이드엔 onBeforeChange 가있는데, 아무런 콘솔도 찍히지 않습니다.

**Comment by seonim-ryu** [comment]
안녕하세요. FE개발랩입니다.
메신저로 전달드리긴 하였으나 이슈 관리를 위해 다시 정리해 드립니다. :)

1. 스크롤바 영역 제거 방법
`scrollX`, `scrollY` 옵션 값을 `false`로 설정하면 제거됩니다.

2. onBeforeChange 동작 이상
`onBeforeChange` 및 `onAfterChange` 옵션의 뎁스가 변경되었습니다.
다음과 같은 뎁스로 이동되어 사용에 유의 부탁드립니다.
```js
{
    onBeforeChange: function() { /* ... */ },
    onAfterChange: function() { /* ... */ },
    editOptions: { /* ... */ }
}
```
