### ISSUE TITLE
모바일웹에서 셀 클릭 시 포커싱 문제

### ISSUE THREAD

**Issue by dellamore** [nhnent/tui.grid#32]
좋은 소스를 공개해주신 덕분에 잘 사용하고 있습니다.

한 가지 원인을 확인할 수 없어서 글 남깁니다.

모바일웹에서 그리드로 표시되는 셀을 클릭할 경우 
좌상단(0,0)으로 화면이 자동 스크롤되고 모바일용 키패드가 표시되는 현상이 있습니다.

edit 옵션을 주지 않았음에도 셀을 클릭하면 모두 동일하게 반응합니다.

HTML을 확인해 보면 Input 태그가 아님에도 키패드가 나오는 현상은 무엇인지 알 수 있을까요?

혹시나 해서 예제에서도 테스트해보았는데 동일하게 반응하네요.

**Comment by seonim-ryu** [comment]
@dellamore 
안녕하세요. 그리드를 사용해주셔서 감사합니다 :)

현재 그리드에서 클립보드 기능을 처리하기 위해서 `textarea` 태그를 포함하고 있는데요.
그리드의 셀을 선택할 때 자동으로 해당 `textarea`에 포커싱이 발생하게 됩니다.

모바일 디바이스에서는 `input` 또는 `textarea` 태그에 포커싱되면 키패드가 활성화되며
위에서 설명드린 `textarea`에 의해서 문의주신 내용과 같이 동작하게 됩니다.

해당 내용 확인 부탁드리겠습니다.

**Comment by dellamore** [comment]
자세한 답변 감사합니다!
