### ISSUE TITLE
grid dblclick Properties API 문서와 다르네요.

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#34]
1.9.0 버젼으로 개발하다 2.1.0 으로 업그레이드 하려고 하다보니, 
많이 바뀌었네요.
먼저, 노고에 감사드립니다.

그리드 이벤트에서 API 문서에는 아래와 같이 나와 있는데,

dblclick
Occurs when a mouse button is double clicked on the Grid.
The event object has all properties copied from the native MouseEvent.

Type:
module:event/gridEvent

Properties:
Name	Type	Description
targetType	string	 type of event target
rowKey	number	 rowKey of the target cell
columnName	string	columnName of the target cell

실제로 해보니,  targetType 하나에 모두 들어있네요.
API 문서하고 현재 버젼하고 달라서 글 남깁니다.
확인 부탁드려요.

**Comment by seonim-ryu** [comment]
안녕하세요. 제보 감사합니다.
해당 내용은 다음 버전 업데이트 때 수정하여 반영하도록 하겠습니다.
감사합니다 :)

**Comment by globeer** [comment]
감사합니다.
