### ISSUE TITLE
editoptions 에 changeBeforeCallback 함수 기능은 어떻게 구현해야 할까요?

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#35]
1.9.0 버젼에서 changeBeforeCallback 함수에서 상품 소분류 선택에 따른 가격, 할인률 등을 셋팅해 주었는데,

2.0.0 버젼이상에서 changeBeforeCallback 함수가 없어진것 같습니다.

onBlur 이벤트보다는 onChange 이벤트가 성격에 맞을 것 같은데, 이벤트가 없네요.

이런 기능은 어디에서 구현해야 할까요?

**Comment by seonim-ryu** [comment]
2.0.0 버전에서 해당 콜백 함수명과 뎁스(`editOptions` 상위 이동)가 변경되었습니다.
변경된 내용은 하단에 정리하였으며, 추가로 [마이그레이션 가이드](https://github.com/nhnent/tui.grid/wiki/TUI-Grid-2.0.0-Migration-Guide)도 함께 참조 부탁드리겠습니다. :)

* 1.9.0 이하 버전
```js
{
    columns: [
        {
            editOptions: {
                changeBeforeCallback: function() { /* .. */ },
                changeAfterCallback: function() { /* .. */ }
            }
        }
    ]
}
```
* 2.0.0 이상 버전
```js
{
    columns: [
        {
            onBeforeChange: function() { /* .. */ }, // same as changeBeforeCallback
            onAfterChange: function() { /* .. */ }, // same as changeAfterCallback
            editOptions: { /* ... */ }
        }
    ]
}
```

**Comment by globeer** [comment]
빠른 답변에 감사드립니다.
