### ISSUE TITLE
relations에서 대, 중, 소 분류인 경우 대분류 변경시 소분류가 남아 있는 현상 외

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#36]
수고 많으십니다. 2.1.0-a 업그레이드 하면서 발생한 현상 확인 요청 드립니다.

1. dblclick 와 비슷하게 click event Parameters 값이 API 문서와 다릅니다. 확인 부탁합니다.

2. relations에서 대, 중, 소 분류인 경우 대분류 변경시 소분류가 남아 있는 현상 확인 부탁합니다.
var grid = new tui.Grid({
    el: $('#grid'),
    scrollX: false,
    scrollY: false,
    rowHeight: 30,
    columns: [
        {
            title: 'Category1',
            name: 'category1',
            editOptions: {
                type: 'select',
                listItems: [
                    { text: 'Select', value: '' },
                    { text: 'Domestic', value: '01' },
                    { text: 'Overseas', value: '02' },
                    { text: 'Etc', value: '03' }
                ],
                useViewMode: false
            },
            relations: [
                {
                    targetNames: ['category2'],
//                    targetNames: ['category2', 'selectedValue'],
                    // targetNames: ['category2'],
                    listItems: function(value) {
//                        console.debug("listItems ###", value);
                        return twoDepthData[value];
                    },
                    disabled: function(value) {
                        return !(value);
                    }
                },
                {
                    targetNames: ['category3'],
                    disabled: function(value) {
                        console.debug("disabled ###", value);
                        return !(value);
                    }
                }
            ]
        },
        {
            title: 'Category2',
            name: 'category2',
            editOptions: {
                type: 'select',
                listItems: [],
                useViewMode: false
            },
            relations: [
                {
                    targetNames: ['category3'],
                    listItems: function(value) {
                        return treeDepthData[value];
                    },
                    disabled: function(value) {
                        return !(value);
                    }
                }
            ]
        },
        {
            title: 'Category3',
            name: 'category3',
            editOptions: {
                type: 'select',
                listItems: [],
                useViewMode: false
            }
        }
    ]
});

3. 2.x 대로 업그레이드 하는 가이드 문서를 readme 문서에 링크 걸어주시면 좋을 것 같습니다.

4. 여유가 되신다면, 각 버젼별 API 문서를 제공해 주시면 좋겠습니다.

수고하세요.

**Comment by codepink** [comment]
@globeer 
먼저 그리드를 적극적으로 사용해주셔서 감사합니다. :)
문의주신 내용들 답변드립니다.

1. 이벤트 관련 주석은 이번 2.1.0 정식 버전 배포 때 전체적으로 수정될 예정입니다.
2. 버그로 확인되었으나, 내부 로직상 바로 처리될 수 있는 이슈가 아니어서 개선 사항으로 등록해두었습니다.
3. README에서 API 문서, 튜토리얼, 예제 페이지를 제외한 나머지 문서들은 wiki로 관리되고 있는데요. 의견주신 내용은 적극 검토해보겠습니다.
4. 현재 그리드가 배포되면 버전에 따라 릴리즈 노트를 작성하고 있으며, 각 버전별 API 문서 링크를 함께 제공하고 있습니다. [릴리즈 노트](https://github.com/nhnent/tui.grid/releases)에서 확인 부탁드립니다.

**Comment by seonim-ryu** [comment]
@globeer 
먼저 그리드를 적극적으로 사용해주셔서 감사합니다. :)
 문의주신 내용들 답변드립니다

1. 이벤트 관련 주석은 이번 2.1.0 정식 버전 배포 때 전체적으로 수정될 예정입니다.
2. 버그로 확인되었으나, 내부 로직상 바로 처리될 수 있는 이슈가 아니어서 개선 사항으로 등록해두었습니다.
3. README에서 API 문서, 튜토리얼, 예제 페이지를 제외한 나머지 문서들은 wiki로 관리되고 있는데요. 의견주신 내용은 적극 검토해보겠습니다.
4. 현재 그리드가 배포되면 버전에 따라 릴리즈 노트를 작성하고 있으며, 각 버전별 API 문서 링크를 함께 제공하고 있습니다. [릴리즈 노트](https://github.com/nhnent/tui.grid/releases)에서 확인 부탁드립니다.
