### ISSUE TITLE
editOptions onBlur 이벤트 관련

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#37]
chrome 브라우져에서 onBlur 이벤트 발생을 인식하지만,

firefox, ie11 에서는 인식하지 않습니다.

다른 이벤트들은 테스트 하지 않았습니다.

같이 확인 부탁드려요.

**Comment by codepink** [comment]
@globeer 
`editOptions`를 통해서 생성된 `input` 중 어느 타입에서 이벤트가 발생하지 않는지요?
좀 더 구체적으로 전달해주시면 감사하겠습니다. :)

**Comment by seonim-ryu** [comment]
@globeer
editOptions를 통해서 생성된 input 중 어느 타입에서 이벤트가 발생하지 않는지요?
좀 더 구체적으로 전달해주시면 감사하겠습니다. :)

**Comment by globeer** [comment]
그리드 칼럼 할인률을 입력후에 onBlur 시에 판매금액을 수정하는 기능입니다.
코드는 다음과 같습니다.

              {
	            title : "<b>할인률</b>"
	          , name : "dscnt_rt"
		      , align : "right"
	          , editOptions : {
	                type: 'text',
	                onBlur : function(ev, data) {
	                	var calcValue = grid_tab_sales_treat.getValue(data.rowKey, 'bsn_untpc') * (100 - parseInt(ev.target.value)) * 0.01;
                  	    grid_tab_sales_treat.setValue(data.rowKey, 'pymnt_amount', calcValue);
	                }
                   }	            
              }

**Comment by codepink** [comment]
@globeer 
예제 코드로 해당 브라우저(Firefox, IE11)에서 `blur` 이벤트 정상 동작하는 것을 확인하였습니다.
다른 PC 환경에서도 동일한 현상이 발생하는지 확인 부탁드리며 os 정보도 전달해주시면 감사하겠습니다. :)

**Comment by seonim-ryu** [comment]
@globeer
예제 코드로 해당 브라우저(Firefox, IE11)에서 blur 이벤트 정상 동작하는 것을 확인하였습니다.
다른 PC 환경에서도 동일한 현상이 발생하는지 확인 부탁드리며 os 정보도 전달해주시면 감사하겠습니다. :)
