### ISSUE TITLE
그리드 컴포넌트에서 datepicker option 질문드립니다

### ISSUE THREAD

**Issue by sehwans** [nhnent/tui.grid#38]
안녕하세요
그리드 컴포넌트에서 columns 설정부분에
datePicker 적용시, options 적용이 되지 않아 질문드립니다

new tui.Grid({
 ...
 ...
columns : [
   {
	            title : "<b>생산년도</b>",
	            name : "PRODUCTION_YEAR",
	            width : 100,
	            editOptions : {
	                type: 'text'
	            },
	            sortable:true,
	            component: {
	                name: 'datePicker',
	                options: {
                      /*
                          아래부분에 type: 'year' 옵션 등 그리드에서 datePicker 컴포넌트를 사용할 때
                          사용자 UI 에서 년도 선택화면을 기본적으로 표현하고자 합니다
                     */
	                    format: 'yyyy', 
	                    type: 'year'
	                }
	            }
	        },
   ]
})

위의 소스대로 적용하였을때, year 옵션이 적용되지 않는 문제에 대해 해결 방안이 있는지요..

**Comment by codepink** [comment]
@sehwans
그리드를 사용해 주셔서 감사합니다. :)
먼저 현재 사용하고 계신 그리드 및 데이트피커 컴포넌트 버전 확인이 필요합니다.
버전 확인 후 문의주신 내용에 대해서 다시 가이드 드리겠습니다.

**Comment by seonim-ryu** [comment]
@sehwans
 그리드를 사용해 주셔서 감사합니다. :) 
먼저 현재 사용하고 계신 그리드 및 데이트피커 컴포넌트 버전 확인이 필요합니다. 
버전 확인 후 문의주신 내용에 대해서 다시 가이드 드리겠습니다.

**Comment by sehwans** [comment]
안녕하세요
답변 감사합니다
사용중인 데이트피커 컴포넌트 버전정보는 다음과 같습니다
/*!
 * tui-component-datepicker.js
 * @version 2.1.0
 * @author NHNEnt FE Development Lab <dl_javascript@nhnent.com>
 * @license MIT
 */

추가로 그리드 버전은 다음과 같습니다
/*!
 * bundle created at "Wed Apr 26 2017 23:22:55 GMT+0900 (KST)"
 * version: 2.1.0-a
 */

**Comment by seonim-ryu** [comment]
@sehwans 
버전 정보 전달해주셔서 감사합니다.
현재 그리드에서는 기본 데이트피커만 생성이 가능한데요.
2.1.0 버전에서 `type`, `timepicker` 등 추가 옵션을 통해 연/월/시간 선택이 가능한 타임피커 생성 기능이 추가될 예정입니다.
배포 후 다시 코멘트 드리겠습니다. :)

**Comment by sehwans** [comment]
답변 감사합니다!
버전 업데이트 기대하겠습니다~

**Comment by seonim-ryu** [comment]
@sehwans 
안녕하세요 :) 오늘 그리드 2.1.0 배포가 있었습니다.
[예제 페이지](https://nhnent.github.io/tui.grid/api/tutorial-example08.html)에서 확인하실 수 있으며
적용 중에 어려우신 점 있으시면 다시 코멘트 남겨주세요! 감사합니다.
