### ISSUE TITLE
grid row click 시 grid_id.addRowClassName(rowKey, 'myStyle') 시 에러

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#39]
그리드 로우 클릭 시 아래와 같이 했을 때,
grid_id.addRowClassName(rowKey, 'myStyle');

다음과 같은 스크립트 오류가 발생합니다.
grid.min.js:5 Uncaught TypeError: Cannot read property 'addClassName' of undefined
    at child.addRowClassName (grid.min.js:5)

확인 부탁드립니다.

**Comment by seonim-ryu** [comment]
@globeer
현재 발생하는 에러 메세지의 경우,
유효하지 않은 `rowKey` 값으로 해당 API를 호출했을 때 발생하게 됩니다.
해당 내용 확인 부탁드립니다. :)
