### ISSUE TITLE
grod.setData(rows) 시에 데이터 7건인데 3건만 보이네요.

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.grid#41]
크롬 디버거에서 확인한 내용입니다.

rows 에 array로 7건의 데이터가 있는데,

그리드 setData(rows) 하면 그리드에 3건만 보이네요. 

로우 칼럼값들이 같은 경우 표현하지 않는 건가요?

**Comment by seonim-ryu** [comment]
@globeer
먼저 그리드 생성 시 세팅하는 데이터 및 `setData` 호출 시 데이터 정보 확인이 필요할 것 같습니다.
데이터 정보(`rows`) 전달해주시면 확인 후 다시 가이드 드리겠습니다.

**Comment by globeer** [comment]
그리드에 
keyColumnName 을 잘못 주었을때 발생하는 문제였습니다.
혼선을 드려 미안합니다.
