### ISSUE TITLE
그리드 컴포넌트 datepicker 문제

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#42]
type : year, month 였을때 달력이 년도, 년월만 나와야 되는데 안되네요.

달력컨트롤에도 같은 문제입니다..

**Comment by seonim-ryu** [comment]
@david80 
현재 그리드는 데이트피커 생성 시 `type`, `timepicker` 옵션이 적용되지 않습니다.
앞으로 배포될 2.1.0 버전에서 적용이 가능하며 배포 후 코멘트 드리겠습니다. :)

**Comment by seonim-ryu** [comment]
@david80 
오늘 그리드 2.1.0 버전이 배포되었습니다.
[예제 페이지](https://nhnent.github.io/tui.grid/api/tutorial-example08.html)에서 기능 동작 확인이 가능하며,
적용 중에 어려운신 점 있으실 경우 다시 코멘트 부탁드립니다. 감사합니다.
