### ISSUE TITLE
Getting-Started 페이지 내 예제 소스 오기 사항 제보

### ISSUE THREAD

**Issue by caoyanxiong-ne** [nhnent/tui.grid#43]
* 해당 페이지 : https://github.com/nhnent/tui.grid/wiki/Getting-Started

## 1. Including Files

![image](https://cloud.githubusercontent.com/assets/18527609/26476025/b4666bb2-41f6-11e7-8a79-eb8badcfcd73.png)

아래와 같이 파일명에 `-component-` 가 붙어야 합니다.

```html
<script src="bower_components/tui-component-pagination/dist/tui-component-pagination.js"></script>
<script src="bower_components/tui-component-date-picker/dist/tui-component-datepicker.js"></script>
```

## 2. Setting data 

![image](https://cloud.githubusercontent.com/assets/18527609/26476052/f49407da-41f6-11e7-8465-4ac5ec50fac3.png)

`grid.setRowList()` 는 없어진(?) 듯합니다. 

![image](https://cloud.githubusercontent.com/assets/18527609/26476070/0b073e4c-41f7-11e7-9f82-4cb008a36643.png)

`setRowList()` 대신 `setData()` 로 하니 동작해서, 해당 부분 확인 필요합니다.

**Comment by seonim-ryu** [comment]
@caoyanxiong-ne
소중한 제보 감사합니다 :)
해당 내용은 수정하여 반영해두었습니다.
