### ISSUE TITLE
기능사용중 도움요청

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#44]
그리드에 select 박스나 text박스는 있는데. 
공통팝업을 띄워서 팝업에서 파라미터받아서 세팅하는 샘플은  없는듯합니다.
샘플이 있었으면 좋겠습니다.

**Comment by seonim-ryu** [comment]
@david80
안녕하세요.
일단 문의주신 내용이 잘 이해되지 않는데요 ^^;
혹시 어떤 기능을 원하시는지 다른 그리드 예제를 전달해주시거나
더 구체적으로 기능 설명을 해주신다면 감사하겠습니다.

**Comment by david80** [comment]
그리드 셀안에서 주소찾기 버튼이 있다고 가정했을때 그버튼을 눌러서 다음주소팝업같은 주소를 리턴받아 값을 그리드안의 JSON 데이터셋에 넣는 샘플같은게 있었으면 합니다.

**Comment by seonim-ryu** [comment]
@david80 
문의주신 기능의 경우 팝업은 서비스단에서 구현하고
해당 팝업에서 값을 선택한 후에 그리드의 `setValue` API를 사용해 데이터를 세팅하면 될 것 같습니다.

현재 예제 페이지는 주요 기능들에 대해서 제공하고 있으며,
특정 서비스에 관련된 예제 페이지는 제공하고 있지 않으므로 양해 부탁드립니다. :)
