### ISSUE TITLE
그리드 셀 에디트 비활성 옵션은??

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#45]
그리드 특정 키 값에 따라 에디트 옵션을 비활성 하고 싶습니다!

**Comment by seonim-ryu** [comment]
@david80 
키 값이 그리드의 `rowKey`를 말씀하시는건지요?
`editOptions`을 사용해 생성된 input 컬럼 중 특정 행만 비활성화(기존 데이터 사용)하려는 경우,
`converter` 옵션을 사용하여 다음과 같이 처리하면 가능합니다.
```js
editOptions: {
    type: 'text',
    useViewMode: false,
    converter: function(value, rowData) {
        if (rowData.rowKey !== 0) {
            return false;
        } else {
            return value;
        }
    }
}
```
확인 부탁드리겠습니다.

**Comment by david80** [comment]
행이 아니라 그 행의 특정셀만 비활성 처리할려고 합니다.

**Comment by david80** [comment]
기능이 작동을 안하는것 같습니다.. 일단 포맷터로 처리했습니다..

**Comment by oracle77** [comment]
그리드 한컬럼에 데이타를 DATA1줄바꿈 DATA2 줄바꿈 DATA3  이렇게 입력하고 싶은데
방법이 있나요 ? 개행문자를 넣어도 안되네요
