### ISSUE TITLE
editOptions.type의 number 추가

### ISSUE THREAD

**Issue by sagnol** [nhnent/tui.grid#46]
editOptions.type에 number가 추가되면

validation 처리가 용이할 것 같아요.

아니면, validate의 TYPE_NUMBER 처리를 

onBeforeChange나 onAfterChange 쪽에서 할 수 있을까요?

number 처리가 쉽지 않네요.

**Comment by seonim-ryu** [comment]
@sagnol 
현재는 `editOptions` 옵션을 통해 생성되는 `input` 중 넘버 타입은 제공되고 있지 않은데요.
정확하게 어떠한 기능을 필요로 하는 것인지 구체적으로 설명해주시면 감사하겠습니다. :)

**Comment by sagnol** [comment]
현재 막혀있는 부분이 number type이 필요한 경우에

유저가 입력시, 숫자만 입력하게 하려고 합니다. 

제가 구현했을때, 서툴러서 그런지는 몰라도

onBeforeChange 쪽에서 return false 로 해도 입력이 되네요. 
(당연히 onBeforeChange 와 onAfterChange의 뎁스는 확인했습니다. 2.0버전 사용중입니다.

![2017-06-12 4 39 43](https://user-images.githubusercontent.com/17628907/27023496-c7637bac-4f8d-11e7-8bcd-73ff539df15a.png)

그래서, number type을 제공을 하게 되면

data type 의 validation 체크가 편하지 않을까해서 올렸습니다.

아래는 실제 사용했던 코드입니다.

```
{
  title: 'Cost',
  name: 'cost',
  validation: {
    required: true,
    dataType: 'number'
  },
  defaultValue: 0,
  onBeforeChnage: function (ev) {
    if(Number(ev.value)){
      ev.value = Number(ev.value);
      return ev;
    }else{
      return false;
    }
  },
  editOptions: {
    type: 'text'
  }
}
```

**Comment by seonim-ryu** [comment]
@sagnol 
구현하고자 하는 기능에 대해 현재 예제처럼 사용하는 것이 맞습니다.

다만 `onBeforeChange` 콜백에서 이벤트를 취소할 때,
`return false` 대신 `ev.stop()`을 호출하시면 정상 동작하게 됩니다.

해당 내용은 2.0 이상 버전부터 변경되었고, 현재 주석이 수정되지 않아 혼동을 드린 것 같습니다.
다음 버전 배포 때 적용될 예정이며, 양해 부탁드리겠습니다 :)

**Comment by sagnol** [comment]
감사합니다!

그런데 number type은 지원 안하시나요?

**Comment by seonim-ryu** [comment]
@sagnol 
넘버 타입 지원은 내부적으로 검토해보고 지원이 가능하면 다시 코멘트 드리겠습니다.
TUI 그리드 사용해주셔서 감사합니다! :)
