### ISSUE TITLE
grid에서 특정 위치에 행을 추가하고 싶습니다.

### ISSUE THREAD

**Issue by ing486sa** [nhnent/tui.grid#47]
안녕하세요.
grid에서 특정 위치에 행을 추가하고 싶습니다.
예제에 가 보니 없는 것 같습니다만....
지원되는 기능인지 확인 좀 부탁드려요~

**Comment by seonim-ryu** [comment]
@ing486sa
안녕하세요. 그리드를 사용해주셔서 감사합니다 :)
아쉽게도 현재는 그리드에서 해당 API를 제공하고 있지 않습니다.
대신 `setData`를 사용하여 처리가 가능한 부분으로 확인 부탁드리겠습니다.

**Comment by DandyU** [comment]
저는 아래와 같이 특정 위치에 행 추가를 하도록 했씁니다.

function appendRow(index) {
	var newRow = {
			eventId: '',
			localEvent: '',
			copyControl: ''
	};
	if (index== null) {
		grid.appendRow(epgCleanRow, null);
	} else {
                var optionsOpt = {
					at: indx,
					extendPrevRowSpan: false,
					focus: false
			};
			grid.appendRow(newRow , optionsOpt);
	}
}

**Comment by seonim-ryu** [comment]
@DandyU 
질문을 혼동했던 것 같습니다 ^^; 답변 감사합니다 :)
