### ISSUE TITLE
날짜 클릭이후 다른 셀 선택후 날짜 캘린더 선택시 데이터 바인딩..

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#49]
![happystation_kr_20170626_123708](https://user-images.githubusercontent.com/11273651/27524026-74b2890e-5a6c-11e7-8d41-ec1157980e2e.jpg)

다른 셀 선택시 앞에서 날짜 컨트롤 선택시 나왔던 캘린덕 박스 날짜 데이터가 바인딩이 됨..

**Comment by seonim-ryu** [comment]
@david80 
안녕하세요. 현재 제공되고 있는 [예제 페이지](http://nhnent.github.io/tui.grid/api/tutorial-example08.html) 및 테스트를 하였을 때
재현되지 않는 현상으로 사용하고 계신 버전 및 테스트 코드를 전달해주시면 감사하겠습니다.

**Comment by david80** [comment]
![4](https://user-images.githubusercontent.com/11273651/27782519-d52a534c-600d-11e7-9e54-debe544a361a.png)

예제에서도 같은 현상입니다.
날짜데이터가 있는 상태에서 다른 캘린더를 띄우고 다른 셀 선택하면 데이터가 들어가 버립니다.

**Comment by seonim-ryu** [comment]
@david80 
해당 내용은 확인하였으며 버그로 처리하여 다음 버전에 수정, 배포될 예정입니다.
그리고 추후 이슈 등록 시 해당 동작에 대해서 조금 더 자세하게 설명해주시면 감사하겠습니다.
