### ISSUE TITLE
grid 넓이가 사용자가 정한 최소 넓이보다 작아지면 가로 스크롤을 했을 때 레이아웃이 깨집니다.

### ISSUE THREAD

**Issue by kbs0327** [nhnent/tui.grid#5]
![image](https://cloud.githubusercontent.com/assets/8895856/12776700/883e7f3a-ca9b-11e5-84b6-07555e69f906.png)

**Comment by dongwoo-kim** [comment]
윈도우 resize 이벤트와 관련된 문제로 보이네요.

그리드에서 width가 따로 지정되지 않고 100%로 되어있는 경우 내부 컬럼 넓이 계산을 위해 window의 resize 이벤트가 발생할 때마다 레이아웃을 갱신합니다. 아마 해당 페이지에서 resize 이벤트를 통해 그리드를 포함하는 요소의 width를 변경하는 것 같은데..  그리드가 레이아웃을 갱신하는 타이밍보다 늦는 경우가 있는 것 같습니다.

부모요소의 width가 변경될 때 그리드의 `refreshLayout()` 메소드를 실행시켜서 강제로 레이아웃을 갱신하도록 하면 해결 될 것 같습니다.

**Comment by kbs0327** [comment]
아 감사합니다.
