### ISSUE TITLE
셀 병합 문의 드립니다

### ISSUE THREAD

**Issue by jaeyeolkim** [nhnent/tui.grid#50]
안녕하세요.
예제를 보면 셀 병합이 아래와 같이 데이터영역에 구현이 되어 있는데요.
>
    {
        name: '19',
        artist: 'Adele',
        release: '2008.01.27',
        type: 'EP',
        genre: 'Pop,R&B',
        _extraData: {
            rowSpan: { // Merge rows
                artist: 3,
                genre: 2
            }
        }
    },
>
혹시 이 방법 말고, 컬럼의 속성으로 병합을 구현할 수는 없는 건가요?
그리고 _extraData 의 속성들은 어디에서 찾아볼 수 있을까요?
감사합니다.

**Comment by seonim-ryu** [comment]
@jaeyeolkim 
안녕하세요. 그리드를 사용해주셔서 감사합니다.
현재 그리드에서는 행 병합(`rowspan`)은 제공하나 열 병합(`colspan`)기능은 제공하고 있지 않습니다.
열 병합 기능은 추후에 기능 개선건으로 등록되어 있는 상태이구요 :)
`_extraData`에 대한 속성은 [예제 페이지](http://nhnent.github.io/tui.grid/api/tutorial-example06.html) 참고 부탁드립니다.

**Comment by jaeyeolkim** [comment]
답변 감사드립니다.
rowspan 을 다른 방법으로 구현할 수 없는지 문의를 드렸던 거였는데 설명이 충분치 못했나봅니다..

1. 예제에서 artist 는 **3**, genre 는 **2** 를 지정해주어야 하는데,
  이렇게 하지 않고 컬럼 선언부에 rowspan: true 같은 속성으로 사용할 수 없는지 확인 요청을 드렸던 겁니다.

2. _extraData 속성은 rowState, className, rowSpan 이렇게 세 가지가 있다고 보면 되겠군요?

**Comment by seonim-ryu** [comment]
@jaeyeolkim 
`columns` 속성을 통해서 병합 처리를 문의하셨던거였군요 ^^;
현재는 `_extraData`를 통해서만 병합 처리가 가능합니다.

2번은 말씀하신대로 `rowState`, `className`, `rowSpan` 속성이 있고
추가로 각 개별 행의 높이를 지정할 수 있도록 `height` 속성도 제공하고 있는데요.

이번에 문의주신 내용들을 확인하면서 전체적으로 `_extraData` 속성에 대한 설명이 부족한 것 같아
추후 예제 페이지 및 튜토리얼을 보강할 예정입니다.

감사합니다. :)

**Comment by jinho1410** [comment]
업그레이드 된것인지 모르겠지만
포멧터로 두 데이터를 하나로 표시해 주는 건 가능한 것 같네요.
    columns: [
        {
            title: 'name',
            name: 'name',
            formatter: function(value, rowData) {
                return value + rowData.userId;
            }
        }
    ]
