### ISSUE TITLE
onblur 버그

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#52]
onblur 

키보드로 tab, enter 를 이용했을 경우 value값이 체인지 되는데

마우스로 다른 셀을 클릭했을 경우엔 onblur 는 타지만 값이 체인지 되어있지 않습니다.

**Comment by ksmark8543** [comment]
덧붙여 상세 내용을 말씀 드리자면.., 그리드 내 input box 에서 입력한 뒤 enter 키를 누를때 파라미터로 던져지게 팝업을 뜨게 했는데, onkeydown 이벤트 에서도 바뀐 값을 받을수가 없습니다.
그리고 onAfterChange 이벤트에서는 이런 행위들이 무척 잘 작동 하지만 셀을 복사해서 붙여 넣을경우 무조건 팝업이 떠 버려서 사실상 여기에도 넣었다가 도로 뺀 상황 입니다.
만약 이 문제가 해결 된다면 이래저래 가장 좋은 조건은 onKeyDown 가 1순위가 되겠네요..

**Comment by seonim-ryu** [comment]
@david80 @ksmark8543
먼저 현재 구현하시려는 기능을 파악하기가 어렵습니다.
문의주신 내용으로 보아 그리드에 직접 이벤트를 바인딩하여 사용하고 계신 것 같은데요.
사용하고 계신 샘플 코드를 전달해주시면 감사하겠습니다.
