### ISSUE TITLE
column의 width값을 % 값으로 줄 수 있나요?

### ISSUE THREAD

**Issue by okletsgo88** [nhnent/tui.grid#53]
width값을 고정 pixel 값으로 주면 화면 크기가 변할 때, 반응을 하지 않아서 각 칼럼의 길이를 다르게
반응형으로 만들려고 하는데, 그러면 %값이 필요할 것 같아서요. 혹시 방법이 있나요?

**Comment by seonim-ryu** [comment]
@okletsgo88
먼저 그리드를 사용해주셔서 감사합니다 :)
아쉽게도 현재는 pixel 값만 제공되고 있습니다.
퍼센트 값에 대한 처리는 개선 사항에 등록되어 있으며 추후에 다시 코멘트 드리겠습니다.
