### ISSUE TITLE
refreshLayout()를 호출될때 에러가납니다.

### ISSUE THREAD

**Issue by NiQst** [nhnent/tui.grid#54]
` refreshLayout: function() {
	        var domState = this.domState;
	        **var offset = domState.getOffset();**

	        this.set({
	            **offsetTop: offset.top,**
	            offsetLeft: offset.left,
	            width: domState.getWidth()
	        });

	        if (this.get('fitToParentHeight')) {
	            this.setHeight(domState.getParentHeight());
	        }
	    },`

SCRIPT5007: 정의되지 않음 또는 null 참조인 'top' 속성을 가져올 수 없습니다.

해당 볼드처리된 부분에서 발생되는데 원인을 알고싶습니다.

**Comment by NiQst** [comment]
해결됬네요...

**Comment by dvmoomoodv** [comment]
어떻게 해결하셨나요 ? 저도 똑같은 증상이 나오고있어서요.

**Comment by minsu0806** [comment]
Uncaught TypeError: Cannot read property 'top' of undefined
el 에 element를 잘못 지정 한 것 같습니다. $(selector).length 해서 결과가 0인지 아닌지 확인 해보세요.
