### ISSUE TITLE
TREE_GRID 구현은 언제쯤 될까요?

### ISSUE THREAD

**Issue by naerro** [nhnent/tui.grid#55]
CLOSED 된 이슈중에 TREE_GRID 관련 해서 상반기쯤 지원 하신다는 답변이 있어서 질문 드려 봅니다.
프로그램 구조, 조직도 표현 등의 용도로 사용하려고 합니다.
감사합니다.

**Comment by seonim-ryu** [comment]
@naerro 
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다 :)
내부 일정으로 인해 우선 순위가 밀려있어 아쉽게도 현재 지원이 어려운 상태입니다. ^^;
지원이 확정되면 다시 코멘트 드리겠습니다.
