### ISSUE TITLE
컬럼에서  json 하위 변수 가지고 오는 방법

### ISSUE THREAD

**Issue by kkange** [nhnent/tui.grid#56]
안녕하세요 질문 드려요

tui 컬럼 설정
```
{            
    name: "bbb.ccc",
    title: "담당자"
}
```

json 데이터
```
{
     aaa : "aaa",
     bbb: {
       ccc : "getData"
     }
}
```

위 json  데이터 처럼 ccc 를 가지고 오는 방법이 있나요

수고하세요

**Comment by kkange** [comment]
converter 써서 해결했어요

그런데 converter 를 쓰니까 수정을 할 수가 없던데 할수 있는 방법 없나요

**Comment by seonim-ryu** [comment]
@kkange
그리드의 컬럼 데이터는 `value` 값으로 참조 값(`object`, `array`)을 허용하지 않습니다.
위와 같이 초기 데이터 세팅은 가능하지만 `editOptions` 옵션을 통해 데이터를 수정할 경우 원본 데이터를 보장할 수 없기 때문에
초기 데이터를 세팅하기 전 그리드 데이터 포멧에 맞게 가공 후 사용하는 것을 권장합니다.
감사합니다 :)
