### ISSUE TITLE
데이터가 없을시 명칭 및 셀 크기 조절

### ISSUE THREAD

**Issue by RRBG-Logan** [nhnent/tui.grid#57]
데이터가 없을시 나오는 명칭과 셀 크기를 조절 할수 있나요?

**Comment by seonim-ryu** [comment]
@kkange
아쉽게도 기본 메세지에 대한 언어 선택(한글 or 영문)은 가능하나
외부에서 메세지를 세팅하는 api는 제공되고 있지 않아 추후에 제공할 예정입니다.

그리고 셀 크기는 메세지가 보여지는 영역에 대한 높이 값 설정을 말씀하시는건지요?
이 경우에는 `bodyHeight` 값으로 조정이 가능합니다. 확인 부탁드립니다 :)
