### ISSUE TITLE
아래 onblur 버그 코드 입니다.

### ISSUE THREAD

**Issue by ksmark8543** [nhnent/tui.grid#58]
editOptions : {
   type: 'text',
   onBlur: function(e, row){
						
/*
	예) 
		input box 의 value가 '홍길동' 인 상태에서..
	    '홍길동2' 라고 작성 한 뒤 마우스로 다른 셀을 클릭하였을 경우 아래 콘솔을 보면 이전 값인 '홍길동' 으로 찍힙니다.
*/
		console.dir(grid.getRow(row.rowKey));
    }
}

※ 그리고 keydown 이벤트 또한 바뀐값을 찾을수가 없어, 사실 이벤트가 있어도 제대로 활용 할 수가없네요.

**Comment by seonim-ryu** [comment]
@ksmark8543
데이터 변경 전/후 값에 대한 로직은 `onBeforeChange` 및 `onAfterChange` 콜백에서 처리하는 것이 맞습니다.
버그가 아니므로 해당 이슈 클로징합니다.
