### ISSUE TITLE
editingEvent: 'click' 속성과 formatter 같이 이용 할 경우 버그

### ISSUE THREAD

**Issue by ksmark8543** [nhnent/tui.grid#59]
editingEvent: 'click', //single click 으로 옵션을 주고
중략..
`
formatter: function(value, rowData) {
      return '<input type="text" id="farmer"'+rowData.rowKey+' name="farmer" onfocus="this.select();"  />';        
}
`

**onfocus 이벤트가 먹히고 나서 바로 포커스가 강제로 빠져나와 버립니다.**

**editingEvent: 'dblclick' 일 경우는 제대로 되구요..**

**Comment by seonim-ryu** [comment]
@ksmark8543
`formatter` 옵션은 변경된 형태로 데이터를 보여주기 위한 용도로 사용되기 때문에
위 예제와 같이 `input` 태그를 생성하여 사용하는 것은 권장하지 않습니다.
해당 내용은 버그가 아니므로 이슈 클로징합니다.
