### ISSUE TITLE
이미지 저장용 (for Meetup Blog)

### ISSUE THREAD

**Issue by dongwoo-kim** [nhnent/tui.grid#6]
1.
![various-inputs](https://cloud.githubusercontent.com/assets/12269489/15240040/d756be5a-1921-11e6-9252-2f915d645dc7.gif)

2.
![various-inputs-no-viewmode](https://cloud.githubusercontent.com/assets/12269489/15240068/fe529786-1921-11e6-9bba-3500f1bc57d4.png)

3.
![keyboard-navi](https://cloud.githubusercontent.com/assets/12269489/15240085/18dbbc86-1922-11e6-99a3-05b25c08b8e2.gif)

4.
![column-relation](https://cloud.githubusercontent.com/assets/12269489/15240102/2def12f8-1922-11e6-91fc-9549f1246826.gif)

5.
![virtual-scroll](https://cloud.githubusercontent.com/assets/12269489/15240104/34fe30e2-1922-11e6-8aad-19af4fcdccc2.gif)

6.
![pagination](https://cloud.githubusercontent.com/assets/12269489/15240122/5cbc807a-1922-11e6-9fbc-885115fd133a.gif)

7.
![theme-preset](https://cloud.githubusercontent.com/assets/12269489/15240164/a3f36170-1922-11e6-9c7c-0ba620bfe24c.gif)

8.
![theme-custom](https://cloud.githubusercontent.com/assets/12269489/15240166/ac13de66-1922-11e6-9b44-3dd543d4d97d.png)

**Comment by kangactor123** [comment]
<img width="133" height="73" alt="Image" src="https://github.com/user-attachments/assets/9987755c-171f-4850-b79a-d3ea21e7392d" />
