### ISSUE TITLE
체크박스 컬럼을 getRow()로 값을 확인해 보면 값의 Type이 일정하지 않습니다.

### ISSUE THREAD

**Issue by DandyU** [nhnent/tui.grid#61]
안녕하세요.

토스트 UI 그리드 사용해보니 여러가지 기능을 간편하고 쉽게 사용할 수 있어서 마음에 듭니다.

사용 중 특이한 현상이 발생해서 공유합니다.
checkbox로 값을 입력하는 경우 getRow()로 확인되는 값의 Type이 String 또는 Array로 일정하지 않은 현상이 있고요.
제가 테스트를 해보니 특정 Row의 checkbox 컬럼을 변경한 후 Type을 확인하면 String으로 확인되고
같은 Row에 있는 다른 컬럼을 변경한 후 checkbox 컬럼의 Type을 확인하면 Array로 확인됩니다.

checkbox 컬럼은 아래와 같습니다.
{
	title: 'Caption',
	name: 'caption',
	width: 70,
	align: 'center',
	onBeforeChange: function(ev){
		console.log('Before change:' + ev);
	},
	onAfterChange: function(ev){
		console.log('After change:' + ev);
	},
	editOptions: {
		type: 'checkbox',
		listItems: [
			{ text: 'kor', value: 'kor' },
			{ text: 'eng', value: 'eng' }
		],
		useViewMode: true
	}
}

**Comment by codepink** [comment]
@DandyU 
현재 질문해주신 내용이 잘 이해되지 않습니다 ^^;
먼저 `getRow()`를 호출했다고 하셨는데요.
아래 예제 코드와 같이 `onAfterChange()` 콜백에서 호출을 한건지,
또한 반환 값에 대한 타입 체크 로직도 해당 콜백에서 확인을 한 것인지 자세한 설명 부탁드립니다. 
```js
{
    title: 'Genre',
    name: 'genreCode',
    onBeforeChange: function(ev){
        console.log('Before change:' + ev);
    },
    onAfterChange: function(ev){
        console.log(grid.getRow(ev.rowKey)); // call api
    },
    editOptions: {
        type: 'checkbox',
        listItems: [
            { text: 'Pop', value: '1' },
            { text: 'Rock', value: '2' },
            { text: 'R&B', value: '3' },
            { text: 'Electronic', value: '4' },
            { text: 'etc.', value: '5' }
        ],
        useViewMode: true
    }
},
// ...
```

**Comment by DandyU** [comment]
@codepink 
안녕하세요. 답변이 늦었습니다.
콜백 함수에서 변경된 값을 확인하지 않았고요.
일괄 처리가 필요하여 특정 이벤트가 발생할 때 Grid의 모든 변경 내용을 확인하도록 하였습니다.
관련 소스 코드는 아래와 같습니다. 참고로 audio, caption의 타입은 체크박스입니다.

<pre><code>
function saveSchedule() {
	var optionsOpt = {rowKeyOnly: false};
	var modifiedRowsInfo = gMyGrid.getModifiedRows(optionsOpt);
	var createdRowsLength = modifiedRowsInfo.createdRows.length;
	var updatedRowsLength = modifiedRowsInfo.updatedRows.length;
	var deletedRowsLength = modifiedRowsInfo.deletedRows.length;
	
	var resultJsonObject = new Object();
	if (createdRowsLength != 0) {
		var createdJsonArray = new Array();
		for (var i = 0; i < createdRowsLength; i++) {
			var rowKey = modifiedRowsInfo.createdRows[i];
			var rowData = gMyGrid.getRowAt(gMyGrid.getIndexOfRow(rowKey, false), false);
			var rowJsonObject = makeJsonObject(rowData);
			createdJsonArray.push(rowJsonObject);
		}
		resultJsonObject.Created = createdJsonArray;
	}
	if (updatedRowsLength != 0) {
		var updatedJsonArray = new Array();
		for (var i = 0; i < updatedRowsLength; i++) {
			var rowKey = modifiedRowsInfo.updatedRows[i];
			var rowData = gMyGrid.getRowAt(gMyGrid.getIndexOfRow(rowKey, false), false);
			var rowJsonObject = makeJsonObject(rowData);
			updatedJsonArray.push(rowJsonObject);
		}
		resultJsonObject.Updated = updatedJsonArray;
	}
	if (deletedRowsLength != 0) {
		var deletedJsonArray = new Array();
		for (var i = 0; i < deletedRowsLength; i++) {
			var idx = modifiedRowsInfo.deletedRows[i].idx;
			deletedJsonArray.push(idx);
		}
		resultJsonObject.Deleted = deletedJsonArray;
	}
	var resultJsonString = JSON.stringify(resultJsonObject);
	console.log("JsonString: " + resultJsonString);
}

function makeJsonObject(rowData) {
	var rowInfo = new Object();
	if (typeof rowData.audio.valueOf() == "string") {
		...
	} else {
		for (var i = 0; i < rowData.audio.length; i++) {
			if (i == 0)
				rowInfo.audio = rowData.audio[i];
			else
				rowInfo.audio += "," + rowData.audio[i];
		}
	}
	if (typeof rowData.caption.valueOf() == "string") {
		...
	} else {
		for (var i = 0; i < rowData.caption.length; i++) {
			if (i == 0)
				rowInfo.caption = rowData.caption[i];
			else
				rowInfo.caption += "," + rowData.caption[i];
		}
	}
	return rowInfo;
}
</code></pre>

**Comment by seonim-ryu** [comment]
@DandyU 
해당 이슈 확인하여 답변드립니다.
먼저 코멘트 알람 누락 및 재현 어려움으로 인해 늦어진 점 양해해 주시기 바랍니다.

현상에 대한 원인으로 초기에 설정하는 그리드 데이터 포멧이 잘못된 것으로 파악됩니다.
`editOptions` 옵션으로 체크 박스 타입의 컬럼을 사용할 때 초기 데이터 값은 다음과 같이 문자열(`string`) 형태가 되어야 합니다.
만약 문자열이 아닌 배열로 설정할 경우, 다른 컬럼을 수정한 후 체크 박스 컬럼의 값을 출력하면 `object` 타입으로 출력됩니다. (문의 내용과 동일한 현상 발생)

```js
var data = [
    {
        // ...
        caption: 'kor', 'eng' // wrong format: ['kor', 'eng'] 
    }
];

grid.setData(data);
```
이전 코드에서는 데이터 세팅 부분이 없어, 확인 후 코멘트 부탁드립니다. :)

**Comment by DandyU** [comment]
값을 설정하는 과정에서 String 또는 Array가 혼용된 것 같습니다. 덕분에 문제를 찾을 수 있었습니다.
감사합니다. :)

**Comment by seonim-ryu** [comment]
@DandyU 
이슈 해결되어 클로징합니다. :)
