### ISSUE TITLE
버그에 관련된 답변이 제대로 안되는거 같네요~

### ISSUE THREAD

**Issue by david80** [nhnent/tui.grid#63]
저희 프로젝트에 토스트 그리드를 여러가지 방법으로 해결해 볼려고 했으나.
심각한 버그가 너무 많아~ 걷어 내기로 결정했습니다..

토스트 그리드 버그라던지 이런 대응이 좀더 원할하면 좋겠네요~

수고하십시오~

**Comment by seonim-ryu** [comment]
@david80 
안녕하세요. 기존에 문의주셨던 이슈들을 확인하던 중에 이런 글을 만나게 되어서 조금은 아쉽네요 ^^;

먼저 이슈 페이지는 _실시간 문의 게시판이 아니기에_ 등록한 이슈를 바탕으로
버그에 해당하는 것인지 또는 신규로 추가되어야 할 기능인지 등 충분한 검토 후에 답변을 드리고 있습니다.

오픈 소스의 경우 특정 서비스에 맞춰 개발된 것이 아니기 때문에
이슈가 발생한 상황에 대한 재현이 필요하며 이는 코드 몇 줄만으로는 즉각적으로 확인이 어려울 때가 많습니다.
개발 환경이나 구현하려는 기능에 대한 상세한 설명이 필요하며 해당 정보를 다시 요청하게 되는 이유이기도 하고요.
코멘트 전까지 소요되는 시간을 줄이고 좀 더 원할한 커뮤니케이션을 위해 [이슈 템플릿](https://github.com/blog/2111-issue-and-pull-request-templates)을 제공할 예정입니다.

그리고 오픈 소스는 말 그대로 _"열려있는 소스!"_ 입니다.
(정말 급하시다면) 직접 버그를 수정하거나 필요한 기능을 개발하여 저희쪽에 PR을 날려주시는 것도 가능합니다.

현재 내부적으로 Toast UI 정책 변경과 여러 작업들이 진행중이어서 이슈 확인이 더디어진 점 양해바랍니다.
이전에 등록하셨던 이슈들은 확인 후 클로즈 진행하겠습니다.

감사합니다 :)
