### ISSUE TITLE
heightResizable 옵션을 사용하면 문제가 있습니다.

### ISSUE THREAD

**Issue by app235** [nhnent/tui.grid#65]
그리드를 2개를 세로로 사용 중입니다

윗쪽 그리드에 heightResizable 옵션에 true를 주어 길이를 길게 늘이고 나서 

아랫쪽 그리드 아무 셀을 클릭하여 포커스를 주면 해당 클릭한 셀에 포커스가 생기지 않습니다.

**Comment by seonim-ryu** [comment]
@app235 
안녕하세요. 메일로 전달드린 내용과 같이 내부 버그로 처리하여 다음 배포 때 적용될 예정입니다.
그리고 이슈 등록 시 템플릿 사용에 유의 부탁드립니다.
