### ISSUE TITLE
setHeader 기능 지원

### ISSUE THREAD

**Issue by rosmaroto** [nhnent/tui.grid#66]
안녕하세요. tui grid 를 사용하여 vue.js에 적용중입니다.

혹시 setColumns 또는 setData 와 같은 header를 업데이트 할수있는 메서드는 지원하지 않는지 문의 드립니다.

grid 컴포넌트를 구성하여 아래와 같이 instance 를 생성하여 사용중인데 API에서는 header를 업데이트 하는것을 찾지 못하여 문의 드립니다.

```js
  mounted () {
    console.log('grid...')
    Grid.applyTheme('clean')
    this.instance = new Grid({
      el: this.$refs.grid,
      data: this.$props.gridData,
      scrollX: false,
      scrollY: false,
      header: {
        height: 80,
        complexColumns: this.$props.gridComplexColumns
      },
      columns: this.$props.gridColumns
    })
  },
  updated () {
    console.log('grid update...', this.instance)
    this.instance.setColumns(this.$props.gridColumns)
    this.instance.setData(this.$props.gridData)
    this.instance.refreshLayout()
  },
  beforeDestroy () {
    this.instance.destroy()
  }
```

**Comment by seonim-ryu** [comment]
@rosmaroto 
안녕하세요. 그리드를 사용해주셔서 감사합니다 :)

먼저 질문하신 내용 중에 확인할 부분이 있는데요.
헤더의 _어떤 데이터를 업데이트 하고자 하는지_ 에 따라 다른 답변을 드릴 수 있을 것 같습니다.

현재 사용하고 있는 `header` 옵션의 하위 값들을 변경하려고 하는 것인지,
아니면 헤더 영역에서 보여지는 타이틀 값을 변경하려고 하는 것인지 확인이 필요합니다.

`header` 옵션 값을 변경하려는 경우에는 현재 제공되는 API가 없으며,
헤더 영역의 타이틀 값을 변경할 때는 `setColums` API를 사용하여 변경 가능합니다.

그럼 해당 내용 확인 부탁드리겠습니다.

**Comment by rosmaroto** [comment]
@seonim-ryu 
안녕하세요 답변 감사드립니다.

우선은 instance의 header 를 업데이트하는 방식은 찾지 못하여 
element를 비우고 그리드를 새로 그려주는 방식으로 처리를 했습니다 ^^;


현재 구현 하려는 그리드는 아래같은 형식의 그리드입니다.

예를 들어 선택된 데이터의 타입 (주간, 월간) 과 날짜(시작일)에 따라서

- 주간, 9/25 시작일

<table class="tui-grid-table"><colgroup><col data-column-name="pjtNm" style="width:221px"><col data-column-name="busiDesc" style="width: 524px;"><col data-column-name="d1" style="width:51px"><col data-column-name="d2" style="width:51px"><col data-column-name="d3" style="width:51px"><col data-column-name="d4" style="width:51px"><col data-column-name="d5" style="width:51px"><col data-column-name="d6" style="width:51px"><col data-column-name="d7" style="width:51px"><col data-column-name="md" style="width:61px"><col data-column-name="mm" style="width:61px"></colgroup><tbody><tr><th data-column-name="pjtNm" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">구분</th><th data-column-name="busiDesc" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">구분2</th><th data-column-name="Mon" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">월</th><th data-column-name="Tue" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">화</th><th data-column-name="Wed" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">수</th><th data-column-name="Thu" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">목</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="Sun" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">일</th><th data-column-name="-" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">-</th><th data-column-name="-" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">-</th></tr><tr><th data-column-name="d1" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">25</th><th data-column-name="d2" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">26</th><th data-column-name="d3" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">27</th><th data-column-name="d4" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">28</th><th data-column-name="d5" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">29</th><th data-column-name="d6" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">30</th><th data-column-name="d7" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">1</th></tr></tbody></table>

- 월간 , 9/1 시작일 

<table class="tui-grid-table"><colgroup><col data-column-name="pjtNm" style="width:221px"><col data-column-name="busiDesc" style="width:51px"><col data-column-name="d1" style="width:51px"><col data-column-name="d2" style="width:51px"><col data-column-name="d3" style="width:51px"><col data-column-name="d4" style="width:51px"><col data-column-name="d5" style="width:51px"><col data-column-name="d6" style="width:51px"><col data-column-name="d7" style="width:51px"><col data-column-name="d8" style="width:51px"><col data-column-name="d9" style="width:51px"><col data-column-name="d10" style="width:51px"><col data-column-name="d11" style="width:51px"><col data-column-name="d12" style="width:51px"><col data-column-name="d13" style="width:51px"><col data-column-name="d14" style="width:51px"><col data-column-name="d15" style="width:51px"><col data-column-name="d16" style="width:51px"><col data-column-name="d17" style="width:51px"><col data-column-name="d18" style="width:51px"><col data-column-name="d19" style="width:51px"><col data-column-name="d20" style="width:51px"><col data-column-name="d21" style="width:51px"><col data-column-name="d22" style="width:51px"><col data-column-name="d23" style="width:51px"><col data-column-name="d24" style="width:51px"><col data-column-name="d25" style="width:51px"><col data-column-name="d26" style="width:51px"><col data-column-name="d27" style="width:51px"><col data-column-name="d28" style="width:51px"><col data-column-name="d29" style="width:51px"><col data-column-name="d30" style="width:51px"><col data-column-name="-" style="width:61px"><col data-column-name="-" style="width:61px"></colgroup><tbody><tr><th data-column-name="pjtNm" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">구분</th><th data-column-name="busiDesc" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">구분2</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="Sun" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">일</th><th data-column-name="Mon" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">월</th><th data-column-name="Tue" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">화</th><th data-column-name="Wed" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">수</th><th data-column-name="Thu" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">목</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="Sun" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">일</th><th data-column-name="Mon" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">월</th><th data-column-name="Tue" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">화</th><th data-column-name="Wed" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">수</th><th data-column-name="Thu" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">목</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="Sun" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">일</th><th data-column-name="Mon" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">월</th><th data-column-name="Tue" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">화</th><th data-column-name="Wed" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">수</th><th data-column-name="Thu" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">목</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="Sun" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">일</th><th data-column-name="Mon" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">월</th><th data-column-name="Tue" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">화</th><th data-column-name="Wed" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">수</th><th data-column-name="Thu" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">목</th><th data-column-name="Fri" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">금</th><th data-column-name="Sat" class="tui-grid-cell tui-grid-cell-head" height="38" colspan="1" rowspan="1">토</th><th data-column-name="-" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">-</th><th data-column-name="-" class="tui-grid-cell tui-grid-cell-head" height="78" colspan="1" rowspan="2">-</th></tr><tr><th data-column-name="d1" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">1</th><th data-column-name="d2" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">2</th><th data-column-name="d3" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">3</th><th data-column-name="d4" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">4</th><th data-column-name="d5" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">5</th><th data-column-name="d6" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">6</th><th data-column-name="d7" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">7</th><th data-column-name="d8" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">8</th><th data-column-name="d9" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">9</th><th data-column-name="d10" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">10</th><th data-column-name="d11" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">11</th><th data-column-name="d12" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">12</th><th data-column-name="d13" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">13</th><th data-column-name="d14" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">14</th><th data-column-name="d15" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">15</th><th data-column-name="d16" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">16</th><th data-column-name="d17" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">17</th><th data-column-name="d18" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">18</th><th data-column-name="d19" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">19</th><th data-column-name="d20" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">20</th><th data-column-name="d21" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">21</th><th data-column-name="d22" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">22</th><th data-column-name="d23" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">23</th><th data-column-name="d24" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">24</th><th data-column-name="d25" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">25</th><th data-column-name="d26" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">26</th><th data-column-name="d27" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">27</th><th data-column-name="d28" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">28</th><th data-column-name="d29" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">29</th><th data-column-name="d30" class="tui-grid-cell tui-grid-cell-head" height="39" colspan="1" rowspan="1">30</th></tr></tbody></table>



기간의 타입과 시작일이 변경될때마다 그리드를 새로 그리는 것이 문제는 없을것같으나, 
좀더 효율적인 방법이 있다면 조언 부탁드립니다.


좋은 그리드를 만들어 주셔서 잘쓰고있습니다.
감사합니다. ^^

**Comment by seonim-ryu** [comment]
@rosmaroto 
안녕하세요. 먼저 코멘트 알람이 누락되어 확인이 늦어진 점 양해부탁드립니다 ^^;

위 예제로 보아 동적으로 `headers.complexColumns` 값을 변경할 수 있는 API를 찾으시는 것 같구요.
아쉽게도 현재는 해당 API가 제공되지 않으며, 기능 검토 후 추후에 제공할 수 있도록 등록해두겠습니다.
(현재 상황에서는 처음 이슈에서 예제 코드와 같이 구현하여 사용하는 것이 맞습니다)

감사합니다 :)
