### ISSUE TITLE
tui-grid 잘 쓰고 있습니다. 근데 사용중에 잘 안되는 문제가 있어서 문의드립니다.

### ISSUE THREAD

**Issue by ahacross** [nhnent/tui.grid#67]
## Version

2.3
## Development Environment

chrome 60 win10 
## Current Behavior

![tui2](https://user-images.githubusercontent.com/1546934/30819927-5db5aba0-a25b-11e7-94ea-86dbe6a9a778.png)

이미지에서 색칠한 부분들이 문제 입니다. 
1. 주황색 체크박스를 출력하고 싶습니다. (근데 체크박스는 하나만 하는 예제도 없어서 여기에 적어봅니다.)
2. 값을 쓰면 total에 잘 반영되어야 하는데 반영이 됐다 안됐다 합니다.

```js
title:"완료",
name:"check",
width:50,
editOptions: {
     type:"checkbox",
     listItems :[{value:true}],
     useViewMode: true
}

```

## Expected Behavior

1.체크박스에 대한 값을 boolean 타입으로 가지고 있으면서 
true면 checkbox 를 checked를 true 하고 
false 면 checkbox 를 checked를 false 하고  싶습니다. 
근데 checkbox부터 안떠서 어떻게 해야 하는지 문의 드립니다. 

2. 이건 됐다 안됐다 합니다. 그냥 footer에 넣어준거 밖에 없어요....
   항상 잘 됐으면 좋겠는데 어떻게 하면 좋을까요??

**Comment by seonim-ryu** [comment]
@ahacross
안녕하세요. 그리드를 사용해주셔서 감사합니다. :)

먼저, 첫 번째 문의주신 체크박스 사용에 대한 내용은
초기 그리드 데이터 값을 받아서 체크박스 상태를 제어하는 기능을 찾으시는 것 같습니다.
이 경우 `editOptions` 대신 `rowHeaders` 옵션과 `_extraData` 값을 이용하면 처리가 가능합니다.
자세한 사용 방법은 [예제 페이지](http://nhnent.github.io/tui.grid/api/tutorial-example06-using-extradata.html)에서 확인하실 수 있구요.
참고로 `_extraData`는 그리드 데이터에 추가되는 데이터 값이며, 해당 값을 만들 때 조건에 맞게 가공하면 됩니다.

그리고 두 번째 내용은 포커스 버그로 인한 이슈로 보여집니다.
포커스 버그의 경우, 이번 달 정기 배포에 처리될 예정이며 배포 후 다시 확인 부탁드리겠습니다.

**Comment by ahacross** [comment]
감사합니다~ 
전 useViewMode: false 이렇게 변경함으로 해결했습니다~ ^^
_extraData로도 처리할 수 있군요~ ㅎㅎ
