### ISSUE TITLE
lodash 지원 안되나요?

### ISSUE THREAD

**Issue by love-zeus** [nhnent/tui.grid#68]
안녕하세요.

2.5 버전에서 lodash 를 이용하여 그리드를 사용해보려고 하는데요
_.mapObject 펑션이 없어서 사용을 못하는거 같습니다.

underscore 대신 lodash 도 사용 가능하다고 설명되어 있던데 이제 lodash 는 사용 불가능한건가요?

**Comment by seonim-ryu** [comment]
@love-zeus 
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다 :)

lodash 사용에 혼동이 있어 가이드를 드립니다.
그리드 내부에서 사용하는 underscore 메서드 중 일부는 lodash는 메서드와 다르기 때문에 underscore 대체하여 
lodash를 사용할 수는 없습니다. ([ref.](https://github.com/lodash/lodash/wiki/Migrating))

대신 콤비네이션 버전(`dist/tui-grid.comb.js`)을 사용하면 문의주신 내용과 같이 lodash 사용이 가능할 것으로 보입니다.
콤비네이션 버전을 사용할 경우 그리드 안에 underscore를 포함하고 있어 별도로 파일을 인클루드할 필요가 없으며, 서비스 페이지에서 사용하는 lodash와 충돌을 막을 수 있습니다.

해당 내용 확인 부탁드리겠습니다.

**Comment by love-zeus** [comment]
답변 감사합니다~
