### ISSUE TITLE
API 를 이용한 createData, updateData, modifyData, deleteData 각각 예제 파일을 올려주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by Jeongmunhun** [nhnent/tui.grid#69]
https://github.com/nhnent/tui.grid/wiki/Binding-to-remote-data
또는 API문서를 봐도 잘 모르겠더라구요....ㅜㅜ

죄송하지만 ....
createData, updateData, modifyData, deleteData 각각 예제 파일을 올려 주시면 
(같은 패턴 같으면 생략하더라도요.) 감사하겠습니다.

올라와 있는 예제는 readData 를 이용한 것인데... 
다른 것은 어떻게 써야 할 지 모르겠더라구요......ㅜㅜ

추가로 downloadExcel, downloadExcelAll 이것도 예제파일 부탁드립니다.^^

jeongmunhun@gmail.com

**Comment by seonim-ryu** [comment]
@Jeongmunhun 
안녕하세요. 그리드를 사용해주셔서 감사합니다. :)

먼저 현재 이해가 어려우신 부분이 _클라이언트측 기능 구현_ 에 대한 것인지 아니면 _서버측 처리_ 에 대한 것인지 확인이 필요합니다.

전체적인 사용 방법에 대한 내용은 예제 페이지에서 `Saving Changed Data` 목차에 설명되어 있으나 아래 간략하게 정리해드립니다. 데이터 생성(`creatData`)을 예로 설명드리며, 다른 액션들도 이와 동일하게 동작합니다.

### 1. URL 등록

`readData`와 동일하게 서버 통신을 위한 URL을 등록합니다.

```js
grid.use('Net', {
    perPage: 100,
    api: {
        createData: '/api/createData'
    }
});
```
### 2. 서버 요청

그리드에서 반환된 net 객체로 데이터 생성 액션에 대한 서버 요청을 처리합니다.
```js
var net = grid.getAddOn('Net');
...
// 그리드에서 데이터 생성 완료 후 서버 호출
net.request('createData');
```
이 때 서버에 요청되는 데이터 포멧은 다음과 같습니다. (서버 파싱용)
```
createRows=[{"c1":"생성 데이터 1","c2":"생성 데이터 2"}]
```

### 3. 서버 응답

커스텀 이벤트를 등록하여 서버 응답에 대한 액션을 처리합니다.
```js
grid.on('response', function(data) {
    console.log(data); // 서버 데이터
});
```

`downloadExcel`, `downloadExcelAll` 액션에 대한 사용 방법도 위와 동일한데요.
다만 기존에 기존에 제공하던 액셀 버튼을 직접 구현해야 사용이 가능합니다.
(액셀 기능 사용에 대한 내용은 튜토리얼 보강 예정입니다)

```js
//  Step 1: URL 설정
grid.use('Net', {
    perPage: 100,
    api: {
        createData: '/api/createData',
        downloadExcel: '/api/download/excel',
        downloadExcelAll: '/api/download/excelAll'
    }
});

// Step 2. 다운로드 액셀 버튼에 대한 기능 구현
var net = grid.getAddOn('Net');

net.download('excel'); // 부분 데이터 다운로드
net.download('excelAll'); // 전체 데이터 다운로드
```

그리고 추후 이슈를 등록해주실 때 이슈 템플릿에 맞추어 작성해주시면 감사하겠습니다. :)
