### ISSUE TITLE
그리드 height 문제

### ISSUE THREAD

**Issue by nofaterock** [nhnent/tui.grid#7]
안녕하세요. 
tui grid 를 사용해보고자 테스트 중 입니다.
bodyHeight 나 fitToParentHeight 가 설정된 상태에서 setRowList, appendRow 호출 시 그리드 높이가 row 수 만큼 늘어나거나 줄어드는 현상이 발견되어서 이슈 남깁니다.

```
var grid = new tui.Grid({
	el: $('#id'),
	headerHeight:20,
	rowHeight:20,
	bodyHeight: 300
});

grid.setRowList([
	{id:1,name:'A'},
	{id:2,name:'B'}
]);
```

**Comment by dongwoo-kim** [comment]
안녕하세요. TUI 그리드에 관심 가져주셔서 감사합니다 :)

현재 스펙대로라면 `bodyHeight`나 `fitToParentHeight`를 지정 하더라도 `isFixedHeight: true` 값을 지정해 주어야 데이터에 따라 높이가 자동 변경되지 않습니다.  다만, `isFixedHeight: true`인 경우 overflow 되는 영역이 제대로 표시되지 않는 현상이 있는데 이 부분은 현재 수정중에 있습니다.

수정중인 내용은 2-3일 내로 반영되어 패치 버전이 배포될 예정입니다. 참고 부탁드립니다.

**Comment by nofaterock** [comment]
isFixedHeight 가 있었군요 ..제 불찰입니다. ^^;;
감사합니다.
