### ISSUE TITLE
filter 기능이 가능한가요?

### ISSUE THREAD

**Issue by love-zeus** [nhnent/tui.grid#70]
api 문서를 봐도 아직 filter 관련된 기능은 보이지 않는데요...
혹시 제가 못 찾았다면 알려주세요~

findRows 를 이용해서 구현해야 하는것인지..아니면 다른 방법이 있는지요...

그리고 없다면 filter 기능 추가할 계획이 있으신지 궁금합니다.

감사합니다.

**Comment by seonim-ryu** [comment]
@love-zeus 
먼저 필터 기능과 관련해 어떤 내용을 검색하려고 하는지 확인이 필요합니다.
`특정 컬럼에 대한 값`으로 검색할 경우에는 문의주신대로 `findRows`를 사용하시면 처리가 가능할 것으로 보입니다.

그리고 추후 이슈를 등록해주실 때는 이슈 템플릿에 맞추어 작성해주시면 감사하겠습니다. :)

**Comment by love-zeus** [comment]
예를 들어 input box 에 text 를 입력하면 그리드 전체에서 필터링 하여 결과만 그리드에 보여준다던지
또는 각 컬럼별 헤더에 input box 에서 컬럼별로 필터링 되는 기능이 있으면 좋을 것 같아서요.
그리고 각 기능의 펑션화 하여 커스터마이징 되면 좋을거 같구요.

우선 findRows 로 처리해 보도록 하겠습니다.

다음부터는 이슈 템플릿에 맞추어 작성하겠습니다^^

**Comment by seonim-ryu** [comment]
@love-zeus 
문의주신 기능은 현재 이슈에 등록되어 있으며 추후에 기능 추가되면 다시 코멘트 드리겠습니다.
의견 주셔서 감사합니다. :)
