### ISSUE TITLE
section 과 focus 를 설정이나 펑션으로 막을 수 없을까요?

### ISSUE THREAD

**Issue by love-zeus** [nhnent/tui.grid#71]
## Version
2.5

## Development Environment
windows 10, Chrome 62

## Current Behavior
selection 기능을 on off, focus 기능을 on off 하고 싶은데 방법이 있을까요?

그리고 스크롤을 옮기기 위해서 focusAt 을 사용했는데 focus 를 바꾸지 않은 상태에서 스크롤을 이동 후에 같은곳으로 focusAt 을 하면 동작 안하는것 처럼 보이더라고요.
그래서 blur 를 먼저 한 후에 focusAt 해보면 정상 동작하던데 처음 의도가 같은 focus 에서는 동작 안하게 하신건지요? 아니면 버그인지요?

## Expected Behavior
selection 이 off 이면 section 동작 안하게
focus 가 off 이면 cell 에 click 해도 focus 안가게
같은 focus 여도 isScrollableopt = true 인경우는 무조건 scroll 이 이동되어야 할거 같습니다.
추가로 fucus 로 이동 안하고 scroll 만 이동할 수 있게 scrollTo 같은 기능이 있으면 좋을거 같습니다.

감사합니다.

**Comment by seonim-ryu** [comment]
@love-zeus 
현재 셀렉션 및 포커스 활성화 기능을 API로 따로 제공하고 있지는 않으나, 그리드 테마 기능을 사용하면 원하는 기능을 구현하실 수 있을 것으로 보입니다.

```js
tui.Grid.applyTheme('default', {
    selection: {
        background: 'transparent',
        border: 'transparent'
    },
    cell: {
        selectedHead: {
            background: 'transparent'
        },
        focused: {
            border: 'transparent'
        }
    }
});
```
 
그리고 `focusAt` 호출 후 스크롤을 이동하더라도 이미 포커스가 그리드 영역 안에 활성화되어 있기 때문에 다시 호출하더라도 스크롤되지 않는 것이 맞습니다.

위 내용 참고 부탁드립니다. :)

**Comment by love-zeus** [comment]
결국 scrollTo 기능을 하기 위헤서는 blur 을 후에 다시 focusAt 을 다시 하번 해야하는군요.

답변 감사드립니다.^^
