### ISSUE TITLE
Fire Fox 56.0.2 에서 select box 값이 변경되지 않습니다.

### ISSUE THREAD

**Issue by wooristory** [nhnent/tui.grid#72]
## Version

tui.grid-2.5.0
## Development Environment

Fire Fox 56.0.2 64bit
## Current Behavior

컬럼에 select 옵션을 넣고 값을 변경 하였지만 값이 변경되지 않음
Chrome 이나 MS Internet Explorer 에서는 정상적으로 값이 변경 됨
```js
// Write example code
```

## Expected Behavior

Fire Fox에서도 정상적으로 값이 변경 되었으면 좋겠습니다.

**Comment by seonim-ryu** [comment]
@wooristory
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다 :)
현재 셀렉트 옵션을 사용하였다고 하셨는데요. `editOptions`를 사용하셨는지요?
기본 동작 확인 시에는 파이어폭스에서도 정상 동작하여, 다른 옵션 사용에 의해 파생된 버그인지 확인이 필요합니다.
그리드 생성 시에 사용한 옵션 정보를 기입해주시면 확인 후 다시 코멘트 드리겠습니다.

**Comment by wooristory** [comment]
https://nhnent.github.io/tui.grid/api/tutorial-example04-input-types.html
주소에 나오는 select box 값을 변경 해도 변경이 되지 않는데요;;
파이어폭스를 삭제 후에 다시 설치해도 역시나 값이 변경이 이루어 지지 않습니다.

**Comment by seonim-ryu** [comment]
@wooristory 
예제 페이지 확인하여 전달드립니다.
현재 파이어폭스에서 `editOptions.type: 'select'`로 설정된 경우에는 동작에 이상이 없는 것으로 확인되었습니다.
<img width="182" alt="select" src="https://user-images.githubusercontent.com/18183560/32832788-0bd31806-ca40-11e7-84e7-625b840fa931.png">

`editOptions.type: 'checkbox'` 또는 `editOptions.type: 'radio'`인 경우에는 `label`을 클릭하였을 때만 값이 변경되며 이는 버그로 이슈에 등록된 상태입니다.
<img width="349" alt="checkbox" src="https://user-images.githubusercontent.com/18183560/32832979-9e03d0a8-ca40-11e7-93c5-b101ed1fb13f.png">


혹시 질문하신 내용이 체크박스, 라디오 버튼 동작에 대한 것인지 다시 확인부탁드립니다.
감사합니다.

**Comment by wooristory** [comment]
파이어폭스 버전이 57.0 64비트로 업데이트 되더니 정상 적으로 작동을 하네요..;;
