### ISSUE TITLE
모바일 소프트키보드 이슈

### ISSUE THREAD

**Issue by naitae99** [nhnent/tui.grid#74]
이 번에 처음 토스트 그리드를 사용해서 작업 중에 있습니다.
다름이 아니라 사용환경이 모바일 환경인데 별다른 이슈가 없이 잘 작동한다 생각했는데, 그리드 영역을 터치하면 편집이 아닌 상태에서도  모바일 키보드가 표시되고 있습니다.
이 부분을 해결 할 옵션이 있나 찾아 보고 있는데, 별다른 소득이 없네요.

답변 부탁 드립니다.

**Comment by seonim-ryu** [comment]
@naitae99 
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다. :)
문의주신 내용은 그리드 영역 선택 시 클립보드 복사 기능에 사용되는 input 앨리먼트에 의해 모바일 디바이스에만 나타나는 현상입니다.
현재 그리드는 모바일을 정식 지원하고 있지는 않으나 추후 지원 여부를 검토하고 있습니다.
확인 부탁드리겠습니다.

**Comment by seonim-ryu** [comment]
#182 이슈 재등록으로 클로즈합니다.
