### ISSUE TITLE
중간 row 삭제시 마지막 row heigth 값을 가져오지 못하는 현상 문의

### ISSUE THREAD

**Issue by rapune** [nhnent/tui.grid#75]
## Version
tui-grid.2.5.0

## Development Environment
chrome, ie
windows7

## Expected Behavior
그리드 옵션 bodyHeight 설정 및 virtualScrolling = true 두 옵션을 동시에 사용하면,
중간 row 삭제시 마지막 row의 height 값이 NaNpx; 로 세팅되어 마지막 row가 깨져보이는 현상이 일어납니다.

case )
bodyHeight 미설정, virtualScrolling = ture  => 정상삭제
bodyHeight 설정, virtualScrolling = false => 정상삭제
bodyHeight 설정, virtualScrolling = true => 중간 row 삭제시 마지막 row height값 NaNpx; 설정 됨.

확인 부탁드립니다.

**Comment by seonim-ryu** [comment]
@rapune
현상 확인하였습니다.
이슈로 등록하였으며 처리되면 다시 코멘트 드리겠습니다.
감사합니다. :)
