### ISSUE TITLE
모바일에서 On Click 이벤트시 키보드가 올라오면서 최상단 스크롤이 자동으로 작동하네요.

### ISSUE THREAD

**Issue by wooristory** [nhnent/tui.grid#76]
IOS 나  안드로이드 모바일에서 gridNotice.on("click", function(ev){ } 이벤트를 걸면 가상키보드가 올라오면서 화면 최상단으로 스크롤이 됩니다.
## Version

tui_grid-2.5.0
## Development Environment

안드로이드 7.0, IOS 11.1.2
## Current Behavior

```js
// Write example code
	gridNotice.on("click", function(ev){
		var sid = gridNotice.getValue(ev.rowKey, "sid", true);
		bbs_view_json("NOTICE", sid);
	});
```

## Expected Behavior

키보드가 올라오지 않고 스크롤도 작동하지 않고 클릭 이벤트만 작동하였으면 합니다.(현재 Web 브라우저에서 작동하는 것 처럼)

**Comment by seonim-ryu** [comment]
@wooristory 
먼저 현상에 대해 설명을 드리자면,
그리드 내부에는 클립보드 기능 사용 시 생성되는 앨리먼트가 있는데 셀을 선택할 경우 해당 앨리먼트에 포커스가 발생하게 됩니다.
모바일 디바이스에서는 `input`과 같이 편집 가능한 앨리먼트에 포커스가 발생하였을 때 키보드가 활성화되는 것이 기본 동작이며, 그리드는 모바일 환경을 지원하지 않아 해당 현상과 같이 동작하게 됩니다.
모바일 지원 여부에 대해서는 현재 검토중이며, 스펙 확정되면 이후 다시 코멘트 드리겠습니다. :)

**Comment by seonim-ryu** [comment]
#182 이슈 재등록하여 클로즈합니다.
