### ISSUE TITLE
셀 우클릭 후 해제 시 범위 지정 이슈

### ISSUE THREAD

**Issue by nhs312** [nhnent/tui.grid#77]
## Version

version: 2.5.0

## Development Environment

macOs. High sierra 10.13.1
chrome 62.0.3202.94 (64bit) 
## Current Behavior

그리드 셀에 우클릭 한 뒤 다른 셀에 좌클릭을 하게 되면 범위 지정이 됩니다.

## Expected Behavior

드래그가 아닌 클릭 액션에서는 특정 셀이 선택 되는게 필요합니다.

**Comment by seonim-ryu** [comment]
@nhs312 
해당 이슈 2.6.1 버전에 패치되었습니다.
확인 후 이슈 클로징 부탁드립니다. :)

**Comment by seonim-ryu** [comment]
해결되어 이슈 클로징합니다.
