### ISSUE TITLE
그리드 bodyHeight 관련 질문입니다.

### ISSUE THREAD

**Issue by wongi0603** [nhnent/tui.grid#79]
현재 높이 조절을 하고싶습니다.
원하는 스팩 : 500 이하일 경우 auto 
                      max(500) 일 경우 스크롤로 
하고싶습니다.

minBodyHeight 는 있는것 같은데 max는 없나요?ㅠㅠ

**Comment by seonim-ryu** [comment]
@wongi0603 
먼저 질문하신 내용에 대한 구체적인 설명이 필요해보입니다.
그리드 body 영역에 대한 높이를 동적으로 변경한다는 것인지, 아니면 body 영역의 높이는 고정하되 그리드 데이터에 따라 스크롤 생성을 다르게 처리하고 싶으신건지요?
현재 `bodyHeight` 옵션으로 고정된 높이 값을 설정할 수는 있으나 max 값을 처리하는 옵션은 없습니다.
구현하시려는 기능 설명을 추가해주시면 좀 더 자세히 도움드릴 수 있을 것 같습니다. :)
(그리고 추가로 이슈 등록 시에는 꼭 _이슈 템플릿_ 에 맞추어 등록 부탁드립니다)

**Comment by wongi0603** [comment]
답변감사합니다. 그냥 고정으로 가져가기로 했습니다.
다음부터 이슈 등록할때는 템플릿에 맞추어 등록하도록하겠습니다.
처음이라 몰랏어요 ㅠ.ㅠ ㅋ
감사합니다. 수고하세요~
