### ISSUE TITLE
최우측 그리드의 너비 조정시 mouseup을 해도 드래그상태로 활성화됨

### ISSUE THREAD

**Issue by mamings** [nhnent/tui.grid#8]
**재현 브라우저**
- 크롬에서 재현됩니다
- 작업시 IE에서도 재현되었으나 샘플예제에서는 재현되지 않습니다.]

**재현해보기**
예제(https://nhnent.github.io/tui.grid/api/tutorial-example1.html) 페이지 기준으로 설명드리자면

송장번호의 우측변을 클릭하여 그리드 너비를 조정할 때
1. 그리드가 그려진 엘리먼트 안에서 드레그 하여 조정시
- 이상없음
2. 그리드가 그려진 엘리먼트 바깥까지 드레그하여 조정하는 경우
- mouseup시에 mouseup된 위치까지 셀의 너비가 늘어나지 않는다.
- 드래그 상태인것처럼 커서가 활성화되어 계속 마우스를 따라서 너비가 조정된다. (그리드 안을 클릭해야 다시 원래의 커서/상태로 돌아온다.)
=> 송장번호가 아니라 메모와 같이 긴 텍스트인 경우, 텍스트 확인을 위해 너비를 조정해야할 일이 생깁니다.

**기대하는 바**
그리드 바깥까지 너비조정으로 드레그를 할 경우
1. mouse up 시에 드래그상태를 해지한다.
2. mouse up된 위치의 폭 만큼 그리드를 늘린다. (가능할까요? 아니면 조정가능한 기본 여분폭(?)이라도 기본으로 있었으면 좋겠습니다) 

고맙습니다.

**Comment by dongwoo-kim** [comment]
안녕하세요. 
해당 이슈는 기존에 처리가 되었던 문제인데요. 해당 예제 페이지 내에서는 iframe 내부에 들어가 있어서 재현이 되고 있는 것 같습니다. 확인 결과 IE에서는 재현이 되지 않고, 크롬과 사파리에서만 발생하고 있는 것 같구요. iframe을 사용하지 않거나 IE인 경우에는 문제가 없어 보이는데.. 혹시 아래 몇가지만 확인해 주실 수 있을까요?

1. https://nhnent.github.io/tui.grid/api/tutorials/example1.html (iframe 없는 예제 페이지) 에서도 재현이 되는지요? 
2. 작업시 IE에서 재현되었다고 했는데, 예제 페이지와 비교해서 특별히 다른 상황이 있나요?

**Comment by dongwoo-kim** [comment]
재현 상황이 명확하지 않아 Close 합니다.
