### ISSUE TITLE
jquery버전이 1.11 인데 저는 1.7.2인데

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#81]
Tui.Grid의 jquery버전이 1.11 인데 제프로그램의 jquery 버전은 1.7.2인데
1.7.2를 사용하면 TuiGrid가 인식이 안되고 1.11을 사용하면
기존jquery를 사용한곳에서 error가 발생합니다.
이럴때 어떻게 하나요?ㅠㅠ

**Comment by seonim-ryu** [comment]
@kjd95110
안녕하세요. 먼저 현재 상황만으로는 이슈 파악이 어렵습니다.
어떤 에러 코드 또는 에러 메세지가 발생하는지 추가 코멘트 달아주시면 감사하겠습니다.
그리고 앞으로 이슈 등록 시에 꼭 _이슈 템플릿_ 에 맞추어 작성 부탁드립니다. :)

**Comment by kjd95110** [comment]
version: 2.6.1
 InternetExplorer 11,windows 10
제프로그램에서 사용하는 (마스트페이지사용) jquery 버전이 1.7 버전인데
Tui.Grid에도 자체적으로 제공하는 jquery(1.11 버전)가 있드라구요
제가 사용하는 프로그램의  마스터페이지의  jquery버전(1.7)을 사용하면 에러가 뜨구요
TuiGrid자체적으로 사용하는 jquery를 포함시키면 에러없이 잘됩니다.
꼭 TuiGrid의 자체적으로 포함된 jquery(1.11) 를 써야하는지 여쭤보는거예요 
혹시 jquery 몇버전을 사용하면 jquery(1.11)과 호환되는지 여쭤봅니다.

**Comment by seonim-ryu** [comment]
@kjd95110 
현재 그리드 디펜던시로 사용되고 있는 jQuery 최소 지원 버전은 **1.8.3** 버전부터이고요.
만약 npm을 사용하여 노드 환경에서 개발할 경우 1.11.0 이상 버전 사용을 권장합니다.
jQuery 버전 업데이트하여 사용부탁드립니다.
