### ISSUE TITLE
이런기능은 어떻게 표현하나요?

### ISSUE THREAD

**Issue by kjd95110** [nhnent/tui.grid#82]
// a  Grid 
       AUIGrid.bind(gridid, "cellClick", function(event) { fncCellClick(event) });

    function fncCellClick(event) {	 
	        $('#ctl00_cphMain_rAdmincode').val(event.item.Admincode); 		//은행코드
	        $('#ctl00_cphMain_rBankcode').val(event.item.Bankcode); 			//결제코드
	        $('#ctl00_cphMain_hdnBank').val(event.item.Bankcode);               //결제코드기억
	        $('#ctl00_cphMain_rBankname').val(event.item.Bankname); 			//은행명
	        $('#ctl00_cphMain_rBankaccount').val(event.item.Bankaccount); 	//계좌번호
	        $('#ctl00_cphMain_rAccountowner').val(event.item.Accountowner);      //예금주
	        $('#ctl00_cphMain_rBankseq').val(event.item.Bankseq);               //은행출력순
}

위의 소스처럼 셀을 클릭했을때  행의 각셀 값을  가져와서 각Textbox에 값을 넣을수 있는데
tuiGrid에서는 어떻게 표현하는지요

**Comment by seonim-ryu** [comment]
@kjd95110 
일단 위에 소스만으로는 질문하신 내용에 답변하기가 어렵습니다만,
셀 클릭 이벤트를 사용한 부분은 커스텀 이벤트에서 `click` 또는 `mousedown` 이벤트를 사용하면 처리가 가능합니다.
(참조: https://github.com/nhnent/tui.grid/wiki/CustomEvent)

커스텀 이벤트 발생 시 넘어오는 파라미터 값에 클릭한 셀에 대한 `rowKey` 및 `columnName` 값이 포함되어 있으며, 이 값들로 데이터를 가져올 수 있습니다.
먼저 그리드 적용 후 코멘트 부탁드립니다.

**Comment by kjd95110** [comment]
grid.on('mousedown', function (ev) {
alert(ev.nativeEvent.target.textContent);
});
이렇게 하면 해당셀의 내용을 읽을수는 있어요
제가 원하는거은 해당셀클릭했을때  그셀의  [행의 내용]은 어떻게 읽어오는지 여쭤봅니다.

**Comment by seonim-ryu** [comment]
@kjd95110
`getRow()` API를 호출하여 해당 행의 데이터(컬럼 값)를 가져올 수 있습니다.

```js
grid.on('mousedown', function(ev) {
    console.log(grid.getRow(ev.rowKey));
});
```

**Comment by 2Seok0** [comment]
안녕하세요 질문하나 할께요ㅜㅜ

**Comment by 2Seok0** [comment]
안녕하세요 질문 하나만 하겠습니다 ㅜㅜ

위 내용처럼 
grid.getRow(ev.rowKey)로 선택한 컬럼들의 정보를 가져왔는데요 
그것을 따로 따로 핸들링하는 방법은 없나요???ㅜㅜ
