### ISSUE TITLE
rowHeaders 옵션주고 헤더쪽 크기변경 시도시

### ISSUE THREAD

**Issue by wongi0603** [nhnent/tui.grid#83]
## Version
 * bundle created at "Thu Nov 30 2017 15:09:08 GMT+0900 (KST)"
 * version: 2.6.0

## Development Environment
크롬 & Internet explorer 11
Windows 10
Asp.net

---------------------------------------

이슈내용입니다.
버그같아보입니다.

평소 셀단위로 클릭되던 포커스가 
rowHeaders: [
                {
                type: 'rowNum',
                width: 23
                }
            ]
옵션주고 헤더쪽 크기변경 시도시
row header (예로 No. 이거)  헤더쪽 크기변경을 하려고하면 크기변경안되고
포커스단위가 바뀌는 버그가있는것같습니다.
그리고 다른 오른쪽 셀을 클릭해도 포커스는 로우단위로되고 파란색 테두리 또한 가장 왼쪽 컬럼만 포커스가 갑니다.

![1111](https://user-images.githubusercontent.com/34563812/34367698-2ab0e47a-eaf1-11e7-9f6f-f9aa0714435f.PNG)
![2222](https://user-images.githubusercontent.com/34563812/34367699-2ad92700-eaf1-11e7-9a2e-8511f1ca2398.PNG)

**Comment by seonim-ryu** [comment]
@wongi0603
해당 현상 확인하였고 버그 이슈로 등록하여 처리될 예정입니다.
제보 감사합니다. :)

**Comment by seonim-ryu** [comment]
#184 이슈 재등록하여 클로즈합니다.
