### ISSUE TITLE
IE8 에서 edit 후 enter, esc 입력 시 셀 포커스를 잃어버리는 문제

### ISSUE THREAD

**Issue by nofaterock** [nhnent/tui.grid#9]
안녕하세요. 
IE8에서 edit 후 esc 또는 enter 로 종료한 경우 포커스를 잃어버리는 현상이 발생하는 것 같습니다. 

예제([https://nhnent.github.io/tui.grid/api/tutorials/example4.html](https://nhnent.github.io/tui.grid/api/tutorials/example4.html)) 기준으로 테스트 하였습니다.

감사합니다 ~

**Comment by dongwoo-kim** [comment]
안녕하세요.
재현상황 확인했습니다. 기존에 있던 버그인데.. 그동안 발견을 못하고 있었던 것 같네요..
수정되는대로 다음 패치 버전에 반영하도록 하겠습니다.
제보 감사드립니다 :)

**Comment by dongwoo-kim** [comment]
[1.7.1](https://github.com/nhnent/tui.grid/releases/tag/1.7.1)  버전에 반영되었습니다. 이슈 클로즈합니다.
