### ISSUE TITLE
Bootstrap 4 modal에 grid 표시 이상

### ISSUE THREAD

**Issue by naitae99** [nhnent/tui.grid#92]
안녕하세요.

Bootstrap 4.0 과 tui.grid 2.8.0를 함께 사용하려고 합니다.
일반적인 페이지에서의 grid 표시가 잘 됩니다.
modal 화면에 grid를 표시하고자 하는데, 표시가 되지 않습니다.
디버깅을 해보고자 chrome 개발자 모드에 진입하니, grid 내용이 표시되네요.

아래와 같이 부트 스트랩 모달을 표시하게 하고, 애니메이션 종료 후에 grid를 표시해도 동일 합니다.
$("#gridModal").modal(toogle);
$("#gridModal").on('hidden.bs.modal', function () {
	modalGridDraw();
});

**Comment by naitae99** [comment]
테스트하면서 스크립트 내용을 잘 못 붙여 넣었네요. ^^
$("#gridModal").modal(toogle);
$("#gridModal").on('shown.bs.modal', function () {
modalGridDraw();
});

**Comment by Leewangro** [comment]
저 혹시 저도 같은 문제를 겪고 있어서 그런데 예제를 하나 풀 소스로 올려주실 수 없을까요?

**Comment by kim-seung** [comment]
> 안녕하세요.
> 
> Bootstrap 4.0 과 tui.grid 2.8.0를 함께 사용하려고 합니다.
> 일반적인 페이지에서의 grid 표시가 잘 됩니다.
> modal 화면에 grid를 표시하고자 하는데, 표시가 되지 않습니다.
> 디버깅을 해보고자 chrome 개발자 모드에 진입하니, grid 내용이 표시되네요.
> 
> 아래와 같이 부트 스트랩 모달을 표시하게 하고, 애니메이션 종료 후에 grid를 표시해도 동일 합니다.
> $("#gridModal").modal(toogle);
> $("#gridModal").on('hidden.bs.modal', function () {
> modalGridDraw();
> });

안녕하세요 똑같은 문제를 겪고 있는데 혹시 해결방안 좀 알 수 있을까요?? 부탁드립니다!

**Comment by naitae99** [comment]
> > 안녕하세요.
> > Bootstrap 4.0 과 tui.grid 2.8.0를 함께 사용하려고 합니다.
> > 일반적인 페이지에서의 grid 표시가 잘 됩니다.
> > modal 화면에 grid를 표시하고자 하는데, 표시가 되지 않습니다.
> > 디버깅을 해보고자 chrome 개발자 모드에 진입하니, grid 내용이 표시되네요.
> > 아래와 같이 부트 스트랩 모달을 표시하게 하고, 애니메이션 종료 후에 grid를 표시해도 동일 합니다.
> > $("#gridModal").modal(toogle);
> > $("#gridModal").on('hidden.bs.modal', function () {
> > modalGridDraw();
> > });
> 
> 안녕하세요 똑같은 문제를 겪고 있는데 혹시 해결방안 좀 알 수 있을까요?? 부탁드립니다!

바로 아래 스크립트 내용이 잘 못 되었다고 남겼는데요.
hidden.bs.modal 이 아니라 shown.bs.modal 입니다.
모달이을 표시하는 애니메이션이 완료된 후에 grid를 그리게 하면 문제는 해결 됩니다.
