### ISSUE TITLE
컬럼 고정방법 및 removeCheckedRows()

### ISSUE THREAD

**Issue by limdaesun** [nhnent/tui.grid#94]
안녕하세요
몇가지 기초적인 질문좀 드릴려고 합니다.

![1](https://user-images.githubusercontent.com/8321842/37134489-1f0c997a-22dc-11e8-9d54-149cc3d9b61a.PNG)

일단 컬럼수가 많아서 가로 스크롤을 생성할수 밖에 없는 상황입니다.
가로 스크롤 이동시 앞에 몇개의 컬럼은 고정되고 싶습니다.
방법이 없을까요?

또한 화면에 보이듯이 row 를 입력받은 값으로 생성하고 있습니다.(appendRow())
대량 생성시에는 그럭저럭 느리지 않지만 삭제할때 굉장히 반응속도가 느립니다.
예를 들어 100개의 로우를 생성하고 
전체선택후 removeCheckedRows 로 삭제시 시간이 많이 소요 되더군요.
그래서 removeCheckedRows 전후로 logding 레이어를 jquery로 show(), hide()  할려고 시도 했지만
removeCheckedRows 진행전 진행후를 나누기 어려워서 원하는 효과를 보고 있지 못하고 있습니다.
promise.js 를 얹어서 시도 했지만 방법을 못찾겠더라구요
혹시 관련해서 조언 부탁 드립니다

**Comment by seonim-ryu** [comment]
@limdaesun 
먼저 첫 번째 기능은 `options.columnOptions.frozenCount` 옵션을 사용하여 처리가 가능합니다.
해당 옵션에 고정하고자 하는 컬럼 개수를 지정하면 보더가 생성되며, 보더 기준으로 왼쪽 컬럼은 고정 오른쪽 컬럼 영역에는 가로 스크롤이 생성됩니다.

두 번째 기능은 대용량 데이터 사용의 경우인 것으로 보이는데요.
그리드에서는 2가지 렌더링 방식을 지원하고 있으며, 대용량 데이터의 경우 부분적으로 리스트를 보여주는 방식으로 처리를 할 수가 있습니다.
`virtualScrolling` 옵션을 사용하면 해당 기능을 사용할 수 있고, 다음과 같이 `rowHeight` 프로퍼티를 추가적으로 지정해야 정상 동작합니다.
이 방식을 사용하였을 때도 성능이 떨어진다면 다시 코멘트 부탁드리겠습니다.
```js
// grid option
{
    virtualScrolling: true,
    rowHeight: 20
}
```
그리고 이후 이슈 등록 시에 꼭 `이슈 템플릿` 사용 부탁드립니다.
감사합니다. :)

**Comment by limdaesun** [comment]
감사합니다.
컬럼 고정 옵션은 안내 주신것 처럼 잘 처리 되었습니다.
렌더링 방식은 알려 주신것처럼 데이터 바인딩시 virtualScrolling 처리 하는 것을 것이 아닌 다른 부분을 질문하고자 했던건데 . 새로운 이슈로 등록해서 질문 드리겠습니다. ^^
