### ISSUE TITLE
pagination 관련 

### ISSUE THREAD

**Issue by AhnSeongHyun** [nhnent/tui.grid#97]
```javascript
     grid.use('Net', {
            perPage: 10,
            readDataMethod: 'GET',
            api: {
                readData: 'api/posts'
            }
        });

         grid.on('beforeRequest', function(data) {
            // For all requests
        }).on('response', function(data) {
            var pagination = grid.getPagination();
            grid.setData(data.responseData.data.items);
            pagination.setTotalItems(data.responseData.data.total);
            pagination._currentPage = data.responseData.data.page;
            pagination.reset();
        })
```

`pagination:true` 인 상태에서 위와 같이 코드를 작성했는데, `pagination.reset()` 을 하지 않으면 
전체 페이징 표시가 안되어서 넣었습니다. 그런데, 2페이지로 가면 데이터는 가져와서 표시하는데 현재 페이지 표시하는것(파란색 표시)이 자꾸 1페이지로 표시되는데 `pagination.reset();` 을 호출해서 그런지 문의 드립니다.

**Comment by seonim-ryu** [comment]
@AhnSeongHyun 
안녕하세요. 먼저 그리드를 사용해주셔서 감사합니다.

문의주신 내용대로 `reset` 사용으로 인해 해당 현상이 발생한 것은 맞으나,
로직대로라면 Net을 사용한 경우에는 그리드 내부에서 자동으로 페이징을 처리하기 때문에 `response`에서 별도의 처리를 하지 않아도 됩니다.

아래 예제는 Net 사용 예제이며, 현재 `readData` 옵션에 설정된 API 응답값에 `pagination` 프로퍼티가 포함되어 있지 않아 페이지네이션이 정상 동작하지 않는 것으로 보입니다.

* https://nhnent.github.io/tui.grid/api/tutorial-example10-using-net.html

```js
// server response data
{
    result: true,
    data: {
        contents: data,
        pagination: { // set pagination
            page: 1,
            totalCount: 20
        }
    }
}
```

다음과 같이 사용해보시고 코멘트 주세요.
그리고 다음 이슈부터는 꼭 [이슈 템플릿](https://github.com/nhnent/tui.grid/blob/production/docs/ISSUE_TEMPLATE.md) 사용하여 등록 부탁드리겠습니다. :)

**Comment by AhnSeongHyun** [comment]
감사합니다. 해당 내용 적용하니까 잘 되네요 ^^
